### ISSUE TITLE
More id dropping at low zooms (roads)

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1002]
In completing https://github.com/tilezen/vector-datasource/issues/952, we have mostly removed `id` properties on merged features (where the `id` wasn't deterministic. 

But zoom 14 is a little interesting, though, as some minor roads are still getting IDs?
- http://tile.dev.mapzen.com/vector/v1/all/14/2619/6331.topojson?api_key=vector-tiles-HqUVidw

```
type: "MultiLineString",
properties: {
sort_key: 358,
landuse_kind: "retail",
kind: "minor_road",
source: "openstreetmap.org",
kind_detail: "service"
},
arcs: [
[
3870
],
[
3871
]
]
},
{
type: "LineString",
properties: {
source: "openstreetmap.org",
kind: "minor_road",
name: "Gardener Rd.",
kind_detail: "residential",
sort_key: 360,
landuse_kind: "parking",
id: 8915543
```

**Comment by zerebubuth** [comment]
We don't drop the `id` when the feature was unique and there were no merge candidates. Because the feature is unique, the ID is still meaningful. In this case, we don't drop `name` on `minor_road` until z13 and the combination of `name` and `landuse_kind` probably makes it unique.
