### ISSUE TITLE
Integrate differ tool with integration tests

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1007]
Tangram [Differ](https://github.com/tangrams/differ) might be useful way to visualize changes in a release (or even a PR) via integration-tests.

**Comment by iandees** [comment]
My thought here is that a bot listening to GitHub PRs could render an image of an area of interest (as specified in the description of the PR or something?) and then as commits come in on the PR it could render new images based on the vector tiles produced after the changes on the PR's branch.

**Comment by zerebubuth** [comment]
A potential problem with this is the state of the database. Any PR, or release, might contain arbitrary changes to the database including changes to the schema, to the min zooms or even to [how we run osm2pgsql](https://github.com/tilezen/vector-datasource/pull/943). To produce useful visual changes, the database(s) used to generate the tiles for "before" and "after" would need to contain a significant amount of data, which might need to be loaded from scratch each time, or restored using something like PITR.

Two things that I think we would need before starting on the PR visualisation are:

1. A way to test migrations. That means we can check that a database made from the merge target plus migrations in the PR still passes the tests. This could help us to avoid loading all the data from scratch each time (barring further drastic changes like the hstore-all one).
2. A tile server for "master" which is migrated on each merge, and kept up-to-date with diffs. Tiles could then be pre-rendered for a limited TOI on each merge commit.

**Comment by nvkelso** [comment]
While a good idea, this never took off. Closing.
