### ISSUE TITLE
Move optional pois layer JINJA tags to YAML

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1008]
Following up with https://github.com/tilezen/vector-datasource/issues/719, in moving `cuisine` and `sport` values to `kind_detail` we should remove those properties (in keeping with the changes in the roads layer in the v1 release).

While dropping `cuisine` looks straight forward, there are a couple other features that still are interesting with `sport`, I think, besides pitches (in landuse and pois)? 

These often map to several (but not many) kinds:

```
    tags->'cuisine' AS cuisine,
    tags->'religion' AS religion,
    tags->'sport' AS sport,
    (transit_routes).score AS mz_transit_score,
    (transit_routes).root_relation_id AS mz_transit_root_relation_id,
    (transit_routes).train_routes AS train_routes,
    (transit_routes).subway_routes AS subway_routes,
    (transit_routes).light_rail_routes AS light_rail_routes,
    (transit_routes).tram_routes AS tram_routes,
    tags->'ref' AS ref,
    tags->'attraction' AS attraction,
    tags->'zoo' AS zoo,
    tags->'exit_to' AS exit_to,
```

I think  `tags->'operator' AS operator,` is interesting to have on all features, so propose leaving that in jinja file.

**Comment by rmarianski** [comment]
For everything we drop from the queries, it's worth checking the queries.yaml file as well as the transforms to see if it gets used downstream. For example, there's label placement logic related to the [sport](https://github.com/tilezen/vector-datasource/blob/9526e79b73e01da8cc8b444fcf76a39879b6a89a/queries.yaml#L472) tag, which gets dropped in a subsequent [transform](https://github.com/tilezen/vector-datasource/blob/9526e79b73e01da8cc8b444fcf76a39879b6a89a/queries.yaml#L482-L491) at lower zooms.

**Comment by nvkelso** [comment]
This was completed in Fall 2017.
