### ISSUE TITLE
Review sort_key spreadsheets

### ISSUE THREAD

**Issue by rmarianski** [tilezen/vector-datasource#1012]
We've normalized some `kind` and `kind_detail` values. We should review the `sort_key` spreadsheets to ensure that they match on the new values.

In particular, the boundaries spreadsheet needs updating.

**Comment by nvkelso** [comment]
Other layers look fine (Matt already updated roads), it's just boundaries that needs work.

**Comment by nvkelso** [comment]
This is working.
