### ISSUE TITLE
Missing localized names on region boundary

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1016]
* **What did you see?** I only see default names (including left and right names, see below).
* **What did you expect to see?** The [source data from OSM](http://www.openstreetmap.org/relation/165473) has names in a couple dozen languages (see below).
* **What map location are you having problems with?** 
  - http://tile.dev.mapzen.com/vector/v1/all/8/42/96.topojson?api_key=vector-tiles-HqUVidw

```
type: "LineString",
properties: {
kind: "region",
name: "Nevada - California",
sort_key: 250,
kind_detail: "4",
id:right: -165475,
id:left: -165473,
name:right: "California",
id: -165473,
osm_relation: true,
name:left: "Nevada"
},
arcs: [
0
]
```

From OSM:

```
name:ar	نيفادا
name:arc	ܢܝܒܐܕܐ
name:bn	নেভাডা
name:el	Νεβάδα
name:en	Nevada
name:eo	Nevado
name:fa	نوادا
name:hak	Nui-fà-tha̍t
name:he	נבדה
name:hi	नेवाडा
name:hy	Նևադա
name:ja	ネバダ州
name:ka	ნევადა
name:ko	네바다
name:ml	നെവാഡ
name:mr	नेव्हाडा
name:nv	Ná'aazhoozh Hahoodzo
name:os	Невадæ
name:pl	Nevada
name:qu	Nevada suyu
name:ru	Невада
name:sr	Невада
name:szl	Newada
name:ta	நெவாடா
name:th	มลรัฐเนวาดา
name:tl	Nebada
name:uk	Невада
name:ur	نیواڈا
name:yi	נעוואדא
name:zh	内华达州
```

**Comment by nvkelso** [comment]
(Found this in completing https://github.com/tilezen/vector-datasource/issues/1012.)

**Comment by iandees** [comment]
So far my exploration has shown that the New York/New Jersey border [on prod](https://vector.mapzen.com/osm/boundaries/15/9643/12327.topojson) has New Jersey on the right while it is currently on the left [on dev](https://vector.dev.mapzen.com/osm/all/15/9643/12327.topojson). Also, the prod tile has a geometry for "New York - New Jersey" and a separate geometry for "New Jersey" while the dev tile has a geometry for "New Jersey - New York" and a separate geometry for "New York".

Also curious: the dev and prod tiles calls them `"kind": "state"` while my local tileserver running master calls them `"kind": "region"`. My local tileserver also only has a single geometry for "New Jersey - New York" and no extra geometry for "New York". These things seem more correct, so they're probably the result of bug fixes, but I would have expected dev to have these fixes too.

**Comment by iandees** [comment]
Debugging my way through transform.py, it looks like boundaries don't have their `source` property set, so [this line](https://github.com/tilezen/vector-datasource/blob/2e9b1291235f4e87e15938a34eeec75302f8bc0c/vectordatasource/transform.py#L449) is returning `None`, which skips the i18n tag transformations.

**Comment by iandees** [comment]
Adding a `source` column to the boundaries queries in 3f01980 seems to have fixed it.

**Comment by nvkelso** [comment]
WFM
