### ISSUE TITLE
Myanmar is replaced by water past z11

### ISSUE THREAD

**Issue by louh** [tilezen/vector-datasource#1029]
* **What did you see?**

Water

* **What did you expect to see?**

Thailand

* **What map location are you having problems with?** _City and country are helpful, as well as tile coordinates or latitude / longitude._  

https://tangrams.github.io/tangram/#16.42728507395366,97.64670482405815,11.427444687527228
(Click zoom out, it comes back. The extent of land missing goes as far south as https://tangrams.github.io/tangram/#10.19112790050563,98.61092430106544,11.427444687527228 and may go even farther north, but I didn't check)

* **Screenshot?** _Props for animated gifs._

at z10
![tangram-1473340655540](https://cloud.githubusercontent.com/assets/2553268/18350729/3bfba4ee-75a5-11e6-97e6-1c90da188650.png)

at z11 - note the labels and roads are still present
![tangram-1473340660074](https://cloud.githubusercontent.com/assets/2553268/18350734/3ee6622a-75a5-11e6-9f75-1312ed6b9c88.png)

**Comment by zerebubuth** [comment]
Thailand looks okay to me - the area which is underwater is Myanmar. It seems that it's because someone added a `waterway=river` tag to the [Myanmar country polyon](http://www.openstreetmap.org/relation/50371), making a giant water polygon which covers the land.

I'm not sure why this isn't also affecting the map on osm.org, though.

**Comment by louh** [comment]
Oops - you're totally right, I was just looking for Thailand when I saw this.

Is there ever a legitimate reason to add that tag to a country polygon?

**Comment by zerebubuth** [comment]
Not that I can think of, and I've removed it in [changeset 42005776](http://www.openstreetmap.org/changeset/42005776). Although I've never been to Myanmar, I'm fairly sure that its whole boundary isn't a river - although it would be to live in an M. C. Escher print with all the perpetual, free hydro power.

**Comment by nvkelso** [comment]
![escher_waterfall](https://cloud.githubusercontent.com/assets/853051/18356964/dd1e81f4-75a3-11e6-9c94-481d3b442e06.jpg)

**Comment by louh** [comment]
Totes fixed
