### ISSUE TITLE
relation "water_polygons" does not exist

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [tilezen/vector-datasource#1042]
So I went through all the installation steps from [Mapzen wiki](https://github.com/tilezen/vector-datasource/wiki/Mapzen-Vector-Tile-Service), except that instead of [new-york_new-york.osm.pbf](https://s3.amazonaws.com/metro-extracts.mapzen.com/new-york_new-york.osm.pbf) i imported the whole planet [planet-latest.osm.pbf](http://planet.openstreetmap.org/pbf/planet-latest.osm.pbf).

Everything went fine, until I requested `http://localhost:8080/buildings/16/19293/24641.json` and this gave me an error:

> 127.0.0.1 - - [14/Sep/2016 03:27:12] "GET /buildings/16/19293/24641.json HTTP/1.0" 500 -
Traceback (most recent call last):
  File "/home/linuxadmin/Mapzen/tileserver/tileserver/__init__.py", line 195, in __call__
    response = self.handle_request(request)
  File "/home/linuxadmin/Mapzen/tileserver/tileserver/__init__.py", line 290, in handle_request
    coord, self.layer_config.all_layers)
  File "/home/linuxadmin/Mapzen/env/lib/python2.7/site-packages/tilequeue/query.py", line 206, in __call__
    raise async_exception
ProgrammingError: relation "water_polygons" does not exist
LINE 16: FROM water_polygons t

I also imported new-york_new-york.osm.pbf after all, and I didn't have this problem.
Can anyone share some tip? :)

**Comment by zerebubuth** [comment]
The steps to [load additional data](https://github.com/tilezen/vector-datasource/wiki/Mapzen-Vector-Tile-Service#load-additional-data-and-update-database), specifically:

```
# Go to data directory
cd vector-datasource/data
# Build the Makefiles that we'll use in the next steps
python bootstrap.py
# Download external data
make -f Makefile-import-data
# Import shapefiles into postgis
./import-shapefiles.sh | psql -d osm
# Add indexes and any required database updates
./perform-sql-updates.sh -d osm
# Clean up local shape files
make -f Makefile-import-data clean
```

Should have downloaded a set of shapefiles and imported them into the database. After the `make -f Makefile-import-data` step, you should have many shapefiles in the `data/` directory. One of those shapefiles, called `water-polygons-split-3857/water_polygons.shp`, will be loaded into the database in the next step, `./import-shapefiles.sh | psql -d osm`.

It's worth checking that the steps all completed correctly - in particular, that the shapefile package downloaded and extracted okay. Here are the MD5 checksums from the download I just did - they should match yours.

```
98868b62c54f88a4ee2a6512b082785f  shapefiles.tar.gz
9e8636f67f3608f73f28a7d2883b25f6  water-polygons-split-3857/water_polygons.shp
```

If they don't match, you might need to clean out the files and try downloading them again.

Hope that helps!

**Comment by ktrzeciaknubisa** [comment]
Thanks @zerebubuth 

You might be right. I was reloading the data multiple times and so perhaps I might omitted the steps at some point. 
But the `./perform-sql-updates.sh` script runs so long for me (5 days until now) - is it expected behavior for the whole planet database? The last log entry I got is:

```bash
Applying updates in parallel across tables...
...
CREATE INDEX
UPDATE 1420
CREATE INDEX
UPDATE 2796
CREATE INDEX
UPDATE 625888
CREATE INDEX
DO
ANALYZE
``` 

and it seems hanging on this.

**Comment by ktrzeciaknubisa** [comment]
Ok, it seems like it completed after 10 days... Thanks

**Comment by sroycode** [comment]
Actually the first time run gives the not-found error during the attempted delete ... can be ignored
