### ISSUE TITLE
Road names and neighborhood names disappearing after zoom level 14th

### ISSUE THREAD

**Issue by 20sandeepsingh** [tilezen/vector-datasource#1057]
I have set up the vector tile service few days back by downloading india.pbf from geofabrik. When I started comparing mapzen's vector tiles with the tiles I have generated, I found that the road and neighborhood names goes missing after zoom level 14th. How can I fix this issue. I am using cinnabar style to visualize it.

**Comment by nvkelso** [comment]
Can you provide a link to your scene file and tile endpoint?

**Comment by 20sandeepsingh** [comment]
Scene file:
http://sandeepsingh.justdis.com/cinnabar-style.yaml

Tile endpoint:
http://sandeepsingh.justdis.com/vtiles/all/{z}/{x}/{y}.topojson

**Comment by 20sandeepsingh** [comment]
You will get tiles only for metros in India e.g. Mumbai, Bangalore, Delhi
etc.

**Comment by nvkelso** [comment]
Both of these links are password protected :\

**Comment by 20sandeepsingh** [comment]
Can you please tell me your email address and I will send you the username
and password.

**Comment by nvkelso** [comment]
nathaniel@mapzen.com
