### ISSUE TITLE
Add line offset information for transit

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1058]
- **What did you see?** Transit lines overlap each other.
- **What did you expect to see?** They should be offset from each other. This might require a new "topological" alternative to the existing `transit` layer (and could also include topology from the transit stations & etc).
- **What map location are you having problems with?** [San Francisco](http://tangrams.github.io/bubble-wrap/#11/37.7911/-122.3026), New York, global.
- **Screenshot?** 

I see: 
<img width="666" alt="screen shot 2016-09-19 at 13 41 14" src="https://cloud.githubusercontent.com/assets/853051/18648316/f43f9cf0-7e6e-11e6-9466-58d62a801966.png">

I want to see:
![system-map](https://cloud.githubusercontent.com/assets/853051/18648315/f4244b4e-7e6e-11e6-9847-fb997532c58b.gif)

**Comment by iandees** [comment]
I always thought that Chicago's loop was an interesting testcase for this. [Google does a particularly poor job](https://www.google.com/maps/@41.8810361,-87.6293917,15.83z/data=!5m1!1e2):

![image](https://cloud.githubusercontent.com/assets/261584/18648732/f34d1762-7e89-11e6-81d0-f6f3196f34c5.png)

Actual:

![image](https://cloud.githubusercontent.com/assets/261584/18648758/0db0c2ac-7e8a-11e6-99e0-f22f3f36b090.png)

**Comment by nvkelso** [comment]
Yes on Chicago! 

**Berlin** is another worst edge case, especially with the different regional, commuter, subway, and light rail systems all mixing along shared rights of way.

**Comment by nvkelso** [comment]
See also:

- https://medium.com/transit-app/how-we-built-the-worlds-prettiest-auto-generated-transit-maps-12d0c6fa502f#.tmoz51mac

**Comment by nvkelso** [comment]
Forward dup of https://github.com/tilezen/vector-datasource/issues/1189.
