### ISSUE TITLE
Missing buffer for "roads" layer?

### ISSUE THREAD

**Issue by yohanboniface** [tilezen/vector-datasource#106]
Compare a [geojson](http://vector.mapzen.com/osm/buildings/15/16593/11278.json) of "buildings" layer:
![screenshot from 2015-06-18 16 49 18](https://cloud.githubusercontent.com/assets/146023/8234097/3da30692-15da-11e5-87e0-e3c859f66e93.png)
and a [geojson](http://vector.mapzen.com/osm/roads/15/16593/11278.json) of the same tile for "roads":
![screenshot from 2015-06-18 16 48 41](https://cloud.githubusercontent.com/assets/146023/8234106/46bb2818-15da-11e5-953f-d1c5564fb6b8.png)

"Roads" seems to be clipped without any buffer, which then ends with some rendering artefacts, see for example:
![screenshot from 2015-06-18 16 53 07](https://cloud.githubusercontent.com/assets/146023/8234168/8bf38c36-15da-11e5-8944-17ae69e057b2.png)

Seems to me that we should keep a buffer, and let consumers of the tile clip it themselves when needed.

**Comment by nvkelso** [comment]
Suggest adding an end cap as a work around.

**Comment by yohanboniface** [comment]
> Suggest adding an end cap as a work around.

I'm already using `line-cap: square;`, or do you mean something else?

**Comment by nvkelso** [comment]
Using this issue to explore adding buffered MVT tile variant.

**Comment by nvkelso** [comment]
Looks like we should setup a per layer config so buffer is configurable per geom type.

**Comment by rmarianski** [comment]
Per layer? Or per format?

**Comment by nvkelso** [comment]
The per layer buffering config would only be executed for the special buffered-MVT format. What are we calling that `MVB` or `MVTB`?

**Comment by nvkelso** [comment]
Try everything at: 

- `8`

If that has problems with labels, try something like?

- earth & water layer points: `256`
- place layer points: `128`
- other layer points: `64`
- lines: `8`
- polygons: `8`

See also: https://www.mapbox.com/vector-tiles/mapbox-streets-v7/#layer-reference

**Comment by nvkelso** [comment]
@yohanboniface we have buffered MVT format tiles up on `dev`, can you take a look please?

**Comment by yohanboniface** [comment]
I'm using http://utilery.readthedocs.org/en/latest/ since then :/

**Comment by nvkelso** [comment]
@rmarianski Do we still have buffered MVT format on dev? If so, we should set it back to clipped for this week's dev deploy in prep of clipped only for our final prod deploy for v1.0

**Comment by rmarianski** [comment]
I did enable it, but upon reviewing the code, it's surprising to me that it worked the way I thought it would in the first place? I opened up a [pr](https://github.com/tilezen/tilequeue/pull/111) that should correct it.

**Comment by nvkelso** [comment]
@rmarianski For the production build: where is the MVTB format disabled, a chef config that overrides https://github.com/tilezen/tilequeue/pull/111/files#diff-27316bd4a5c05ab0317c1f9d6440afd3R115?

**Comment by nvkelso** [comment]
If further work is needed here, we'll create a new issue in a new milestone.
