### ISSUE TITLE
NY boundary issue on dev

### ISSUE THREAD

**Issue by zerebubuth** [tilezen/vector-datasource#1063]
The **976-fractional-pois** test is failing on dev because the New York boundary isn't present in the output. However, it is present in the dev database, and appears to have the right properties and min zoom. It isn't clear why the boundary code is failing to cut this with the New Jersey boundary.

The test passes fine locally and on CI, so is possibly something to do with having a full database of data rather than the cherry-picked data for the tests.

See #1061 for the original issue.

**Comment by nvkelso** [comment]
I still see region boundaries from OSM, and I still see Hoopa reservation boundary.
