### ISSUE TITLE
NE Admin-1 boundaries missing from processed shapefiles

### ISSUE THREAD

**Issue by zerebubuth** [tilezen/vector-datasource#1064]
The **992-boundaries-min_zoom-and-name** test is failing because there are no `Admin-1 boundary items` in the `ne_50m_admin_1_states_provinces_lines` table in the dev database. There are none in the shapefile downloaded from S3 [as part of the installation process](https://github.com/tilezen/vector-datasource/wiki/Mapzen-Vector-Tile-Service#load-additional-data-and-update-database), so perhaps this indicates a shapefile processing error?

The shapefile fixture is okay, and the tests pass locally and on CI.

**Comment by rmarianski** [comment]
I checked the [original upstream](http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/50m/cultural/ne_50m_admin_1_states_provinces_lines.zip) shape file, and it too doesn't contain any `Admin-1 boundary` items, all are `1st Order Admin Lines`.

**Comment by nvkelso** [comment]
This is my mistake in
https://github.com/tilezen/vector-datasource/pull/1037/files#diff-dca2f4be5bc54303506aa7848a476050L32

We should add that one selector back to the remaining region filter.

_n

**Comment by nvkelso** [comment]
WFM
