### ISSUE TITLE
Grace Cathedral min_zoom is funky

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1084]
This could be related to partial POIs layer database migration?

* **What did you see?** Grace Cathedral in SF has a min_zoom of 16 with an area of 4078, while a neighboring place_of_worship First Church of Christ Scientist with area of 1501 has a min_zoom of 14.41. Grace Cathedral is also a local landmark, while the other church is not.
* **What did you expect to see?** Grace Cathedral should have at least as good as min_zoom as the other church (if not show up earlier).
* **What map location are you having problems with?** SF, 16/37.7911/-122.4120
* **Screenshot?** 

<img width="476" alt="screen shot 2016-09-22 at 10 11 54" src="https://cloud.githubusercontent.com/assets/853051/18758464/0fe4cdbe-80ad-11e6-82e0-b20ac4f13891.png">
<img width="317" alt="screen shot 2016-09-22 at 10 11 48" src="https://cloud.githubusercontent.com/assets/853051/18758462/0fdda264-80ad-11e6-9b19-4210fa847f7c.png">
<img width="760" alt="screen shot 2016-09-22 at 10 11 33" src="https://cloud.githubusercontent.com/assets/853051/18758463/0fdfd322-80ad-11e6-98e0-682e256b6a6a.png">

**Comment by zerebubuth** [comment]
Yup. Both have an area <5,000 and so should have `min_zoom: 16`. The lower `min_zoom` on the other church is incorrect, perhaps due to a partial / failed migration.

**Comment by nvkelso** [comment]
Both churches now have the same `min_zoom`, database migration seems to have worked this time! 

But some of the min_zoom values seem like they need work still. I suspect areas from landuse polygons should be counted differently than areas from buildings for place_of_worship, and garden zooms seem off. I've filed https://github.com/tilezen/vector-datasource/issues/1085 to track those in future release.
