### ISSUE TITLE
serving performance tips

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [tilezen/vector-datasource#1088]
Hi guys, I'd like to ask you for some tips related to tile serving. I was able to setup Mapzen Vector Tile Service, it works, but serving speed is not the best. 

For example when i call a path `/boundaries,landuse,roads,water/14/16146/10258.json` it takes 10 secs on my server, but if test same on https://vector.mapzen.com it is as fast as 300 ms.

I was checking [performance tuning docs](https://switch2osm.org/loading-osm-data/) but they don't make a difference.

My VM specs are not that bad, 64 GB RAM and:

```bash
$ lscpu 
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
CPU(s):                56
Vendor ID:             GenuineIntel
Model name:            Intel(R) Xeon(R) CPU E5-2683 v3 @ 2.00GHz
CPU MHz:               1999.960

$ sudo lshw -C disk
       description: SCSI Disk
       bus info: scsi@2:0.0.0
       logical name: /dev/sda
       size: 1280GiB (1374GB)
```
Any help is much appreciated :)

**Comment by rmarianski** [comment]
Right, processing times tend to be zoom level dependent, and the kinds of times you see are what I would expect.

What we do in production is pre-generate lots of tiles, and serve as much as possible from the cache. In this case, we store the tile with all the layers in it, and the only processing that we do to it is to fetch that generated tile, and strip out the layers that weren't requested.

For production use cases, I'd suggest trying the same kind of approach, namely to generate the tiles you expect to serve in advance and populate a cache with its contents. It's not documented, but we use the [tilequeue](https://github.com/tilezen/tilequeue) repo for this.

**Comment by ktrzeciaknubisa** [comment]
Thanks Robert. 

I have the tilequeue installed (it is mentioned in [Install Python dependencies](https://github.com/tilezen/vector-datasource/wiki/Mapzen-Vector-Tile-Service#install-python-dependencies) anyway).

But what does it mean since it does not use cache on my server? Does it require some extra configuration for cache usage?

**Comment by nvkelso** [comment]
You should be able to change the store setting to `directory` instead of
`s3`:

https://github.com/tilezen/tilequeue/blob/master/config.yaml.sample#L6

**Comment by rmarianski** [comment]
Yes, what @nvkelso mentioned in the sample config will allow you to store tiles locally on the filesystem, and read from a queue that is just a file. You can run the `seed` command to populate the list initially. I recommend getting started with this too.

We have queue and store interfaces (to read the tiles to process and where to store them once generated), so if you need to populate a different type of cache it should be possible to add if you were willing to go down that route. We use aws, with sqs as the queue and s3 as the store so implementations exist for that.

**Comment by ktrzeciaknubisa** [comment]
Thank you guys, seems working for mem queue and directory store (btw. why do you prefer sqs over mem? is it because RAM capacity may not be sufficient? What are the mem requirements: if I have 64 GB should I worry?)

Requesting cached tile time drops down to 2 sec (well https://vector.mapzen.com is still faster :)

And so I was trying to set up 3 as the store to compare with directory store, however I wasn't able due to:

```bash
  File "/.../Mapzen/env/local/lib/python2.7/site-packages/boto/auth.py", line 941, in get_auth_handler
    'Check your credentials' % (len(names), str(names)))
boto.exception.NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV1Handler'] Check your credentials
```

I'm sure I did provide valid `aws_access_key_id` and `aws_secret_access_key`, but something tells me it may not be enough. I have other apps (written for [node.js](https://nodejs.org)) where I use [s3](https://github.com/andrewrk/node-s3-client) module and so there I need to provide additional `region` param (e.g. region = "us-west-2") otherwise access key/secret access key would not suffice.

**Comment by rmarianski** [comment]
We use sqs for scaling reasons: we have multiple worker instances pulling messages and generating tiles.

Yes, what you mention about region is most likely an issue, and would probably need to be added to the code. When we run in production we use `iam` `role`s to grant access, but it might still be the case that us-east is assumed somewhere. Feel free to submit a pr/issue for this.

**Comment by ktrzeciaknubisa** [comment]
Issue submitted. You also mentioned before:

> You can run the seed command to populate the list initially. 

I wanted to ask how exactly do can I run this command, but it looks like I found the answer in https://github.com/tilezen/vector-datasource/issues/968#issuecomment-241040388

Thanks guys :)
