### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by zerebubuth** [tilezen/vector-datasource#1090]
In most layers we merge, where possible, features having the same `kind` and other properties. However, the `kind` is quite detailed, having separate values for `battlefield`, `common`, `farmland`, `forest`, `garden`, `park`, etc... This means that opportunities at low zooms for merging are small, and often individual `kind` features don't meet our area restrictions.

We could add a `kind_category` which captured the "greenness" of the above `kind`s, and allowed us to drop `kind` at low zooms and merge on `kind_category`. Although this would mean a loss of detail, it would mean keeping the "presence" of the polygon and its effect on the texture of the map.

**Comment by nvkelso** [comment]
We've refactored landuse kind remapping and general zoom visibility substantially in v1.7 milestone.
