### ISSUE TITLE
Re-evaluate area/volume properties on merged buildings

### ISSUE THREAD

**Issue by rmarianski** [tilezen/vector-datasource#1095]
- **What did you see?**

On merged buildings, the area/volume is calculated from all features that got merged together. Although we assign a `scale_rank`, it can be surprising when trying to use it for area/volume filtering in tangram styles.
- **What did you expect to see?**

Perhaps we should consider dropping the area/volume properties on merged features? We should also consider if we want to do this everywhere we merge, like for the `landuse` layer.
The original motivation was to cut down on tile sizes by returning fewer features back. We could also try merging features that actually intersect somewhere, but this would probably complicate processing as well as result in larger tile sizes.
- **What map location are you having problems with?** _City and country are helpful, as well as tile coordinates or latitude / longitude._

For example:

/buildings/14/4827/6157.json
OSM id [281343104](http://www.openstreetmap.org/way/281343104) gets merged in.

**Comment by nvkelso** [comment]
We fixed this in v1.6
