### ISSUE TITLE
For health care POIs rename  speciality > kind_detail

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1098]
We modified a transform in https://github.com/tilezen/vector-datasource/pull/1097 for healthcare `speciality`, but just like restaurant cuisine and sport on pitches, we should generalize this as `kind_detail`. 

This is a bug fix over v1.0.0 tiles.

**Comment by zerebubuth** [comment]
`speciality` is a list, and we don't have any other `kind_detail` which are lists. Perhaps taking the first entry of `speciality`? Or sorting them and taking the first alphabetically, for consistency?

**Comment by nvkelso** [comment]
I think the first is good, that way it could be more data driven. And if we develop opinions about sorting it later we could do that.

I like what we did with the shields where we have a singular and a list version of the property, should we do that here? So kind_detail and all_kind_detail?

**Comment by zerebubuth** [comment]
Given it's just this one-off tag at the moment, does it make sense to keep the list in `speciality` and the first item in `kind_detail`. That has the benefit of being an _additional_ tag, so plays nice with our semver promises too.

With the shields, there's a generally well-accepted ranking of importance of roads. Annoyingly, it's not consistent from country to country, so it means writing down a bunch of different rules for different places.

For healthcare specialities, I'm not sure how one could rank one over another. We could potentially rank them based on a snapshot of their current popularity. For example, in [taginfo today](http://taginfo.openstreetmap.org/keys/healthcare:speciality#values), `psychiatry` has 205 uses, `neurology` has 125, so we should rank `psychiatry;neurology` as `psychiatry` first? Although that runs into problems when we have `general` ranked first, and something like `general;internal` - would it be more useful to rank the more specific (`internal`) speciality first? (Aside: how can `general` even be a `speciality`?)

It probably doesn't matter too much - we can pick the first and redefine the sort order later if we think it could be improved. Or use a spreadsheet for it, if the ordering isn't amenable to computation.

**Comment by nvkelso** [comment]
This is undocumented so we can do in v1.2 release.
