### ISSUE TITLE
Topojson encoding issue

### ISSUE THREAD

**Issue by rmarianski** [tilezen/vector-datasource#1100]
- **What did you see?**

Features in the topojson layer don't seem to be encoded properly.
- **What did you expect to see?**

Same features as in geojson and mvt layers.
- **What map location are you having problems with?** _City and country are helpful, as well as tile coordinates or latitude / longitude._  

https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fcdn.rawgit.com%2Ftangrams%2Ftangram-sandbox%2F1d60a85ed384150d8a98c26fa30f5a4123c1224f%2Fstyles%2Fdefault.yaml#12.7582/37.3086/-120.8965
- **Screenshot?** _Props for animated gifs._

![screenshot](https://cloud.githubusercontent.com/assets/53770/19090684/7c71997c-8a4d-11e6-92e5-85655e0682f4.png)

**Comment by zerebubuth** [comment]
Tile location is `12/672/1589`. At one zoom level out (z11), it's possible to see similar artefacts on the river in to the left (in `11/335/794`). This looks like simplification gone wrong, but that's just my initial guess.

**Comment by rmarianski** [comment]
The other formats, geojson and mvt, look fine.

**Comment by rmarianski** [comment]
This looks to have been fixed by https://github.com/tilezen/vector-datasource/issues/1145 too (which was created by me as a dupe of this, sorry).
(When checking the tangram play link, update the source to use tiles v1.0)
