### ISSUE TITLE
How to add a custom layer

### ISSUE THREAD

**Issue by musicformellons** [tilezen/vector-datasource#1101]
I am trying to add a custom layer of geometry points. I have a Geojson file with geometry points in it which I add to the Postgis 'osm' database using ogr2ogr as a 'customlayer' table. 

```
osm=# \d+ customlayer
                                                         Table "public.customlayer"
    Column    |         Type         |                           Modifiers                           | Storage  | Stats target | Description 
--------------+----------------------+---------------------------------------------------------------+----------+--------------+-------------
 ogc_fid      | integer              | not null default nextval('customlayer_ogc_fid_seq'::regclass) | plain    |              | 
 wkb_geometry | geometry(Point,4326) |                                                               | main     |              | 
 url          | character varying    |                                                               | extended |              | 
 image        | character varying    |                                                               | extended |              | 
 city         | character varying    |                                                               | extended |              | 
Indexes:
    "customlayer_pkey" PRIMARY KEY, btree (ogc_fid)
    "customlayer_geom_idx" gist (wkb_geometry)
Has OIDs: no
```

I added the 'customlayer' layer to queries.yaml but I am kind of lost how to proceed. I do need to add a customlayer.jinja2 template as this is causing an error (jinja2.exceptions.TemplateNotFound). Do I also need to add a customlayer.yaml file?

The points should be visible at all zooms (0 to 21). Any directions how to proceed (migrations needed y/n?) are much appreciated.

**Comment by rmarianski** [comment]
Most likely just need a jinja2 template where you specify what you would query, with the name configured in the queries.yaml file. The __id__ and __geometry__ properties are important and expected to be in the results. In the other layers, the yaml is used to generate sql functions that the jinja templates use. If you don't need or want to generate those, then the yaml is not needed. In the queries.yaml file, you can also define subsequent transforms to run on the results, but this is optional too.

**Comment by musicformellons** [comment]
My customlayer.jinja2:
```
SELECT
    ogc_fid AS __id__,
    wkb_geometry AS __geometry__

FROM customlayer
```

When running server and making request I get:
```
shapely.geos.ReadingError
ReadingError: Could not create geometry because of errors while reading input.

Traceback (most recent call last)
File "/root/tileserver/tileserver/__init__.py", line 195, in __call__
response = self.handle_request(request)
File "/root/tileserver/tileserver/__init__.py", line 298, in handle_request
[], [], self.buffer_cfg)
File "/root/env/lib/python2.7/site-packages/tilequeue/process.py", line 358, in process_coord
feature_layers, extra_data = _preprocess_data(feature_layers)
File "/root/env/lib/python2.7/site-packages/tilequeue/process.py", line 63, in _preprocess_data
shape = loads(wkb)
File "/root/env/lib/python2.7/site-packages/shapely/wkb.py", line 16, in loads
return reader.read(data)
File "/root/env/lib/python2.7/site-packages/shapely/geos.py", line 361, in read
raise ReadingError("Could not create geometry because of errors "
ReadingError: Could not create geometry because of errors while reading input.
```

**Comment by musicformellons** [comment]
Changed the customlayer.jinja2 into:
```
SELECT
    ogc_fid AS __id__,
    {% filter geometry %}wkb_geometry{% endfilter %} AS __geometry__

FROM customlayer

```

And errors are gone. Not yet really clear if geometry points of customlayer are coming through. I do get:
`{"type": "FeatureCollection", "features": []}` in the browser on this url: http://0.0.0.0:18080/customlayer/16/19293/24641.json

On zoom 0-14 I get: `Not Found`

Will see if I can 'find' points...

**Comment by rmarianski** [comment]
> On zoom 0-14 I get: Not Found

Are you using valid tile coordinate urls? There's a simple validity check initially to see if the coordinate is valid before proceeding.

> I tested but the custom points do not get through. Any idea?

We have code that [filters out geometries](https://github.com/tilezen/tilequeue/blob/78834523eed6595ce47af0c020aa610784e8e9d2/tilequeue/transform.py#L126-L132) that lie outside the tile's bounding box, which is format specific in case the format expects data to be buffered. Even further upstream though, [features that don't intersect in the bounding box](https://github.com/tilezen/tilequeue/blob/78834523eed6595ce47af0c020aa610784e8e9d2/tilequeue/process.py#L78-L84) get dropped too.

If you find a tile coordinate that should contain any custom points, I would expect it to start appearing.

**Comment by musicformellons** [comment]
Mmh, I show the points in the map as geojson-source and these show up, then I can lookup the requested tiles in the server terminal and request the 'original url', but they do not contain any 'custom points', so I am pretty sure they do not 'come through' somehow. I am pretty much stuck now.

**Comment by musicformellons** [comment]
Ah, I understand your remark regarding zoom 0-14 better now. I was thinking of having coordinates and zoom in the url, but these are really tilenumbers and zoom. So actually zoom 0-14 'does work', i.e. for example `http://0.0.0.0:18080/customlayer/1/1/0.json `returns: `{"type": "FeatureCollection", "features": []}`. So now my problem restricted to: no features at all zooms.

**Comment by musicformellons** [comment]
`http://0.0.0.0:18080/customlayer/1/1/1.json` returns:
`{"type": "FeatureCollection", "features": []}`
 
However,
`http://0.0.0.0:18080/all/1/1/1.json `
returns among other layers also all the custom points except with coordinates of 0:
`..... "id": 106}}]}, "customlayer": {"type": "FeatureCollection", "features": [{"geometry": {"type": "Point", "coordinates": [0.0, -0.0]}, "type": "Feature", "properties": {}, "id": 14555}, {"geometry": {"type": "Point", "coordinates": [0.0, -0.0]}, "type": "Feature", "properties": {}, "id": 13787}, {"geometry": {"type": "Point", "coordinates": [0.0, -0.0]}, "type": "Feature", "properties": {}, "id": 13788}, {"geometry": {"type": "Point", "coordinates": [0.0, -0.0]}, "type": "Feature", "properties": {}, "id": 13789}, {"geometry": {"type": "Point", "coordinates": [0.0, -0.0]}, "type": "Feature", "properties": {}, "id": 13790}, {"geometry": {"type": "Point", "coordinates": [0.0, -0.0]}, "type": "Feature", "properties": {}, "id": 13791}, {"geometry":.....`

**Comment by musicformellons** [comment]
Serious progress! Points (for both all and for just customlayer) show on map closely around coordinates lat 0 and long 0.

E.g. `http://0.0.0.0:18080/all/17/65535/65535.json` returns:
`"customlayer": {"type": "FeatureCollection", "features": [{"geometry": {"type": "Point", "coordinates": [-0.00066433, 0.00036555]}, "type": "Feature", "properties": {}, "id": 11432}, {"geometry": {"type": "Point", "coordinates": [-0.00103285, 0.00032351]}, "type": "Feature", "properties": {}, "id": 36699}, {"geometry": {"type": "Point", "coordinates": [-0.00066402, 0.00036565]}, "type": "Feature", "properties": {}, "id": 10828}, {"geometry": {"type": "Point", "coordinates": [-0.00066371, 0.00036697]}, "type": "Feature", "properties": {}, "id": 10829}, {"geometry": {"type": "Point", "coordinates": [-0.0006645, 0.00036557]},`

So one problem left now: the coordinates are somewhere scrambled into very low values.

**Comment by rmarianski** [comment]
Nice sleuthing! The code does expect that the geometries in the database are in mercator (3857 projection). Can you re-project the data on the way in?

**Comment by musicformellons** [comment]
That must be it! My coords are in WGS84. Will convert and reimport, that should do the trick.

A question relating to actual use and performance of this custom layer. As stated [here](https://github.com/tilezen/vector-datasource/issues/1092) the basic strategy for performance is trying to avoid rendering. This custom layer will be updated frequently, so how to go about that? Maybe just render this layer or something? Any ideas?

**Comment by zerebubuth** [comment]
The time taken to render a tile is due to the query from the database plus the post-processing we do in Python. The query time is generally related to the database size (plus complicating factors like index, index bloat, etc...). If you want to overlay your custom, frequently-updated layer on top of regular tiles then it might be worth considering rendering tiles containing _only_ your custom layer, and loading [multiple sources](https://mapzen.com/documentation/tangram/sources/) in Tangram, for example:

```yaml
sources:
  mapzen:
    type: MVT
    url: http://tile.dev.mapzen.com/vector/v1/all/{z}/{x}/{y}.mvt
    url_params: { api_key: XXX }
  customlayer:
    type: MVT
    url: http://my.tile.render.server/customlayer/{z}/{x}/{y}.mvt
```

Or equivalent for other client-side JS rendering libraries. This means you should get better performance when rendering your custom layer, as there's no need to keep all the base layer data in the database - it'll be smaller and more efficient.

Alternatively, if the are your custom data covers is small, you could pre-generate the base map layers and store them on disk so that only the custom layer was generated on-the-fly. Depending on how small the coverage is, that could be a very effective way to speed up access.

**Comment by musicformellons** [comment]
Makes sense, thanks!
