### ISSUE TITLE
Remove natural_forest and natural_wood from pois layer

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1103]
These should only be label placements in the landuse layer but are now appearing in the pois layer.

```
  # natural forests - note already clamped to z12
  - filter: {natural: forest}
    min_zoom: { min: [ { max: [ 12, { lit: zoom + 2 }, { lit: *tier2_min_zoom } ] }, 14 ] }
    output: { kind: natural_forest, tier: 2 }

  # natural woods - note already clampted to 12
  - filter: {natural: wood}
    min_zoom: { min: [ { max: [ 12, { lit: zoom + 2 }, { lit: *tier2_min_zoom } ] }, 14 ] }
    output: { kind: natural_wood, tier: 2 }
```

Example:
- http://tile.dev.mapzen.com/mapzen/vector/v1/all/14/8184/5448.topojson

```
{
type: "Point",
properties: {
kind: "natural_wood",
area: 2426,
source: "openstreetmap.org",
min_zoom: 14,
tier: 2,
id: -1756198,
osm_relation: true
},
coordinates: [
388,
933
]
},
```

<img width="394" alt="screen shot 2016-10-04 at 22 08 40" src="https://cloud.githubusercontent.com/assets/853051/19101687/286fcd9e-8a7f-11e6-8135-000d69863955.png">

Curious that we're even showing those without any names!

**Comment by nvkelso** [comment]
Possibly also `village_green`?

<img width="597" alt="screen shot 2016-10-04 at 22 41 54" src="https://cloud.githubusercontent.com/assets/853051/19102278/c9cb4f70-8a83-11e6-88a4-70ed4ec95e43.png">

**Comment by nvkelso** [comment]
I can find the 2nd example for **Mt. Cydonia Ponds Natural Area** label position but not the 3rd example in this test for **Liebesinsel**. Both were fresh generated tiles.

- https://github.com/tilezen/vector-datasource/pull/1205/files#diff-35adbc8f1a5e80a9c3e72c1ed1397caa

**Comment by zerebubuth** [comment]
I think this might have been because tileserver and tilequeue were using different date prefixes - I forgot to update the tileserver one after the dev build finished. It's looking okay for me now. Could you check that it's looking good for you too, please?

**Comment by nvkelso** [comment]
Verified :)
