### ISSUE TITLE
MultiLineString geometry issues in mapzen vector tiles

### ISSUE THREAD

**Issue by Kristonitas** [tilezen/vector-datasource#1104]
I'm trying to parse the data from mapzen vector tiles. I tried to look for similar issues to find a solution, but it didn't answer my questions, sorry if I missed something.

I'm trying to parse two specific tiles:
(left tile)
https://vector.mapzen.com/osm/roads/13/4259/2911.mvt
(right tile)
https://vector.mapzen.com/osm/roads/13/4260/2911.mvt
Same things can be seen in json data as well.

My goal is to try and parse similar (mapbox as well) tiles with C#, but for debugging, I'm using javascript plugins (pbf, vector-tile...).
- **What did you see?**

Feature, with OSM id of: 107613595 has 29 path segments in the left tile and 19 segments in the right tile. And the x/y coordinates vary by 2000 units in each tile, efectively "covering" half of the tile.
- **What did you expect to see?**

http://www.openstreetmap.org/way/107613595
It should be a small path with at most 17 **points**, and confined in a small corner area of both of these tiles. I'm well aware that viewing the same place with mapbox-gl (and loading mapzen tiles) works pretty good,  and most of the data seems to be correct, but some non-rendered paths can't be good as far as I can tell.

I've seen similar issues posted earlier, but they were mostly about multiple connected sub-paths, but what I'm seeing is a lot of strange data. In general, how should I go about interpreting **MultiLineStrings**? Can those multiple segments go not in a connected order?

At higher zoom levels this problem mostly goes away as there are almost no MultiLineStrings.

**Comment by nvkelso** [comment]
Sorry to hear you’re running into problems.

Can you retest against v1 vector tiles, please? We’re about to push those
live – they probably show the same problem but it would be helpful to
confirm.

(left tile)
https://tile.mapzen.com/mapzen/vector/v1/roads/13/4259/2911.mvt
(right tile)
https://tile.mapzen.com/mapzen/vector/v1/roads/13/4260/2911.mvt

**Comment by zerebubuth** [comment]
Hi!

Sorry for the confusion - I think what might be happening is that the road segments are being merged and the current production behaviour is to pick _one of_ the IDs to continue on the merged segment. I think this has been fixed in #952 which is part of the v1.0 release coming very soon (and which @nvkelso just mentioned).

I took those two tiles and highlighted the segments with `id=107613595` in red:

![image](https://cloud.githubusercontent.com/assets/271360/19315008/0eef061c-9094-11e6-9b7a-1b015992b3da.png)

As you can see, this includes a great many other features which don't originate with way 107613595. I think they have been merged with it because they are also unnamed paths with `sac_scale=hiking`.

**Comment by Kristonitas** [comment]
Thanks for the detailed feedback.

The v1 vector tiles seem to skip id's on merged paths (as expected) and there are less _merging_ going on at zoom level of 15. I only wonder now if a path can be merged on one tile and non-merged and with OSM id on the other tile.

I think I was expecting to always see references to OSM for all paths. I missed the #952 issue and it explained everything.

**Comment by Kristonitas** [comment]
Also, is there a high level description (or comments in source code) how the merging is determined for specific zoom levels. Those details would help me out a bit.

**Comment by nvkelso** [comment]
Yes, I think it's possible for that oddness to happen (where you have different results for different tiles). We're tracking making that more consistent in https://github.com/tilezen/vector-datasource/issues/1002 (but it'll give you _less_ ids than you currently see).

Road merging is triggered in the main `queries.yaml` file:

* https://github.com/tilezen/vector-datasource/blob/master/queries.yaml#L609-L613

Which happens after certain properties are dropped from the features in the same `queries.yaml` file:

* https://github.com/tilezen/vector-datasource/blob/master/queries.yaml#L487-L542

The line merging logic is in two places in `transform.py`:

* https://github.com/tilezen/vector-datasource/blob/master/vectordatasource/transform.py#L3042-L3065
* https://github.com/tilezen/vector-datasource/blob/master/vectordatasource/transform.py#L2882-L2938
