### ISSUE TITLE
extra water lines

### ISSUE THREAD

**Issue by meetar** [tilezen/vector-datasource#1107]
- **What did you see?**

Looks like some extraneous lines in the water from z0-at least z8:

<img width="433" alt="screen shot 2016-10-14 at 5 20 11 pm" src="https://cloud.githubusercontent.com/assets/459970/19403158/35524a26-9233-11e6-977c-1222bfa4278d.png">
<img width="1100" alt="screen shot 2016-10-14 at 5 20 33 pm" src="https://cloud.githubusercontent.com/assets/459970/19403164/3a1d6450-9233-11e6-80db-543f97539a8e.png">
<img width="656" alt="screen shot 2016-10-14 at 5 25 16 pm" src="https://cloud.githubusercontent.com/assets/459970/19403169/3c86450e-9233-11e6-908e-b283ffe5582b.png">

https://tangrams.github.io/explorer/#1.5/34.8027/202.9600/boundary/1
https://tangrams.github.io/explorer/#2.6/42.9921/-70.7558//
https://tangrams.github.io/explorer/#3.0/34.5247/-70.2246//
https://tangrams.github.io/explorer/#5.7/19.4649/-74.1362//
https://tangrams.github.io/explorer/#6.5/16.7795/-85.6620//
https://tangrams.github.io/explorer/#8.7/21.8779/-83.4401//

**Comment by nvkelso** [comment]
This is all but resolved (the northern horizontal line at first 2 zooms remains):

![image](https://user-images.githubusercontent.com/853051/52680786-9d707d80-2eee-11e9-80bd-95f89760b397.png)

![image](https://user-images.githubusercontent.com/853051/52680796-a95c3f80-2eee-11e9-885a-fdbf74d6fcfe.png)

**Comment by nvkelso** [comment]
Resolved in v1.7 via #1806.
