### ISSUE TITLE
No information about shapefiles.tar.gz

### ISSUE THREAD

**Issue by pnorman** [tilezen/vector-datasource#1112]
https://github.com/tilezen/vector-datasource/wiki/Mapzen-Vector-Tile-Service#load-additional-data-and-update-database has the file shapefiles.tar.gz downloaded, but I can't find any information on its contents, how it is generated, or the licenses involved.

**Comment by zerebubuth** [comment]
Sorry about that, it's a gap in our documentation. Until that gets fixed, the summary is: there's a couple of Makefiles generated by [`data/bootstrap.py`](https://github.com/tilezen/vector-datasource/blob/master/data/bootstrap.py) and the template called [`Makefile-prepare-data`](https://github.com/tilezen/vector-datasource/blob/master/data/Makefile-prepare-data.jinja2) downloads the data and reprojects it. The use of Makefiles here is probably, with hindsight, an unnecessary complication. The current list of data sources used to generate the Makefiles from the templates is in [`assets.yaml`](https://github.com/tilezen/vector-datasource/blob/master/data/assets.yaml), and the licenses are:

* For the data from [openstreetmapdata](http://www.openstreetmapdata.com), [ODbL](http://opendatacommons.org/licenses/odbl/1-0/).
* For the data from [naturalearthdata.com](http://www.naturalearthdata.com/), [public domain](http://www.naturalearthdata.com/about/terms-of-use/).

**Comment by nvkelso** [comment]
I've updated the wiki docs in https://github.com/tilezen/vector-datasource/wiki/Mapzen-Vector-Tile-Service/a52c94aa27190773f59360b3b9b207c45a99a01c. Thanks @pnorman!
