### ISSUE TITLE
Organize queries by table

### ISSUE THREAD

**Issue by rmarianski** [tilezen/vector-datasource#1130]
To reduce load on the database, the queries should be oriented around the tables that they query instead of by layer. The python code can then take care of grouping the results by layer.

This should greatly reduce the number of queries issued the the database. Currently, each layer queries a series of tables and unions them together. Most (all?) of the time, the filter is done on a `min_zoom` value in the table that is set on update. It should be possible to convert the union of the results across all tables into a single filter that simply `or`s the `min_zoom` clauses together.

This also implies that we may no longer need to maintain the jinja queries themselves. These queries might be able to become yaml configuration where each layer has a corresponding min_zoom column, and possibly a few other options. This might not actually be possible though, as there are some differences in terms of whether intersections are done on the geometry, and there's a special boundaries intersection done at query time too, but maybe some yaml configuration can capture this. There is also some logic that exists in the queries wrt which layer receives the `name` value for labeling purposed, but this should be moved to python. 

This should be done once #1129 is complete.

**Comment by nvkelso** [comment]
This work was completed in Fall 2017.

**Comment by nvkelso** [comment]
Related PR: https://github.com/tilezen/vector-datasource/pull/1352.
