### ISSUE TITLE
Additional maritime boundary cleanup

### ISSUE THREAD

**Issue by stepps00** [tilezen/vector-datasource#1133]
Following up on: https://github.com/tilezen/vector-datasource/issues/294

Opening this issue to track any undesirable maritime boundaries that still exist in our house styles.

**Comment by stepps00** [comment]
Example:

<img width="979" alt="screen shot 2016-11-21 at 3 30 39 pm" src="https://cloud.githubusercontent.com/assets/18567700/20505065/8a8234b8-afff-11e6-960b-5784e4698ebe.png">

**9/28.2838/34.7580**

**Comment by stepps00** [comment]
Example:

<img width="687" alt="screen shot 2016-11-21 at 3 37 32 pm" src="https://cloud.githubusercontent.com/assets/18567700/20505249/7ae61442-b000-11e6-9c04-cf49f6b85415.png">


**9.78542/-15.9314/-191.9598**

**Comment by nvkelso** [comment]
Not a priority, closing.
