### ISSUE TITLE
Add religion to kind_detail

### ISSUE THREAD

**Issue by sensescape** [tilezen/vector-datasource#1134]
Right now we show [religion](https://taginfo.openstreetmap.org/keys/religion?filter=all#values) as it's own tag. Instead that should be stored in `kind_detail` to be consistent with sport and cuisine. See https://github.com/tilezen/vector-datasource/issues/1127.

`christian` leads with 680,000 instances, down to `taoist` with 1876 and then `bahai` with 124. There are a few that have less than 100 that aren't listed here.

```
christian
muslim
buddhist
hindu
shinto
jewish
taoist
sikh
multifaith
voodoo
unitarian_universalist
jain
spiritualist
bahai
```

**Comment by nvkelso** [comment]
This was done in the last few releases.
