### ISSUE TITLE
License of documentation

### ISSUE THREAD

**Issue by pnorman** [tilezen/vector-datasource#1136]
Is the MIT license being used for the documentation as well?

What is the license for the cartography in the schema that the docs describe? There is currently no license, and in this situation some companies take this to be all rights reserved. i.e. license for the tilezen schema vs license for the text describing the schema.

**Comment by nvkelso** [comment]
Looks like we use a mix of CC-BY (probably the right choice) and MIT in Mapzen docs now. I'll confer with the docs team and add special docs license file here.

**Comment by nvkelso** [comment]
(This should probably also be done for Joerd and Cartography docs.)

**Comment by nvkelso** [comment]
@pnorman Can you clarify this one: `What is the license for the cartography in the schema that the docs describe?` 

* Do you mean the screenshot images used in the documentation, or 
* Mapzen house styles like Bubble Wrap?

**Comment by nvkelso** [comment]
* The license for the tilezen schema is under **MIT** (the general project license that already exists)
* The license for the text "docs" describing the schema... is also "open" but needs to be declared.

**Comment by nvkelso** [comment]
Related PR: #1137.

**Comment by pnorman** [comment]
> @pnorman Can you clarify this one: What is the license for the cartography in the schema that the docs describe?
> 
> Do you mean the screenshot images used in the documentation, or
> Mapzen house styles like Bubble Wrap?

Neither - the schema has cartographic decisions, and although not everyone believes these can be protected by copyright or other IP, some companies do. An example is the choice to have a layer which has roads of class motorway, trunk, primary at z8, secondary starting at z10, motorway_link, tertiary at z11, etc.

I'm not claiming those choices are or are not protected, but there's a certain amount of caution these days.

**Comment by nvkelso** [comment]
Both the Tilezen tile schema aka data model (covered under the general MIT license in this `vector-datasource` repo already) and the Mapzen cartographic styling are open source (e.g. [Bubble Wrap MIT license](https://github.com/tangrams/bubble-wrap/blob/gh-pages/LICENSE)).

**Comment by nvkelso** [comment]
To clarify about the _names_ used for forks of the software stack and Mapzen cartographic styles: 

- If it's the same (no modifications), then use the original project name.
- If you've modified it, and want to refer to it by a name:
  - Choose a different project name than the original project name
  - It's okay to say "based on X" or "fork of X"
