### ISSUE TITLE
Empty string `name` fields in ocean

### ISSUE THREAD

**Issue by bcamper** [tilezen/vector-datasource#1139]
* **What did you see?**

Ocean features without a `name` seem to be including an empty string value.

https://tile.mapzen.com/mapzen/vector/v1/all/15/5236/12655.topojson

```
area: 3004978176
id: 4126
kind: "ocean"
min_zoom: 0
name: ""
sort_rank: 200
source: "openstreetmapdata.com"
```

* **What did you expect to see?**

If a feature doesn't have a `name` value, I expect the `name` property to be dropped from the feature entirely.

* **What map location are you having problems with?**

See tile URL above.

**Comment by nvkelso** [comment]
I think this is a regression over v0.10 tiles.

**Comment by nvkelso** [comment]
@rmarianski Is this an issue any more after your RAWR tile refactoring?

**Comment by rmarianski** [comment]
This should be fixed as part of it.

**Comment by nvkelso** [comment]
k, will hold off closing until we get a dev build to verify.

**Comment by nvkelso** [comment]
Fixed during Fall 2017 RAWR Tile sprint.
