### ISSUE TITLE
Consider always simplifying before clipping

### ISSUE THREAD

**Issue by rmarianski** [tilezen/vector-datasource#1144]
For certain layers, we simplify before clipping. This helps ensure that the points on tile boundaries stay on there. But, to prevent simplifying a huge geometry before clipping, we first clip using a buffered bounding box, of 10%, but that was arbitrarily chosen. Then we simplify this, and clip again with the actual bounding box.

We should consider using this approach whenever we simplify to reduce rendering artifacts. The down side I can think of is that it's a little bit more expensive to simplify this way across the board. But given that we already do it for water, earth, and boundaries, which tend to contain the largest geometries anyway, I don't expect this to add that much more overhead.

**Comment by rmarianski** [comment]
@bcamper found an example of this in the `landuse` layer.

**Comment by nvkelso** [comment]
Process changed.
