### ISSUE TITLE
Remember queue source when reading messages

### ISSUE THREAD

**Issue by rmarianski** [tilezen/vector-datasource#1146]
For messages that get enqueued in the custom top priority queue, the current behavior is try to acknowledge them in a different queue based on its zoom level, which fails.

Instead of calculating the queue on acknowledgement, it should get threaded through the pipeline.

**Comment by rmarianski** [comment]
Not sure why I created this issue in vector-datasource. The tilequeue repo would have been more appropriate.

**Comment by nvkelso** [comment]
This issue was moved to tilezen/tilequeue#134
