### ISSUE TITLE
water boundary lines from OSM are missing

### ISSUE THREAD

**Issue by kkowalsky** [tilezen/vector-datasource#1153]
* Waterlines [boundary = true] aren't showing up in a smooth line (more like random dots) at zooms 9 and higher. 
* Should continue to be a line, like other areas around the world 
* Eastern coast of Italy, near Ancona or Pescara

![waterlines](https://cloud.githubusercontent.com/assets/4246770/21911468/bf7a1330-d8d5-11e6-9dd7-b68d802cc22f.gif)

**Comment by nvkelso** [comment]
Duplicate of #735.
