### ISSUE TITLE
Move legacy jinja SQL to layer YAMLs

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1154]
We'd like to redo how our Postgres queries work, but theres a lot of cruft in the jinja SQL that could be moved to the YAML files to make the problems more obvious.

See also:

- https://github.com/tilezen/vector-datasource/issues/1129
- https://github.com/tilezen/vector-datasource/issues/1130
- https://github.com/tilezen/tilequeue/issues/141

**Comment by lygstate** [comment]
Are this compilicated?

**Comment by zerebubuth** [comment]
Perhaps! It's hard to say without doing it. The best I can offer is that I don't think it will be very complicated, but the existing queries are quite _complex_, so the process of translating parts of the query into YAML might be difficult at times.

**Comment by lygstate** [comment]
@zerebubuth What's the diffencies between mapbox tileserver vs tangram tileserver?
https://github.com/pka/t-rex are for mapbox mvt generating, does that also suite for tilzen? 
Maybe would introduce some performance benefit.

**Comment by zerebubuth** [comment]
I'm not entirely sure what all the differences are between Mapbox's tile serving stack and Tilezen's. The most obvious would be that theirs is written mainly in NodeJS and ours in Python, which makes further comparison more complicated!

As I pointed out in #1174, T-rex looks interesting but doesn't do all the things we'd need for it to be a drop-in replacement for Tilezen's tileserver. We currently support GeoJSON and TopoJSON formats in addition to MVT format, and a set of complicated cartographic transforms which (as far as I'm aware) aren't implemented anywhere else.

There's nothing special there which couldn't be implemented elsewhere, but Tilezen's stack has grown over the course of a few years to support the special features we wanted in `vector-datasource`. Other people have implemented different sets of things to support the features that they wanted. So there are lots of different tile serving stacks, many of which share some subset of features (such as MVT serving) but not others. It unfortunately also means that the components of most stacks are not interchangeable, drop-in replacements for each other.

This means that you need to figure out which features are important for your application, and then make a decision about which technology stack is closest to your needs.

**Comment by ImreSamu** [comment]
@lygstate 
> What's the diffencies between mapbox tileserver vs tangram tileserver?

check the http://www.paulnorman.ca/blog/2016/11/serving-vector-tiles/  _"Serving Vector Tiles  ... Which should I use?  ..."_

**Comment by pnorman** [comment]
> We'd like to redo how our Postgres queries work, but theres a lot of cruft in the jinja SQL that could be moved to the YAML files to make the problems more obvious.

If I'm understanding this right, there's two ways layers are specified, jinja SQL and YAML files, and this is converting from one to the other?

**Comment by nvkelso** [comment]
Yes, this issue tracks migrating logic that is still in the "legacy" jinja SQL files to the more generic (and newer) YAML config files.

Background: The YAML is parsed and ends up as SQL as a intermediate step now and gives us more flexibility in terms of relying less on Postgres as it can be a bottleneck. 

We expect that much of the legacy jinja SQL can be migrated, but some will be hard and will stay in the jinja files. The net result of this issue should leave us with _some_ content still in the jinja – and that content will require different followup work.

**Comment by nvkelso** [comment]
99% of this was completed by @rmarianski last year. Closing.
