### ISSUE TITLE
extra lines in ocean polygons z0-z7

### ISSUE THREAD

**Issue by meetar** [tilezen/vector-datasource#1162]
* **What did you see?**

<img width="1131" alt="screen shot 2017-02-06 at 10 08 36 am" src="https://cloud.githubusercontent.com/assets/459970/22652393/475a3816-ec54-11e6-9dc7-85be59bcfcb2.png">

* **What did you expect to see?**

Something more like:

<img width="1131" alt="screen shot 2017-02-06 at 10 08 36 am" src="https://cloud.githubusercontent.com/assets/459970/22652449/80426022-ec54-11e6-963f-dea0226ba70e.png">

This occurs apparently randomly throughout the world from zoom 0 through at least 7.

Sample scene: https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fgist.githubusercontent.com%2Fanonymous%2F1877931d427f1ddd459f8cd48e7cdc04%2Fraw%2Fad1a0a10895a963b04355d42255cc9ef6cca33db%2Fscene.yaml#2.84/-17.93/174.97

**Comment by nvkelso** [comment]
This is a dup of your #1107.

**Comment by meetar** [comment]
Ah ha, there's where I left it... thanks!
