### ISSUE TITLE
Add shorelines to boundaries?

### ISSUE THREAD

**Issue by meetar** [tilezen/vector-datasource#1163]
Can we offer a layer (or modify an existing layer) including shorelines in administrative boundaries, to make drawing political maps easier? For instance, there doesn't seem to be a way to easily draw a map of the US States based on the OSM data… but it seems as though there should be. (Is there?)

https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fgist.githubusercontent.com%2Fanonymous%2F1c249c1803a263f9492bf599652f7269%2Fraw%2Fb29b7f65c039be295b2506176176e2b4fb5760d5%2Fscene.yaml#4.230/43.366/-99.104

<img width="992" alt="screen shot 2017-02-06 at 10 34 37 am" src="https://cloud.githubusercontent.com/assets/459970/22653591/e539cee0-ec57-11e6-8a78-0cbb0509fa17.png">

**Comment by nvkelso** [comment]
The existing basemap on the `vector` endpoint is intended for reference mapping (not thematic mapping). There are plans to add more thematic mapping polygons (e.g. using Who's On First), but on a different endpoint and a different repo than this one.
