### ISSUE TITLE
transform_feature_layers_shape() takes exactly 6 arguments (7 given)

### ISSUE THREAD

**Issue by leyenda** [tilezen/vector-datasource#1168]
Hello, I've followed the installation instructions, but when testing the tile server at `http://localhost:8080/buildings/16/19293/24641.json`, I got this error:
```
<!--
Traceback (most recent call last):
  File "/home/isaga/tileserver/tileserver/__init__.py", line 204, in __call__
    response = self.handle_request(request)
  File "/home/isaga/tileserver/tileserver/__init__.py", line 310, in handle_request
    json_data_all, layer_data, coord, format, self.buffer_cfg)
  File "/home/isaga/tileserver/tileserver/__init__.py", line 163, in reformat_selected_layers
    coord, meters_per_pixel_dim, buffer_cfg)
TypeError: transform_feature_layers_shape() takes exactly 6 arguments (7 given)
-->
```
When testing this other URL `http://localhost:8080/all/16/19293/24641.json`  I got a correct JSON  object response.

**Comment by nvkelso** [comment]
@leyenda Can you confirm which versions of `vector-datasource`, `tilequeue`, and `tileserver` you have installed? It's probably a miss-match between them.

**Comment by leyenda** [comment]
Thank you for your reply. You are right, I may have forgotten to change the branch on tileServer and tilequeue. I  am going to start from 0 using Ubuntu 14.04.5 x64 and reply with my results.

**Comment by nvkelso** [comment]
It's best to use the latest release, and reference the tags for the dependent releases:

- https://github.com/tilezen/vector-datasource/releases/tag/v1.1.0

Eg:

- **Requires:** [tileserver v1.3.0](https://github.com/mapzen/tileserver/releases/tag/v1.3.0) and [tilequeue v1.4.0](https://github.com/mapzen/tilequeue/releases/tag/v1.4.0) and [mapbox-vector-tile v1.0.0](https://pypi.python.org/pypi/mapbox-vector-tile/v1.0.0).
