### ISSUE TITLE
Roads with bicycle=designated are missing that property

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1171]
From the Bike Map launch for Walkabout ([blog post](https://mapzen.com/blog/bike-map/)) a user [noticed](https://twitter.com/ustroetz/status/839903089872224256) that roads with bicycle=designated tags aren't showing up as blue on the map. It turns out we have config error in our roads filter logic:

Currently we only export `bicycle=*` on footways, but that should be for any road layer feature (so ~~move~~ **copy** it up a couple lines up to the highways section):

- **Needs change:** https://github.com/tilezen/vector-datasource/blob/master/yaml/roads.yaml#L79

The post-processing operation correctly anticipates the bicycle tag when setting the `is_bicycle_related` boolean, but the data isn't there on most roads because of the bug in the roads.yaml (above).

- **No change:** https://github.com/tilezen/vector-datasource/blob/master/vectordatasource/transform.py#L3577

**Comment by nvkelso** [comment]
This should also expose `bicycle=no` properties as a no-op for motorways and the like that don't allow bikes.

**Comment by bhousel** [comment]
Awesome Bike Map!  

Someone I work with just noticed that `bicycle=dismount` is also being ignored, so there are a bunch of segments styled white that should be off limits.

For example, these pedestrian ways around UPenn:  https://www.openstreetmap.org/way/335523313

**Comment by nvkelso** [comment]
@bhousel Thanks for the report. The `bicycle=dismount` data already existed on paths, not showing it in the map was a style problem so I moved your comment over to https://github.com/tangrams/walkabout-style/issues/152, which is now fixed (but needs a prod deploy to go live).

**Comment by nvkelso** [comment]
(The `is_bicycle_related` logic mentioned above may also need to change for consistency, but for the styling we're good to go.)

**Comment by bhousel** [comment]
Thanks for the quick fix @nvkelso! 👍

**Comment by nvkelso** [comment]
Hmm, I see this property added on the test way in Eureka, California...

But the way in Germany mentioned via Twitter still lacks the `bicycle:designated` tag?

http://www.openstreetmap.org/way/4613300#map=17/52.52742/13.41253

**Comment by nvkelso** [comment]
Verified :) I see that way in Germany now, and a ton more in places like Portland and Berkeley!

<img width="837" alt="screen shot 2017-04-19 at 23 32 20" src="https://cloud.githubusercontent.com/assets/853051/25216676/8ab7c9e2-2558-11e7-8fba-4336d76a63b2.png">
