### ISSUE TITLE
Use https://github.com/omniscale/imposm3 to speed up the planet import speed.

### ISSUE THREAD

**Issue by lygstate** [tilezen/vector-datasource#1173]
Currently the speed of osm2pgsql are very slow, how about using imposm3 to improve the performance of it?

**Comment by zerebubuth** [comment]
Imposm3 is not a drop-in replacement for osm2pgsql. While both bits of software are very capable, and probably either could be used, it might take a lot of work to switch from one to the other.

Planet import is something that should be done very rarely, and kept up to date by applying diffs. If you need to run something on your local machine, or are testing the software setup in advance of a full deploy, then I would strongly recommend starting with a smaller extract. For example, Mapzen provide [Metro extracts](https://mapzen.com/data/metro-extracts/) for small metropolitan areas and [Geofabrik downloads](http://download.geofabrik.de/) provide extracts of larger state and national areas too. 

If you use these smaller extracts for testing software and setup, then you only need to do a full planet load once. I think we've averaged about one every 6 months over the past couple of years.

**Comment by nvkelso** [comment]
As Matt summarized, we view the slower import more as a one-time cost that is acceptable (plus using imposm3 would require many other changes) and are focused on improving tile render speed in other parts of the stack. Closing this issue for now.
