### ISSUE TITLE
Using https://github.com/pka/t-rex for tile generating.

### ISSUE THREAD

**Issue by lygstate** [tilezen/vector-datasource#1174]
* **What did you see?**
* **What did you expect to see?**
* **What map location are you having problems with?** _City and country are helpful, as well as tile coordinates or latitude / longitude._  
* **Screenshot?** _Props for animated gifs._

**Comment by zerebubuth** [comment]
T-rex looks like a great bit of software. Unfortunately, it's not a drop-in replacement for `tileserver` and `tilequeue` and, while it does many of the same processing functions, it doesn't have the same set that we depend upon for our `vector-datasource`.

It would be possible to extend t-rex to do these things, and I'll be watching the project with interest. But, at the moment, it would be a huge amount of work to switch and we would lose a lot of our current functionality.
