### ISSUE TITLE
Project cycling route ref onto roads and paths

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1175]
After we published the new Mapzen Bike Map ([blog post](https://mapzen.com/blog/bike-map/)) we received feedback it would be nice to see special ref shields on the colored bike features.

- **What did you see?** Many cycling roads are grouped into relations which have `ref` values, but no `ref` value on the way. The cycleway's `ref` is useful for way finding in both in cities and for longer distance touring between cities.
- **What did you expect to see?** I expect to see the cycle relation's `ref` value on the way as a new property (similar to what we do for the road shields, there should be a set of singular and plural cycleway network and cycleway shield text properties added)
- **What map location are you having problems with?** 
  - https://www.openstreetmap.org/way/417389551 and it's relation:
    - https://www.openstreetmap.org/relation/32310
    - 16/37.7526/-122.4192

This issue is similar to https://github.com/tilezen/vector-datasource/issues/775 and they can probably be done at the same time.

**Comment by nvkelso** [comment]
Hmm, I'm only rarely seeing this on roads in San Francisco that _do_ have cycle relations, including https://www.openstreetmap.org/way/417389551 which is in the test. Bad dev build?

Oddly I **do** see the right tags on https://www.openstreetmap.org/way/397097600 just a few blocks away.

**Comment by zerebubuth** [comment]
Hmmm... very strange. I just took a look and got a feature with properties:

```json
{
  "kind": "major_road",
  "name": "Valencia St.",
  "sort_rank": 379,
  "kind_detail": "secondary",
  "oneway": "no",
  "is_bicycle_related": true,
  "bicycle_shield_text": "45",
  "cycleway": "lane",
  "source": "openstreetmap.org",
  "min_zoom": 10,
  "landuse_kind": "retail",
  "all_bicycle_shield_texts": [
    "45"
  ],
  "all_bicycle_networks": [
    "lcn"
  ],
  "id": 417389551,
  "bicycle_network": "lcn"
}
```

Which does include the information. But the tile last modified says `Thu, 13 Apr 2017 18:42:03 GMT`. So that's weird. I can't really explain that unless you got a different version of the tile from me, but I'm not sure how that would be the case...

We'll need to rebuild dev anyway because of changes in #1213. Let's check whether this is still an issue after that's all done.

**Comment by nvkelso** [comment]
Verified, looks great!

We could consider dropping the `all_*` shield and networks for bicycle, bus, walking at zooms 11 and 12 (versus current zoom 10 max in https://github.com/tilezen/vector-datasource/blob/master/queries.yaml#L507-L608) as well as a later optimization. If that turns out to be useful I can file a followup issue. 

<img width="402" alt="screen shot 2017-04-19 at 22 13 04" src="https://cloud.githubusercontent.com/assets/853051/25214797/5534691a-254e-11e7-87b1-6ac70a5ef419.png">

<img width="801" alt="screen shot 2017-04-19 at 22 12 52" src="https://cloud.githubusercontent.com/assets/853051/25214796/55326bec-254e-11e7-984d-ce68869753f1.png">
