### ISSUE TITLE
Bring piers in earlier

### ISSUE THREAD

**Issue by meetar** [tilezen/vector-datasource#1178]
The buildings on these piers show up before the piers do:

https://tangrams.github.io/explorer/#15.2/32.7165/-117.1731/kind/pier

Can we bring piers in at zoom 13, to see those features earlier? (Possibly by giving piers the same area thresholds as buildings?)

**Comment by jschleuss** [comment]
+1

Our sister publication in San Diego would like them to show up earlier. Contact me if you have questions.

**Comment by nvkelso** [comment]
Hi Jon :)

Can you confirm you want the pier landuse layer polygons earlier, not the
pier lines in the roads layer?

Looks like those are toggled by area right now, we could look into moving
them into a different zoom tier. Do they want the labels to show up earlier
for some of these, too? (Is the label more important or same importance as
the polygon?)

Are there any other attributes on the piers that tells us one is more
important than another? Like something to indicate the cruise ship terminal
is more “interesting” than say a industrial pier?

**Comment by jschleuss** [comment]
Yessir!

We're looking for the pier landuse to show up earlier. It looks like the largest piers show up first (maybe at z13) and then more at z14 and z15. Labels of the piers aren't important to us at the present moment. 

This is all for our mapmaker, so don't let us rule the conversation. But some folks in San Diego said it's a little weird to have a map of Downtown SD and not see those piers. I've updated our YAML file https://github.com/datadesk/web-map-maker/issues/59

I can't see anything that would make some piers more important than others. It didn't even occur to me until they mentioned it. LA's piers are puny by comparison. Thanks for looking into this!

![piers](https://cloud.githubusercontent.com/assets/695934/24023735/8d3f2e42-0a6b-11e7-83b2-63089b0a041a.gif)

**Comment by nvkelso** [comment]
Great GIF, thanks for the explanation. I agree they should show earlier,
will take some weeks to get a fix out.

**Comment by zerebubuth** [comment]
Which zoom level should these be visible until? The smallest of the main piers in the GIF are:

* [Broadway Pier](http://www.openstreetmap.org/way/275609725#map=11/32.7217/-117.1836), which has area 17,855 and currently ends up with a `min_zoom` of 15. Should that be 11 instead?
* The unnamed [pier at the end of West G Street](http://www.openstreetmap.org/way/275609722#map=11/32.7362/-117.1458) has area 4,734 and also currently a `min_zoom` of 15. Should that also be 11, or would such a small polygon be almost invisible at that zoom?

**Comment by nvkelso** [comment]
I suspect something like:

- zoom 11 for **Cruise Terminal** with area `53,276`
  http://www.openstreetmap.org/way/275609726
- zoom 12 for **Broadway Pier** with area `17,856`
  http://www.openstreetmap.org/way/275609725
- zoom 12 for **unnamed pier** with area `4,734`
  http://www.openstreetmap.org/way/275609722

Looking at the existing landuse tiers:

- https://github.com/tilezen/vector-datasource/blob/master/yaml/landuse.yaml#L5-L56

None of the existing tiers seem to match well. Seems more like a sq meters > pixel threshold more like earth layer?

**Comment by zerebubuth** [comment]
Follow up in #1206 for the breaking changes we might want to make in v2.0.

Looks like I should proceed with a raw size-based zoom (+1.81). Before I do, it's worth checking; that value would make [this pier](http://www.openstreetmap.org/way/377915546#map=11/25.1618/121.3824), which is the largest I could find that really looks like a pier, visible at zoom 8. Is that what we want, or should we cap it at zoom 11?

**Comment by nvkelso** [comment]
Cap at 11.

**Comment by nvkelso** [comment]
👍Verified
