### ISSUE TITLE
Require that most POIs have names

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1186]
* **What did you see?**

Gardens without names are appearing in Scotland as POIs.

* **What did you expect to see?**

The landuse layer can have unnamed polygons, but POIs should _generally_ only include named features.

* **What map location are you having problems with?** 

- http://tile.mapzen.com/mapzen/vector/v1/all/12/2011/1276.topojson
- http://www.openstreetmap.org/way/273274870
- https://github.com/tilezen/vector-datasource/blob/master/yaml/pois.yaml#L441-L444

Currently the Mapzen basemap styles have logic to insist on names for most features, except the following kinds:

- https://github.com/tangrams/walkabout-style/blob/gh-pages/walkabout-style.yaml#L4298-L4413
- https://github.com/tangrams/walkabout-style/blob/gh-pages/layers/bike-interlay.yaml#L249-L276

Namely:

Namely it disabled all POIs from displaying if they don't have a name, **unless**:

## No name okay at any zoom:

_The pois.yaml filter already clamps to sane min_zoom value._

- [ ] attraction
- [ ] bbq
- [ ] beacon
- [ ] bicycle_junction
- [ ] bicycle_parking
- [ ] bicycle_repair_station
- [ ] boat_storage
- [ ] communications_tower
- [ ] cross
- [ ] dam
- [ ] drinking_water
- [ ] dune
- [ ] egress
- [ ] fee_station ??? not sure about this one, did we change the kind name before v1?
- [ ] fire_lookout ??? not sure about this one, did we change the kind name before v1?
- [ ] firepit
- [ ] fishing_area
- [ ] gate
- [ ] geyser
- [ ] hazard
- [ ] horse ??? not sure about this one, did we change the kind name before v1?
- [ ] hot_spring
- [ ] information
- [ ] landmark - has a area logic, too
- [ ] life_ring
- [ ] lifeguard_tower
- [ ] observatory
- [ ] parking
- [ ] petroleum_well
- [ ] picnic_site
- [ ] picnic_table
- [ ] pitch
- [ ] playground
- [ ] power_pole
- [ ] power_tower
- [ ] put_in
- [ ] put_in_egress
- [ ] pylon
- [ ] ranger_station
- [ ] rapid
- [ ] rest_area (this is a very early min_zoom 11)
- [ ] rock
- [ ] saddle
- [ ] shower
- [ ] silo ??? not sure about this one, did we change the kind name before v1?
- [ ] sinkhole
- [ ] slipway
- [ ] spring
- [ ] stone
- [ ] swimming_area
- [ ] toilets
- [ ] traffic_signals
- [ ] trailhead
- [ ] tree
- [ ] walking_junction
- [ ] waste_disposal
- [ ] water_point
- [ ] water_tower
- [ ] water_well
- [ ] watering_place
- [ ] windmill

## Special circumstances

- [ ] **allotments**  (combo area) / zoom 17
    - this should get a POI feature, not just a LANDUSE label creation
    - https://github.com/tilezen/vector-datasource/blob/master/yaml/landuse.yaml#L475-L478
- [ ] **garden** (combo with access)
    - this is the one that had a bad min_zoom filter (setting everything to 12!?)
    - NOTE: This was in the general list above, but moved here after comments in https://github.com/tilezen/vector-datasource/issues/1186#issuecomment-290392298.

**Comment by nvkelso** [comment]
This is a followup for #1185 and an optimization for Mapzen basemap styles.

**Comment by zerebubuth** [comment]
Should we additionally filter out everything which doesn't have a name and `access` is either `private` or `no`? That thins the gardens out quite a lot in Edinburgh - see this [overpass query](http://overpass-turbo.eu/s/nUq).

I think we can use the name as a proxy for importance, and the access restriction as a measure of public utility. Which would mean unnamed, private things are probably unimportant and inaccessible, making them likely to be Points of No Interest :wink:

**Comment by rmarianski** [comment]
> Points of No Interest

PONI` :horse:

**Comment by nvkelso** [comment]
@zerebubuth Sounds good :) I've updated the main issue description.

**Comment by zerebubuth** [comment]
Should we add `kind: mast` to the list of things which are allowed to not have a name? Seems like most masts would go unnamed.

**Comment by zerebubuth** [comment]
Also `kind: cycle_barrier`.

**Comment by nvkelso** [comment]
Yes, good additions!

**Comment by nvkelso** [comment]
I'm still seeing many unnamed gardens in the example [zoom 12 tile](http://tile.mapzen.com/mapzen/vector/v1/all/12/2011/1276.topojson), a bad database migration for `min_zoom`?

**Comment by nvkelso** [comment]
✅ Will you look at that tiny tile! Verified tile contents as well.

<img width="504" alt="screen shot 2017-04-19 at 22 57 14" src="https://cloud.githubusercontent.com/assets/853051/25215679/ea0e25bc-2553-11e7-8e52-70f7dcccfbb2.png">

**Comment by nvkelso** [comment]
Actually, some widespread funky is going on here _(look for the small grey box icons):_

- Some of these _should_ be included, but are missing their `kind`
- Many of them _should not_ be included at all, though (they aren't in the white list).

They all don't have names in OSM.

<img width="617" alt="screen shot 2017-04-19 at 23 12 58" src="https://cloud.githubusercontent.com/assets/853051/25216097/cd3b22f8-2555-11e7-863c-bc54acac2cf3.png">

**15/37.7567/-122.4270 in San Francisco**

- http://tile.dev.mapzen.com/mapzen/vector/v1/all/15/5240/12666.topojson

In the **pois** layer I'm seeing many features without `kind`:
`{"type":"Point","properties":{"source":"openstreetmap.org","min_zoom":14.79,"id":79457493,"area":1957}`

That one is a `graveyard`, as we can see in the **landuse** layer:

`{"type":"Polygon","properties":{"source":"openstreetmap.org","kind":"grave_yard","area":1957,"sort_rank":11,"min_zoom":14.79,"id":79457493},"arcs":[[1890]]},`

There are several more of these just in that one tile, and most tiles have them.

**16/37.7692/-122.4908 in San Francisco Golden Gate Park**

Here's one in a different tile that is also missing a `kind` key and value (but was in the white list and should be included in the tile, and is):

https://www.openstreetmap.org/node=2724417498

**Comment by nvkelso** [comment]
We should probably also add a note in the **pois** layer documentation that most POIs require a name, but some don't.

**Comment by nvkelso** [comment]
**Eek! In Switzerland 10/46.8963/8.1079**

Lots of landuse=forest (and other?) unnamed POIs creeping in...

`{"type":"Point","properties":{"source":"openstreetmap.org","min_zoom":10.0,"id":-2841814,"osm_relation":true,"area":4138680},"coordinates":[1168,1127]},`

- https://www.openstreetmap.org/relation=2841814

<img width="745" alt="screen shot 2017-04-19 at 23 58 52" src="https://cloud.githubusercontent.com/assets/853051/25217570/46ece3d8-255c-11e7-849b-09df66a5fcf2.png">

**Comment by nvkelso** [comment]
Another 3 in SF:

- **Railway station:** https://www.openstreetmap.org/way/313763513
- **Military area:** https://www.openstreetmap.org/way/44018545
- **Beach:** https://www.openstreetmap.org/relation/2165533

<img width="539" alt="screen shot 2017-04-20 at 00 09 12" src="https://cloud.githubusercontent.com/assets/853051/25217991/f7344924-255d-11e7-9dbd-b9035c17c87b.png">

**Comment by nvkelso** [comment]
Finally found another **pois** feature where this `traffic_signal` is legitimately in the whitelist of no-name-okay features that is correctly included in the dev tile, but missing `kind` (and thus Bubble Wrap would fail to draw those icons):

- https://www.openstreetmap.org/node/65361720

**Comment by nvkelso** [comment]
It's worth noting that many no-name-okay features like picnic areas, toilets, etc are correctly getting their kind and showing up in tiles.

<img width="608" alt="screen shot 2017-04-20 at 00 20 00" src="https://cloud.githubusercontent.com/assets/853051/25218270/1f68649c-255f-11e7-827e-c569e9df60b1.png">

**Comment by nvkelso** [comment]
Surprised to see these `level_crossing` features at 14/37.7568/-122.4657:

We _should_ have included them as no-name-okay, but they're not in that list, but still showing up in dev tiles, but missing their `kind`:

- https://www.openstreetmap.org/node/4608620475

(Really they should be `min_zoom: 18` – they'd still show up in zoom 15 tiles if someone wanted to show them early, but only useful for nav when you're coming up on one.)

<img width="758" alt="screen shot 2017-04-20 at 00 22 24" src="https://cloud.githubusercontent.com/assets/853051/25218409/9a93e056-255f-11e7-8f98-5ae5f5e3859f.png">

**Comment by zerebubuth** [comment]
Yup! It looks like I forgot to run the migration _again_. I'll retry that now.

**Comment by nvkelso** [comment]
This is looking pretty good now :)

But in doing the QA pass I found a few more that should be whitelisted (and a couple that shouldn't) – otherwise there is regressions for features like `traffic_signals` which should always show up regardless of name. 

Follow-up is in https://github.com/tilezen/vector-datasource/issues/1218.
