### ISSUE TITLE
Improve road/line merging

### ISSUE THREAD

**Issue by bcamper** [tilezen/vector-datasource#1191]
We currently merge certain features, such as roads, by shared properties. This can create large MultiLineString geometries, which reduces property duplication and client-side processing time for feature-filtering. However, there are two ways these merged features can be substantially improved:

1. Many (in some cases a large %) of the individual LineStrings within those MultiLineString are often **contiguous** (e.g. the last coordinate on one LineString is the same as the first coordinate of the next LineString), and could be further coalesced into a smaller number of LineStrings, eliminating data duplication (repeating coordinates) and reducing client-side time for line processing (avoid per-LineString setup/overhead).

2. Within these LineStrings, there are often unnecessary extra vertices that are **collinear** (even after the secondary merge step above) -- such as individual nodes at intersections on a long road. These can be removed to further reduce the vertex count and improve client-side geometry build and render time.

I ran some client-side post-processing tests to gauge the impact, but I think it makes most sense to do this once server-side, as an extension of the existing merge transforms. In this example, two additional transforms were applied to the data:

- For each MultiLineString, the constituent LineStrings were iterated in order, and fused where the last/first coordinates matched.
- Then, the coordinates of each resulting LineString were iterated, and intermediate collinear points (according to a configurable tolerance) were removed (so this is a more narrow form of simplification).

In these images, red dots show each road vertex (only minor roads are shown). For the initial (un-modified) tile data, it takes **144,378** polygons to render these roads. After the additional merging steps, the # of polygons was reduced to **80,414** -- a **44% reduction**. (In this example there are a couple places where the geometry is slightly altered, but with proper tolerance tweaking it should be possible to do these transforms with no visual changes.)

Here is the before/after:
![dissolve-roads](https://cloud.githubusercontent.com/assets/16733/24681602/f629a3c2-1963-11e7-9450-8ddc4c227442.gif)

Additionally, this merging can improve **label placement** by creating longer individual LineStrings upon which more labels can fit.

**Comment by nvkelso** [comment]
Great GIF!

**Comment by zerebubuth** [comment]
This is already done server side in the [`merge_line_features`](https://github.com/tilezen/vector-datasource/blob/master/vectordatasource/transform.py#L3055) post-processor. However,

1. The line merging code might not be doing what we expect, so we should add extra tests around that.
2. The lines might not be mergeable in the post-processor, but become mergeable (i.e: meet at the same start/end point) once their coordinates are quantized in the tile formatting step. If this is the case, we may want to move coordinate quantization into the post-processing pipeline explicitly. However, I could see that stirring up all kinds of new issues.

At a guess, I'd say the simplification is just not working because it can't simplify across several LineStrings in a MultiLineString, so hopefully we fix the root issue and that gets fixed too.

**Comment by bcamper** [comment]
Update in case it's helpful for debugging: I had been running the client-side merging **after** scaling coordinates to an internal tile scale of 4096 units (similar to default MVT), which fit your theory that there might be a merge issue depending on quantization level. However, I tried moving it to earlier in the process, and found (more or less) the same level of MultiLineString merging even when applied to initial lat/lng coords (I expected it to not merge as many). In fact, I actually got the *best* merge rate with pure GeoJSON tiles.

In any case, there still could be a server-side issue with merging before vs. after simplification to the tile scale, but I thought this was interesting nonetheless.

**Comment by nvkelso** [comment]
@bcamper Can you verify this one, please?

**Comment by nvkelso** [comment]
If this is working but there is additional enhancement to be had let's do a separate followup issue for the next milestone.

**Comment by bcamper** [comment]
I am working on getting stats. The TLDR is I see a modest improvement, but still much below what I think is possible (and would like to see! :)  But, I don't see an obvious problem with the current behavior, so no need for it to block a current release.

**Comment by zerebubuth** [comment]
I looked into this a bit more and it looks like the line merging routine we are using doesn't cope with "ambiguous" merges, such as those at 4-way junctions. We might end up having to replace that with something of our own.

**Comment by bcamper** [comment]
Here's what I've found (using the new debug stats in https://github.com/tangrams/tangram/pull/544) for a high-complexity NYC view at z12 (#12/40.68636570811375/-73.94691467285234):

*Note: line geometry counts here are the number of **GL triangles** Tangram had to build to render the features (lines decomposed into triangles, etc.), not the number of features in the source data - but for line features, they should scale linearly together.*

**Tangram master / prod tiles**
- Total line geometries: 258,232
- roads 222,512
  - highways 23,810
  - major roads 39,304
  - minor roads **148,756**
  - railways 7,812

**Tangram master / dev tiles**
- Total line geometries: 226,079 **(-13% from prod)**
- roads 190,294
  - highways 17,884
  - major roads 21,056
  - minor roads **144,110**
  - railways 4,556

**Tangram merge-multilines / dev tiles**
- This branch does additional client-side line merging + simplification
- Total line geometries: 156,359 **(additional -30% from dev tiles, -39% from current prod)**
- roads 121,198
  - highways 15,212
  - major roads 20,374
  - minor roads **80,086**
  - railways 3,168

**Summary**
It looks like the dev tiles are effectively reducing the numbers of highways, major roads, and railways (these are just the top sub-layers), but aren't really affecting the number of *minor roads* (only 148k -> 144k in this view) - which are the vast majority at this zoom. 

For reference, the client-side code I'm using is [here](https://github.com/tangrams/tangram/blob/5bb881d29a56e8eab59ed173cec294d87b424b40/src/sources/data_source.js#L106-L191) (sorry, it's a bit more complex than it needs to be due to some premature optimization to avoid reallocating/copying LineStrings that never need to be modified). It has two steps:

1. `mergeContiguousMultiLineString()`: iterates through the LineStrings in a MultiLineString, and merges any LineStrings where the last and first coordinates are equal (iterates in their natural order, so only helps if contiguous segments also happen to be sequential in the feature data!).
2. `mergeColinearLineString()`: after the above step, iterates through all the coordinates of the merged LineStrings, and *removes* any coordinates that are within a certain angle tolerance of the line's current direction (measured via the dot product of normalized vectors). This is a more narrow form of simplification to only remove near-colinear coordinates (I also tried running a generic simplification step on the geometry, before trying something more specific to the desired outcome here). 

This technique works particularly well for grid systems with lots of straight streets, so this NYC example may be one of the cases of best-realized gains.

**Comment by zerebubuth** [comment]
Cool, thanks!

Do you know how much of the 30% saving over dev tiles is due to `mergeContiguousMultiLineString()` and how much due to `mergeColinearLineString()`? If the problem is what I found before (the lack of merging at 4-way junctions) then I'd expect the `mergeColinearLineString()` pass to be much less effective on minor roads than the `mergeContiguousMultiLineString()` pass.

**Comment by nvkelso** [comment]
This looks good to take to prod, and we'll followup for the minor roads in https://github.com/tilezen/vector-datasource/issues/1227 in the next release.

**Comment by bcamper** [comment]
Will follow up with comments on new issue
