### ISSUE TITLE
Project bus route operators and refs to roads

### ISSUE THREAD

**Issue by zerebubuth** [tilezen/vector-datasource#1194]
Following on from https://github.com/tilezen/vector-datasource/pull/1193#discussion_r110241258, we should project bus route relation information down to the roads. However, instead of `network`, we should use `operator`.

**Comment by zerebubuth** [comment]
TODO: find example.

**Comment by nvkelso** [comment]
Example:

This way has cycle, bus, and driving networks!

- https://www.openstreetmap.org/way/417097119
- 23 (bus), 50 (bicycle), and 35 (driving)
- `bus_network`: `San Francisco Municipal Railway` (from operator)

**Comment by nvkelso** [comment]
The bus refs are taken care of in https://github.com/tilezen/vector-datasource/pull/1193.

**Comment by nvkelso** [comment]
Released in v1.3
