### ISSUE TITLE
Stop using tags-> in YAML

### ISSUE THREAD

**Issue by zerebubuth** [tilezen/vector-datasource#1199]
Since we moved to the hstore schema, everything is in the tags column and the  `tags->` prefix is unnecessary. We've got a mix of different uses in the YAML files, but it could be confusing for any new contributors whether `tags->` is required or not (just to be clear: it's not).

This should just be a `sed 's/tags->//'` on the YAML files, but it's possible that it might throw up some unexpected regressions.

**Comment by nvkelso** [comment]
Amen!

**Comment by nvkelso** [comment]
@zerebubuth @rmarianski Does your RAWR tile refactor address this issue as process changed?

**Comment by rmarianski** [comment]
I think it's a good idea to fit into the rawr tiles work.

**Comment by nvkelso** [comment]
There are still a few of these hanging out. Deferring to next milestone.

**Comment by nvkelso** [comment]
Fixed by https://github.com/tilezen/vector-datasource/pull/1771.

**Comment by nvkelso** [comment]
QA verified.
