### ISSUE TITLE
Bug/Typo in pois.yaml

### ISSUE THREAD

**Issue by paulmach** [tilezen/vector-datasource#1208]
* **What did you see?**
lines [1135-6](https://github.com/tilezen/vector-datasource/blob/master/yaml/pois.yaml#L1135) in `yaml/pois.yaml` are:
```
output:
  kind: {col: tourism, tier: 6}
```

* **What did you expect to see?**
I expected to see `output: { kind: { col: tourism}, tier: 6}`  which is what makes sense and found other places like [line 211](https://github.com/tilezen/vector-datasource/blob/master/yaml/pois.yaml#L211)

* **What map location are you having problems with?** _City and country are helpful, as well as tile coordinates or latitude / longitude._  

NA

* **Screenshot?** _Props for animated gifs._

NA

**Comment by nvkelso** [comment]
More legible code is always good, thanks for the fix :)

**Comment by nvkelso** [comment]
Verified in dev.
