### ISSUE TITLE
Drop zoom 11 and 12 all_* bicycle, walking, bus shield text and networks

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1214]
This is an optimization for work performed in https://github.com/tilezen/vector-datasource/issues/1175 and https://github.com/tilezen/vector-datasource/issues/775. In those issues we additional properties on **roads** layer features for bicycle, walking, and bus network and shield text. But on the map there's often not any room to show these extra shields, plus Tangram can't render them quite yet ;)

We could consider dropping the all_* shield and networks for bicycle, bus, walking at zooms 11 and 12 (versus current zoom 10 max in https://github.com/tilezen/vector-datasource/blob/master/queries.yaml#L507-L608) to improve road merging, regardless of road kind.

**Comment by zerebubuth** [comment]
Looks like this was done in #1198, so should be sent to staging.

**Comment by nvkelso** [comment]
Verified on dev.
