### ISSUE TITLE
Road shield code doesn't correctly handle UTF-8

### ISSUE THREAD

**Issue by zerebubuth** [tilezen/vector-datasource#1215]
The road shield extraction code uses regular expressions to extract parts of the `ref` tag to use as `shield_text`. However, the regular expression code (`re` module) appears to treat `str` as ASCII, even if the `re.UNICODE` flag is passed. I think that means we must convert all strings to `unicode` before using it?

**Comment by nvkelso** [comment]
@zerebubuth is this ready to test on `dev`?

**Comment by zerebubuth** [comment]
Yes, I think so. I only deployed it later on in the build, but since the problem would have prevented affected tiles from being rendered, then I think they should all be good from now onwards.

**Comment by nvkelso** [comment]
This test passes, and I see a shield on the line in **dev** which means this is no longer a build blockers. 

Note: I see `77К-012` as the ref in the data, but `77K` in our shield_text which is slightly inconsistent but isn't a show blocker.
