### ISSUE TITLE
landuse_kind not always present on buildings

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1226]
* **What did you see?**
Reported via support, the buildings at LAX Airport in Los Angeles _mostly_ have the expected `landuse_kind` properties, but not always, and even the same building can include or not include the property at different zooms.

* **What did you expect to see?**
All buildings on the airport landuse polygon should get `landuse_kind` consistently.

* **What map location are you having problems with?** 
- http://tangrams.github.io/bubble-wrap/#14/33.9412/-118.4190

* **Screenshot?** 

zoom 14 has the main international terminal without, while terminal 2 includes it:

<img width="827" alt="screen shot 2017-04-26 at 20 44 03" src="https://cloud.githubusercontent.com/assets/853051/25467174/781d827c-2ac1-11e7-86dc-28cb62c9de69.png">
<img width="941" alt="screen shot 2017-04-26 at 20 43 40" src="https://cloud.githubusercontent.com/assets/853051/25467175/781ea79c-2ac1-11e7-8dca-0bc1d03b895c.png">

While zoom 14 didn't include the property, now zoom 16 does on nearby United building:
<img width="759" alt="screen shot 2017-04-26 at 20 44 12" src="https://cloud.githubusercontent.com/assets/853051/25467173/780ca2b8-2ac1-11e7-9342-f78324215156.png">

**Comment by nvkelso** [comment]
We think this is because the centroid for the building is calculated on a larger clip than the landuse polygon. They both need to be based on the same clip.

**Comment by zerebubuth** [comment]
Not the centroid, but the landuse polygon must [overlap at least 80% of the building area](https://github.com/tilezen/vector-datasource/blob/b7bd4036967d81c1451a57dbdf5af8a6fbf60293/vectordatasource/transform.py#L1073). The effect is the same, though.

**Comment by nvkelso** [comment]
Also affects `building` features especially in relations, here in New York city (red has it, grey doesn't):

- https://www.openstreetmap.org/way/137564642#map=17/40.75345/-73.97684

<img width="818" alt="screen shot 2017-05-16 at 5 29 33 pm" src="https://cloud.githubusercontent.com/assets/853051/26138194/25b6f2fa-3a7c-11e7-9168-a3b3cb58b7d5.png">

/cc @sensescape

**Comment by nvkelso** [comment]
Related: https://github.com/tilezen/vector-datasource/issues/1142 Should we clip buildings completely to tile boundaries?

**Comment by nvkelso** [comment]
Subtask of https://github.com/tilezen/vector-datasource/issues/1348.

**Comment by nvkelso** [comment]
This looks to be the root cause of https://github.com/tangrams/tangram-es/issues/1653 building flicker z-fighting in Cinnabar on ES (also kinda observable on JS).

**Comment by nvkelso** [comment]
Discussion from today's Tile sync meeting:

- Related [StackOverlow question](https://stackoverflow.com/questions/46231640/mapzen-buildings-polygons-are-clipped-when-draw-on-map/46242999?noredirect=1#comment79512167_46242999)
- To make the intercut 99% accurate instead of 95% we’d need to buffer 3x3 landuse and buildings.
- Do we do the 3x3 for all layers, for all zooms? Probably not as early work around that made zooms 8 and 12 buffering landuse was very slow…
- This could all go away if we refactor how we calculate the intercut with RAWR tiles

Deferring action on this issue until after basic RAWR tiles are in production.

**Comment by nvkelso** [comment]
Looks like building_part features (https://github.com/tilezen/vector-datasource/issues/1226#issuecomment-301980388) still aren't getting the landuse_kind correctly, but the airport examples are so "good enough", with followup in new issue.

**Comment by nvkelso** [comment]
Verified on prod, filed new issue #1495 for building_part .followup
