### ISSUE TITLE
surface property missing at mid-zooms

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1252]
Looks like surface is in the drop properties list twice (oops):

- zoom 11: https://github.com/tilezen/vector-datasource/blob/e324c7d3406895c065aa40bd5de5d66be491d720/queries.yaml#L517
- zoom 14: https://github.com/tilezen/vector-datasource/blob/e324c7d3406895c065aa40bd5de5d66be491d720/queries.yaml#L557

The second instance in zoom 14 is likely an error.

By the time unclassified and some tracks are visible at zoom 11 in https://github.com/tilezen/vector-datasource/issues/1250 and https://github.com/tilezen/vector-datasource/issues/1251 the surface tag needs to be included.

**Comment by matkoniecz** [comment]
I see that ways with bicycle routes appear as soon as z8, surface data would be useful here. Would it be OK to show surface data also for zoom levels 11-8? (https://github.com/tilezen/vector-datasource/blob/2a4d03e69adf5f5161216a6b5a5744a7c0ccf8f3/integration-test/1170-very-early-paths-and-bike-routes.py).

**Comment by nvkelso** [comment]
Maybe. Tilezen prefers optimizing for **display** cartography (the "renderer") and smaller file sizes and better feature labeling over passing thru full set of survey properties that are more useful for other mapping services like **routing**.

Generally low- and mid-zooms should show "access" is generically possible (and should shy away from exporting features that aren't relevant at regional scale if they aren't "accessible"), and high zooms should show the details of what type of access is possible, surface tags, etc. I agree that bicycling is a crossover feature where it's useful to _see_ where in the transportation network it's easier / more preferable to route at the mid-zooms.

Please make the case with some OSM way examples that the surface tag would also be useful from zoom 8 to zoom 11.

NOTE: Tilezen generally breaks out

- **low-zoom** into `zooms 0-7` with hardly any feature properties (but the most name localization)
- **mid-zooms** into `zooms 8-14`, with
    - **early-midzoom** with more feature dropping at `zooms 8-11` and 
    - **late-midzoom** at `zoom 12-14` with less feature dropping
- **max_zoom** of `zoom 15` with "full" feature properties (512px tiles at zoom 15, and 256px zoom 16 tiles being cut up 512px zoom 15 tiles).

**Comment by nvkelso** [comment]
(It's also worth stating that we bend the rules a little for bicycling as some of us are avid cyclists ;)
