### ISSUE TITLE
Update VERSION

### ISSUE THREAD

**Issue by iandees** [tilezen/vector-datasource#1260]
We're tagged v1.3.0 but the `VERSION` file is 1.2.0.

**Comment by nvkelso** [comment]
Let's fix this as a patch version, e.g. `1.3.1`, we could get some docs fixes in there, too (there are open PRs).

**Comment by nvkelso** [comment]
Turns out there have been some code changes since, so updating version, changelog, and tagging as v1.4.0.

**Comment by nvkelso** [comment]
Fixed in https://github.com/tilezen/vector-datasource/releases/tag/v1.4.0.
