### ISSUE TITLE
Show json output when using curl

### ISSUE THREAD

**Issue by musicformellons** [tilezen/vector-datasource#1270]
When I test my running tileserver I do get output in the browser, but when I use curl it just give whether request were succesful but no output. 

E.g. I do:
`user@vps:~# curl -vso /dev/null http://localhost:8080/all/1/1/0.json | jq '.'`

And then get:
```
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /all/1/1/0.json HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost:8080
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Access-Control-Allow-Origin: *
< Content-Type: application/json
< Content-Length: 2
< ETag: "99914b932bd37a50b983c5e7c90ae93b"
< Date: Fri, 09 Jun 2017 14:45:22 GMT
< Server: Werkzeug/0.9.6 Python/2.7.6
< 
{ [data not shown]
* Closing connection 0
```

But in the browser I get actual JSON output of the relevant tiles. Can I get output with curl? How?

**Comment by zerebubuth** [comment]
The `-o /dev/null` bit of the `curl` command means "send output to nowhere". To get information in `jq`, either:

```
curl -o tile.json -vs 'http://.....
jq '.' tile.json
```

Or, if you don't want to save it:

```
curl -s http://.... | jq '.'
```

For more information on how to use `curl`, please take a look at [the curl documentation](https://curl.haxx.se/docs/manpage.html).

**Comment by musicformellons** [comment]
I was confused as I would expect data back, but apparently 'tiles are empty'. Solved now. Thanks.
