### ISSUE TITLE
Features with a empty string name

### ISSUE THREAD

**Issue by zerebubuth** [tilezen/vector-datasource#1296]
Some features are being given a blank string for the `name` property, for example:

* Natural Earth urban areas
* OSM (openstreetmapdata.com) water polygons

Check whether this is what's expected, and if the name was supposed to be omitted then remove it. If the blank name is only there to trigger some other processing, then fix that rather than exposing blank strings in the tiles.

**Comment by nvkelso** [comment]
I'm 99% sure neither of these have names in the source data, and we shouldn't expose an empty name property (drop it instead).

The ocean one has an existing bug report (that we already export empty names and shouldn't): https://github.com/tilezen/vector-datasource/issues/1139.

**Comment by nvkelso** [comment]
Fixed during Fall 2017 RAWR Tile sprint.
