### ISSUE TITLE
tunnel south of Manhattan

### ISSUE THREAD

**Issue by musicformellons** [tilezen/vector-datasource#1297]
I found a strange 'tunnel' which seems a bug (looks like it should be a boat route). I also find it in your own mapexample, so it is not in my styling. It is in the middle of my attached picture, just south of Manhattan, and crosses the Hugh L. Carey Tunnel:

![screenshot from 2017-07-03 17-38-40](https://user-images.githubusercontent.com/10334123/27799761-b919b842-6016-11e7-80e6-80f8a26d6bac.png)

**Comment by iandees** [comment]
This is a [mis-tagged way in OSM](http://www.openstreetmap.org/way/500964184). If you'd like to fix it it will get fixed in our dataset in a couple hours.

**Comment by iandees** [comment]
It looks like the ferry route mapped there was a duplicate, so I removed it in [this changeset](http://www.openstreetmap.org/changeset/50012713).

**Comment by nvkelso** [comment]
Looks like another weird minor road near Pier 11. I think there's a private ferry operator in NYC who's trying to add their routes to the map, but having problems.
