### ISSUE TITLE
[RAWR] GeoJSON output different

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1299]
This is probably not that big of a deal... but occasionally I see a few pixels different map output using RAWR tiles and today's dev build. Zooming into those regions in QGIS using the GeoJSON tile I _do_ see some different geometries for the same features. Looks like rounding errors?

**SF Bay Area:**

- http://tile.mapzen.com/mapzen/vector/v1/all/10/164/395.json (prod)
- http://tile.dev.mapzen.com/mapzen/vector/v1/all/10/164/395.json (dev, RAWR)

red = dev
black = prod

<img width="917" alt="screen shot 2017-07-03 at 10 28 17" src="https://user-images.githubusercontent.com/853051/27802774-b76aebe2-5fda-11e7-9427-64bf5db232fe.png">

**Comment by zerebubuth** [comment]
Those look like differences in line simplification, with the tolerance being well under a pixel for a z10 tile.

A possible source for that would be that many of our filters, including the line merging one, operate on the input in order but we don't have a deterministic order for the features.

**Comment by nvkelso** [comment]
At first I thought this was just near ramps for highways at zoom 9, but now I'm seeing it at zoom 10 in a more noticeable way:

![z10-quantization](https://user-images.githubusercontent.com/853051/27803274-8b1e995a-5fdd-11e7-9b79-c69137448c37.gif)
