### ISSUE TITLE
[RAWR] Missing road features in Paris

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1302]
Similar to https://github.com/tilezen/vector-datasource/issues/1298... 

In today's `dev` build with RAWR tiles phase 1 sprint (built off https://github.com/tilezen/vector-datasource/pull/1272) I'm not seeing several roads in the **roads** layer as rendered in Bubble Wrap from around zoom 15 (and in and out):

- https://tangrams.github.io/bubble-wrap/#15/48.8326/2.2687

**Prod includes all roads:**
<img width="1121" alt="screen shot 2017-07-03 at 11 56 20" src="https://user-images.githubusercontent.com/853051/27805048-19c9d81e-5fe7-11e7-845d-21ac111ac4f6.png">

**dev (RAWR) is missing some roads:**
<img width="1120" alt="screen shot 2017-07-03 at 11 56 13" src="https://user-images.githubusercontent.com/853051/27805050-19d73270-5fe7-11e7-961c-2f7c661ca65f.png">

<img width="124" alt="screen shot 2017-07-03 at 11 59 21" src="https://user-images.githubusercontent.com/853051/27805045-19c16b0c-5fe7-11e7-9984-1bc03a152809.png">
<img width="193" alt="screen shot 2017-07-03 at 11 57 46" src="https://user-images.githubusercontent.com/853051/27805047-19c9bfc8-5fe7-11e7-85d4-0df0f838dd48.png">
<img width="188" alt="screen shot 2017-07-03 at 11 57 33" src="https://user-images.githubusercontent.com/853051/27805046-19c614b8-5fe7-11e7-938d-fe2bc3283923.png">
<img width="256" alt="screen shot 2017-07-03 at 11 57 10" src="https://user-images.githubusercontent.com/853051/27805049-19caf8ac-5fe7-11e7-83e2-772166f459ab.png">
<img width="294" alt="screen shot 2017-07-03 at 11 56 58" src="https://user-images.githubusercontent.com/853051/27805051-19dbbe8a-5fe7-11e7-96c2-e778126cfbe2.png">

**Comment by nvkelso** [comment]
Some more roads are missing in central Paris:

<img width="878" alt="screen shot 2017-07-03 at 12 02 11" src="https://user-images.githubusercontent.com/853051/27805107-82327dc0-5fe7-11e7-8223-d6f80c3eb72c.png">
<img width="826" alt="screen shot 2017-07-03 at 12 02 04" src="https://user-images.githubusercontent.com/853051/27805106-8232366c-5fe7-11e7-896c-b831cae233f0.png">
<img width="180" alt="screen shot 2017-07-03 at 12 01 59" src="https://user-images.githubusercontent.com/853051/27805105-822151f8-5fe7-11e7-8536-2de03fd1d6d1.png">
<img width="195" alt="screen shot 2017-07-03 at 12 01 50" src="https://user-images.githubusercontent.com/853051/27805104-821f9bba-5fe7-11e7-9a71-d83491ad4606.png">

**Comment by zerebubuth** [comment]
After @rmarianski re-ran the min zoom functions to fix up those issues, I enqueued the TOI for Paris and it looks like the roads are back and showing properly again:

![image](https://user-images.githubusercontent.com/271360/27828580-b77215f4-60b4-11e7-9043-921f8f0b6fdf.png)

![image](https://user-images.githubusercontent.com/271360/27828746-c8877f72-60b5-11e7-9a32-08048a6a8e9f.png)

Note that I had to flush my cache to get this to work, which I thought we didn't need to do for the dev server - perhaps something wrong there too? Also, the shields are showing up a bit odd; they look like they've been offset a little, but I think that might just be the cutting-edge version of bubble-wrap I'm using.

**Comment by rmarianski** [comment]
> I enqueued the TOI for Paris and it looks like the roads are back and showing properly again

:+1: 

> Note that I had to flush my cache to get this to work, which I thought we didn't need to do for the dev server

We do set a cache control max-age header for half a day, which is what I'm guessing it was.

**Comment by nvkelso** [comment]
Verified fix on dev, closing.

This appears unrelated to RAWR tiles, might be a previous DB migration that went wrong, and we just didn't notice till now. (There haven't been any RAWR-related migrations.)
