### ISSUE TITLE
Use VW geometry simplification

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#131]
We're using the default DP geometry simplification which create angular, chunky shapes instead of beautiful shapes.

Turns out newer PostGIS includes Visvalingam-Whyatt geometry simplification popularized in the MapShaper.org tool: http://postgis.net/docs/manual-dev/ST_SimplifyVW.html

Let's start using VW for our vector tiles.

**Comment by bcamper** [comment]
oooh

**Comment by nvkelso** [comment]
Mapshaper.org CLI might be useful here?
https://github.com/mbloch/mapshaper

**Comment by rmarianski** [comment]
Thanks, will definitely take a look at that too. I also found a python package that might be useful to try: https://pypi.python.org/pypi/visvalingam

**Comment by nvkelso** [comment]
Bostock to the rescue!

On Thu, Aug 20, 2015 at 10:38 AM, Robert Marianski <notifications@github.com

**Comment by nvkelso** [comment]
This doesn't affect the API, moving to v1.1

**Comment by nvkelso** [comment]
Closing old tasks.
