### ISSUE TITLE
highway=pedestrian + area=yes (squares, plazas) are missing

### ISSUE THREAD

**Issue by matkoniecz** [tilezen/vector-datasource#1312]
* **What did you see?**

No mention in https://mapzen.com/documentation/vector-tiles/layers/ and lack of appearance of pedestrian squares on tangram maps

* **What did you expect to see?**

It is possible to display pedestrian squares as they may be a major POI, and for high zoom it is desirable to display square shape.

* **What map location are you having problems with?** _City and country are helpful, as well as tile coordinates or latitude / longitude._  
* **Screenshot?** _Props for animated gifs._

http://www.openstreetmap.org/#map=19/50.05674/19.93502
http://www.openstreetmap.org/#map=19/50.06177/19.93785
http://www.openstreetmap.org/?mlat=50.07825&mlon=19.88321#map=19/50.07825/19.88321

**Comment by nvkelso** [comment]
I already see these in vector tiles (they weren't correctly displaying in Mapzen basemaps, however).

eg: http://tile.mapzen.com/mapzen/vector/v1/all/16/36397/22210.topojson

<img width="324" alt="screen shot 2017-07-17 at 12 16 27" src="https://user-images.githubusercontent.com/853051/28285684-7f8871b6-6aea-11e7-809c-c8561f949b49.png">

Roads were coloring based on the landuse_kind intersection:

<img width="435" alt="screen shot 2017-07-17 at 12 13 52" src="https://user-images.githubusercontent.com/853051/28285693-85441966-6aea-11e7-9327-513592caf461.png">

Now after basemap style changes the area will also display:

<img width="601" alt="screen shot 2017-07-17 at 12 17 34" src="https://user-images.githubusercontent.com/853051/28285691-853ce7e0-6aea-11e7-82ec-11fa8c665dea.png">

**Comment by nvkelso** [comment]
See also TopoJSON opened into QGIS:

<img width="353" alt="screen shot 2017-07-17 at 12 36 04" src="https://user-images.githubusercontent.com/853051/28286295-939d1e20-6aec-11e7-8ddf-742e0f338200.png">

**Comment by matkoniecz** [comment]
Hm, I reported it after checking documentation at https://mapzen.com/documentation/vector-tiles/layers/#roads-transportation and it was not mentioned anywhere (or I missed this).

Is it possible that there is still a documentation big?
