### ISSUE TITLE
bridge=viaduct should receive is_bridge: true

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1314]
Following up from https://github.com/tangrams/cinnabar-style/issues/38 it turns out there are many different valid `bridge=*` values, but right now we only allow `bridge=yes` in the `is_bridge` calculation. 

We should accept a wider range of values (or just blacklist bridge=no and allow any other bridge values) to calculate `is_bridge`.

When `is_bridge: true` then should we also export the `bridge=*` value?

The same may also be true for `is_tunnel`...

Sample feature:

- https://www.openstreetmap.org/way/365016934

**Comment by nvkelso** [comment]
Looks like tunnels is more straight forward, suggest no action at this time.

- https://taginfo.openstreetmap.org/keys/tunnel#values
- `culvert` (tunnels on streams) aren't something we need to worry about right now. 
- `building_passage` seems more like an indoor mapping thing and would be covered in https://github.com/tilezen/vector-datasource/issues/1305.

**Comment by matkoniecz** [comment]
building_passage is also for real roads - see http://www.openstreetmap.org/way/72470554#map=19/50.06669/19.96823 http://www.openstreetmap.org/way/248897086#map=19/50.07460/19.91746 http://www.openstreetmap.org/way/465407841#map=19/50.08053/19.89269 http://www.openstreetmap.org/way/453556335#map=19/50.04096/19.92371 

For bridges - one may want to track down reasons for that but default map style is using following bridge values: 

> 'yes', 'boardwalk', 'cantilever', 'covered', 'low_water_crossing', 'movable', 'trestle', 'viaduct'

https://github.com/gravitystorm/openstreetmap-carto/blob/194a9e5ae4b949aa79110c73447a3d9126c1cde3/project.mml#L750

**Comment by nvkelso** [comment]
Subtask of https://github.com/tilezen/vector-datasource/issues/1349.

**Comment by nvkelso** [comment]
Looks like OpenMapTiles is having to worry about `culvert` in Paris:

- https://github.com/openmaptiles/openmaptiles/issues/360

**Comment by nvkelso** [comment]
https://taginfo.openstreetmap.org/keys/bridge#values

So really is present and not `no`.

**Comment by nvkelso** [comment]
QA verified.
