### ISSUE TITLE
http://mapzen.com/vector used in description of this github repo is a redirect

### ISSUE THREAD

**Issue by matkoniecz** [tilezen/vector-datasource#1315]
* **What did you see?**
https://github.com/tilezen/vector-datasource has 

>  Mapzen vector tile service - OpenStreetMap vector tiles in several formats http://mapzen.com/vector

* **What did you expect to see?**

Direct link to documentation/description after clicking on http://mapzen.com/vector

* **What did you see?**
"Redirecting" banner on barebone page

**Comment by nvkelso** [comment]
Thanks, fixed!

(Repo description and a few README links.)
