### ISSUE TITLE
ImportError: No module named vectordatasource.meta.python crash on running tests

### ISSUE THREAD

**Issue by matkoniecz** [tilezen/vector-datasource#1325]
* **What did you see?**

./scripts/setup_and_run_tests.sh crashed with:

Generating functions from YAML...
~/Desktop/tmp/vector-datasource/vectordatasource/meta ~/Desktop/tmp/vector-datasource/data
Traceback (most recent call last):
  File "sql.py", line 1, in <module>
    from vectordatasource.meta.python import parse_layers, output_kind, \
ImportError: No module named vectordatasource.meta.python

* **What did you expect to see?**

Passing tests.

* **Log**
Note that this was running code including #1324 to make possible to obtain test data.

https://gist.github.com/matkoniecz/cfe1de2355aa54c1b9eb6479c9c952d2

**Comment by rmarianski** [comment]
Sounds like you just need to run `python setup.py develop` first from the vector-datasource directory.

**Comment by matkoniecz** [comment]
Yeah, and running this script is already the most visible instruction in testing guide. Sorry.

**Comment by rmarianski** [comment]
No problem! Glad that's all it was.

**Comment by yaoshenshen** [comment]
I suggest run command “pip install -U -r requirements.txt” in vector-datasource
