### ISSUE TITLE
[docs] update-the-database-properties - at least create-sql-functions.py was moved

### ISSUE THREAD

**Issue by matkoniecz** [tilezen/vector-datasource#1327]
https://github.com/tilezen/vector-datasource/blob/master/CONTRIBUTING.md#update-the-database-properties fails with

```
python: can't open file 'create-sql-functions.py': [Errno 2] No such file or directory
psql: FATAL:  database "osm" does not exist
```
For start, create-sql-functions.py was moved to vectordatasource/meta/sql.py in https://github.com/tilezen/vector-datasource/commit/7a1b6d98e16b51386eb0180a164c1a19858d8781#diff-4e2091df1ddaa09aa56175a13674ed7f

I tracked down file movement - but I am not sure whatever something else described in https://github.com/tilezen/vector-datasource/blob/master/CONTRIBUTING.md#update-the-database-properties also changed.

**Comment by nvkelso** [comment]
@rmarianski I think you moved this around in master (while the docs are for the last good release tag). Can you update the docs for master, please?

**Comment by rmarianski** [comment]
Whoops, yea. It looks like it should just be that line though. I've updated it in a [pr](https://github.com/tilezen/vector-datasource/pull/1329).
