### ISSUE TITLE
natural earth has english rather local names, missing other languages, as bonus some names are malformed

### ISSUE THREAD

**Issue by matkoniecz** [tilezen/vector-datasource#1371]
* **What did you see?**

https://en.wikipedia.org/wiki/%C5%81%C3%B3d%C5%BA has label "Lódz"

I would expect either Łódź (local name, name on English wikipedia) or Lodz in ASCII form. Not unholy contraption that is neither local nor English name, probably because NE has problem with UTF8.

```
id | 5776
-- | --
kind | locality
min_zoom | 6
name | Lódz
population | 758000
region_capital | true
source | naturalearthdata.com
```

English names without local names, as result map that is trying to show labels in specific language is broken on low zoom

```
country_capital | true
-- | --
id | 7143
kind | locality
min_zoom | 4
name | Warsaw
population | 1707000
source | naturalearthdata.com
```

OSM has several languages, and specifies proper local name.

* **What did you expect to see?**
Full set of name tags from OSM data.

In other words - I think that for cities it is desirable to discard NE and use pure OSM (or merge OSM with NE).

https://github.com/gravitystorm/openstreetmap-carto has quite good (see https://www.openstreetmap.org/#map=5/51.272/21.583 or other areas on low zoom) display of labels that IIRC is based solely on OSM data (if useful I may track down and summarize how this is done)

* **What map location are you having problems with?** _City and country are helpful, as well as tile coordinates or latitude / longitude._  

Problem is global, systematic and affects all low zoom where OSM data is not used for city labels.

* **Screenshot?** _Props for animated gifs._

Encountered for example on https://mapzen.com/tangram/play/?#8.7500/48.1808/16.2415 (Vienna)  during development of https://gist.github.com/matkoniecz/456041cea84e0cc58a82a070acd5b4b1 style (if problem is not clear I may produce minimal working example).

![selection_005](https://user-images.githubusercontent.com/899988/29313651-7dd35f38-81bb-11e7-8d7b-c2cf42aa25f5.png)
![selection_006](https://user-images.githubusercontent.com/899988/29313654-7fbd63b6-81bb-11e7-8e04-e36bbf4a2636.png)

**Comment by matkoniecz** [comment]
What NE provides so simplest solution "just use OSM data in its current form" was not used?

**Comment by nvkelso** [comment]
Thanks for your report, @matkoniecz! 

This is a dup of #977, moving discussion over there.
