### ISSUE TITLE
make geometry simplification of tram tracks less agressive

### ISSUE THREAD

**Issue by matkoniecz** [tilezen/vector-datasource#1377]
* **What did you see?**
Geometry simplification of tram tracks is too easy to notice before z16

* **What did you expect to see?**
Geometry simplification is not obviously noticeable.

* **What map location are you having problems with?** _City and country are helpful, as well as tile coordinates or latitude / longitude._  
* **Screenshot?** _Props for animated gifs._

Tramtracks (and maybe other rail types) may make sharp turns

https://mapzen.com/tangram/play/#15.7500/50.0831/19.8791

15.7
![selection_010](https://user-images.githubusercontent.com/899988/29488737-7478dcca-8511-11e7-80f7-3246bee04143.png)

16
![selection_012](https://user-images.githubusercontent.com/899988/29488762-c348c392-8511-11e7-9041-50bb6a294a7e.png)

**Comment by nvkelso** [comment]
Is the transit layer any better?

**Comment by matkoniecz** [comment]
> Is the transit layer any better?

This part of railway network is service only (passengers are leaving tram on stop before loop, at the end of loop there is an initial stop), so transit layer is not providing this section of tram tracks.

![selection_002](https://user-images.githubusercontent.com/899988/29496704-88838194-85d8-11e7-8275-037f13f15541.png)

**Comment by nvkelso** [comment]
Interesting. Will have a look!

**Comment by nvkelso** [comment]
Don't see this as an issue anymore:

![image](https://user-images.githubusercontent.com/853051/52748109-7d969380-2f9a-11e9-8354-cc0dfe312aa9.png)
