### ISSUE TITLE
Remove redundant element in test?

### ISSUE THREAD

**Issue by zerebubuth** [tilezen/vector-datasource#1379]
While refactoring the tests, I came across [this test](https://github.com/tilezen/vector-datasource/blob/c730b7262b3b06215d0bcaeec077b031fe4d2aba/integration-test/593-early-footway.py#L17-L19) which checks that [this way](https://www.openstreetmap.org/way/28691787#map=13/37.7504/-122.5076) is a footway. It was edited about 7 months ago to be a `highway=path` instead, although the test still passes because there's another footway in the same tile loaded for a different test. Because the new refactored tests only load the fixture elements specific to that test, it now fails.

@nvkelso, just wanted to check that this test is redundant - it seems that there's another `highway=footway, foot=designated` just above it. Can we just drop this particular element from the test?

**Comment by nvkelso** [comment]
I think it's fine to remove the duplicate failing test.

It looks like [28691787](https://www.openstreetmap.org/way/28691787) **lacks** a name, and 
[161702316](https://www.openstreetmap.org/way/161702316) **has** a name. But they both appear at the same zoom level. There may have been proposed logic to bias paths with names to an earlier zoom that I suspect wasn't used in the final iteration so the test is junk DNA and failing to boot so let's remove it.

**Comment by zerebubuth** [comment]
Cool. Fixed in 78e8cb9.
