### ISSUE TITLE
Need to distinguish business and spur routes from basic networks

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1387]
* **What did you see?**

**First Capital Dr** in St. Charles, MO receives an interstate 70 shield when it is in fact a surface street! The motorway south of there also receives an interstate 70 shield. One of these is in error.

* **What did you expect to see?**

Technically First Capital Dr is a **business route** alternate of I-70 which is somewhat common but a little odd.

We should make sure such routes get sometime like `US:I-B` instead of `US:I` network values exported. The OSM `ref` value we draw from does correctly indicate this as a business route. I've seen the same type of thing for `US:US` routes (were we should also support something like `US:US-B`).

This should probably be paired with an alternate shield shown in grayscale and maybe with BUS. added to it on the Mapzen basemap style side that's only labeled zoom 14+? (Looks like these mostly get labeled by Tangram at zoom 15+ now so not really a change.)

* **What map location are you having problems with?** 

St. Charles, MO
http://tangrams.github.io/walkabout-style/#15/38.7781/-90.4949

* **Screenshot?** 

<img width="1078" alt="screen shot 2017-09-02 at 21 13 57" src="https://user-images.githubusercontent.com/853051/30000507-c964dcee-9023-11e7-8870-9305917d19ff.png">

**Comment by nvkelso** [comment]
See also: modifier (thanks @mojodna!):

- https://www.openstreetmap.org/relation/1933234

**Comment by zerebubuth** [comment]
What do you want the behaviour to be if the `network` is already set to something more than just `US:??`?

For example:

* [`modifier=Business`, `network=US:I:Business:Loop`](https://www.openstreetmap.org/relation/1935116) - assume this should stay as `US:I:Business:Loop`?
* [`modifier=Spur`, `network=US:NJ:Essex`](https://www.openstreetmap.org/relation/945855) - ignore the `Spur` and leave as `US:NJ:Essex`?
* [`modifier=Spur`, `network=US:NJ:CR`](https://www.openstreetmap.org/relation/941526) - should be `US:NJ:CR:Spur`? How do we tell the difference between the `CR` and `Essex` cases?

**Comment by nvkelso** [comment]
> * [`modifier=Business`, `network=US:I:Business:Loop`](https://www.openstreetmap.org/relation/1935116) - assume this should stay as `US:I:Business:Loop`?

Yes, do nothing.

> * [`modifier=Spur`, `network=US:NJ:Essex`](https://www.openstreetmap.org/relation/945855) - ignore the `Spur` and leave as `US:NJ:Essex`?

I think `US:NJ:Essex:Spur`.

> * [`modifier=Spur`, `network=US:NJ:CR`](https://www.openstreetmap.org/relation/941526) - should be `US:NJ:CR:Spur`? How do we tell the difference between the `CR` and `Essex` cases?

I think also: `US:NJ:CR:Spur`

**Comment by nvkelso** [comment]
This is working in "prod" Nextzen, closing.

**Comment by nvkelso** [comment]
Related artwork issue: https://github.com/tangrams/icons/issues/27.
