### ISSUE TITLE
Unit test follow-ons

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1392]
In https://github.com/tilezen/vector-datasource/pull/1386 @zerebubuth noted a few outstanding TODOs:

- [x] `OsmFixtureTest` seemed like a good name at the time. It turned out that having different classes for the different data sources wasn't useful, so this should be `s/^Osm//`.
    - Addressed in https://github.com/tilezen/vector-datasource/pull/1391.
- [ ] Station relation root IDs don't yet work - the list of relations needs to be passed into the fixture data source rather than having each feature already merged to its `__relations__`.
- [x] It's assumed that there's a store (e.g: S3 bucket) of pre-generated fixtures, but this isn't currently implemented. The downloading part is stubbed out, and the uploading part should (perhaps?) be done by a successful `master` branch CircleCI run.
    - https://github.com/tilezen/vector-datasource/pull/1394
- [x] There's a _lot_ of logic in `tilequeue` for this which really feels like it ought to be in `vector-datasource`, but there wasn't an obvious way to extract it cleanly.
    - _Eh, future future work. Ignore for now._
- [x] the branch of `tilequeue` that CircleCI is pulling is set to `zerebubuth/local-fixtures`. This should be changed back after https://github.com/tilezen/tilequeue/pull/241 is merged, but before this PR is merged!
    - At the time this issue was filed https://github.com/tilezen/tilequeue/pull/241 still hadn't been merged.

**Comment by zerebubuth** [comment]
Fixed the `tilequeue` branch in 6206dbf.

**Comment by zerebubuth** [comment]
Fixed the S3 caching issue in #1394 and a bunch of follow-on commits to get the upload to actually work.
