### ISSUE TITLE
unify landuse=forest and natural=wood

### ISSUE THREAD

**Issue by matkoniecz** [tilezen/vector-datasource#1397]
* **What did you see?**
It seems that handling both landuse=forest and natural=wood is necessary. Add result during testing my map style I discovered that some forests are invisible with my map style.

I am not a newbie to OSM tagging and I was still surprised. I expect that somebody new would not even notice the problem for a long time.

* **What did you expect to see?**

Both tags, with identical meanings are reduced to landuse=forest

* **What map location are you having problems with?** _City and country are helpful, as well as tile coordinates or latitude / longitude._ 

54.041902, 21.715725

* **Screenshot?** _Props for animated gifs

Not available for now (see below)

In general, I am reporting issue from mobile - I tried searching for duplicated and checked documentation, but it is possible that this report is a duplicate

**Comment by nvkelso** [comment]
Can you include several examples, please?

In most cases in the USA these should be different tags and output kinds the way the data is setup. But I wouldn't be surprised if these tags (and related tags) are miss-used a bunch either in the USA or elsewhere ;)

**Comment by matkoniecz** [comment]
In Poland in my experience both tags mean that area is forested.


https://wiki.openstreetmap.org/wiki/Forest indicates that problem is far more complicated that I remembered

**Comment by nvkelso** [comment]
I don't see a big difference between Walkabout and OSM.org for green areas. Is it possible to link to a way?

In any event, the tagging is quite complicated and a change like this would probably be a 2.x breaking change trigger.

https://www.openstreetmap.org/#map=13/54.0498/21.7344

<img width="950" alt="screen shot 2017-09-18 at 13 29 31" src="https://user-images.githubusercontent.com/853051/30563097-98db1242-9c75-11e7-8f85-e999c75f7d47.png">
<img width="938" alt="screen shot 2017-09-18 at 13 28 46" src="https://user-images.githubusercontent.com/853051/30563098-98e8635c-9c75-11e7-865b-22789e3c3cb4.png">

**Comment by matkoniecz** [comment]
In default OSM style style is the same for forest tagged as natural=wood and landuse=forest (note that I participated in selecting this rendering).

I expect that typical data consumer will display both in the same style as differences in meaning, if any, differ strongly between people editing OSM.

**Comment by matkoniecz** [comment]
http://www.openstreetmap.org/way/327548430#map=19/54.16574/21.67665 landuse

http://www.openstreetmap.org/way/30820812#map=19/54.05277/21.70385 natural

**Comment by nvkelso** [comment]
This is partially or completely addressed by other landcover changes in v1.7 milestone.
