### ISSUE TITLE
barrier=wall is missing

### ISSUE THREAD

**Issue by matkoniecz** [tilezen/vector-datasource#1403]
* **What did you see?**

barrier=wall is not exported

* **What did you expect to see?**

barrier=wall data

* **What map location are you having problems with?** _City and country are helpful, as well as tile coordinates or latitude / longitude._  

It seems to be documented as missing - see https://mapzen.com/documentation/vector-tiles/layers/

> Also includes of some barrier and waterway tags: city_wall (zoom 12+), dam (zoom 12+), retaining_wall (zoom 15+), snow_fence (zoom 15+), fence (zoom 16+ only) and gate (zoom 16+ only).

For example https://www.openstreetmap.org/way/330603734#map=19/50.07639/19.93181 is not present in data

https://mapzen.com/products/maps/cinnabar/more-labels/#lat=50.07627&lng=19.93155&z=20

Note that barrier=wall is a standard barrier tag, used over 2M times - https://taginfo.openstreetmap.org/tags/barrier=wall

* **Screenshot?** _Props for animated gifs._

**Comment by nvkelso** [comment]
Good find!

Suggest we modify `fence` so it considers `wall` in the same set also at zoom 16, like:

`- filter: { barrier: [fence, wall] }`

https://github.com/tilezen/vector-datasource/blob/4eb1fbd1cab6194713761470b2fdb57eb43d3c01/yaml/landuse.yaml#L1020-L1024

Thanks for providing a testing feature.

**Comment by nvkelso** [comment]
Verified on dev.
