### ISSUE TITLE
Vector Tiles: "building:material" property

### ISSUE THREAD

**Issue by msmollin** [tilezen/vector-datasource#1408]
From @nrdegroot: For 3D applications, it would be nice if Mapzen Vector Tiles passed through the "building:material" tag. Currently it only provides the "building:roof_material" tag.

**Comment by nvkelso** [comment]
Seems reasonable. Scheduled for v1.6

**Comment by nvkelso** [comment]
Verified in "prod" Nextzen tiles, closing.
