### ISSUE TITLE
invalid label (stale or from an external source)

### ISSUE THREAD

**Issue by matkoniecz** [tilezen/vector-datasource#1410]
* **What did you see?**

label "Nowy Miasto" that appears to not be present in current OSM data

- I tried searching for it by Nominatim - http://www.openstreetmap.org/search?query=Nowy+Miasto,%20Krak%C3%B3w#map=18/50.06645/19.94610
- and overpass http://overpass-turbo.eu/s/swb
- again, even more inclusive overpass http://overpass-turbo.eu/s/swc

* **What did you expect to see?**

nothing

* **What map location are you having problems with?** _City and country are helpful, as well as tile coordinates or latitude / longitude._  
* **Screenshot?** _Props for animated gifs._

![selection_002](https://user-images.githubusercontent.com/899988/31850525-9a75299c-b653-11e7-94d2-91e01a716b16.png)

There are two problems with it - "Nowe Miasto" (described at https://pl.wikipedia.org/wiki/Nowe_Miasto_w_Krakowie ) is name for (partially/mostly/almost completely failed) urban project, I am not aware of anybody using this name as an orientation point/area of city (though I may be wrong - but given that it is missing from OSM despite good coverage of names at least indicates that I am not an outlier).

And certainly "Nowy Miasto" is ungrammatical, if anything it should be "Nowe Miasto".

In general, place names in Poland are rather well mapped and language is tricky so I am unsure about use of third-party data.

**Comment by zerebubuth** [comment]
Thanks for pointing that out!

You're right; that label doesn't come from OSM. We take neighbourhood (and macrohood, microhood) labels from [Who's On First](https://whosonfirst.mapzen.com/), and they should be given a property `source: whosonfirst.mapzen.com` to recognise this in the output GeoJSON, TopoJSON or MVT.

I've submitted an [issue about this datum](https://github.com/whosonfirst-data/whosonfirst-data/issues/1008) on the main tracker. So hopefully will be fixed soon!

**Comment by matkoniecz** [comment]
I missed source, thanks for pointing this out!

I added

> , not: {source: [whosonfirst.mapzen.com]}

to nix this value and future wrong values. I also fixed duplicates that I wanted to investigate for some time.

**Comment by nvkelso** [comment]
@matkoniecz Can you tell us more about the duplicates, please? We have bandwidth to fix them if you provide some direction.

Hiding all `source: [whosonfirst.mapzen.com]` will hide most neighbourhood labels on the map – unless the ones in OSM are tagged something other than neighbourhood.

**Comment by matkoniecz** [comment]
https://github.com/whosonfirst-data/whosonfirst-data/issues/1022 - but I am unsure of

> We have bandwidth to fix them if you provide some direction.

given what I see https://github.com/whosonfirst-data/whosonfirst-data/pulls?page=2&q=is%3Apr+is%3Aopen

I will report more after issue that I just created is fixed and already produced PRs are processed.

**Comment by matkoniecz** [comment]
> Hiding all source: [whosonfirst.mapzen.com] will hide most neighbourhood labels on the map – unless the ones in OSM are tagged something other than neighbourhood.

So OSM labels for neighbourhoods are discarded to make space for data from whosonfirst? At least in Poland whosonfirst labels are quite low quality in my experience and using OSM data would be better.

**Comment by matkoniecz** [comment]
And clear duplicate at https://mapzen.com/tangram/play/?#17.50000/50.07097/19.94142

![selection_004](https://user-images.githubusercontent.com/899988/32135567-9c7446a2-bc01-11e7-96d2-b30769f17b76.png)

with https://github.com/ENT8R/streetcomplete-mapstyle/blob/283c61b29f27cc6f018d84ba364662be6d9ea12d/style.yaml style

**Comment by nvkelso** [comment]
@matkoniecz FYI Who's On First PRs are back near "Inbox 0" levels.
