### ISSUE TITLE
cannot seem to find pois like Wind Turbines and Crane;

### ISSUE THREAD

**Issue by nrdegroot** [tilezen/vector-datasource#1417]
I am not able to get points of interests of type wind turbine and container gantry crane to show up on the zoom levels that I tested (15-18). Since these are rather large structures I think it would be nice to include them in vector tiles.

Example of vector tile where I would like the cranes to show up: https://tile.mapzen.com/mapzen/vector/v1/all/17/103341/65074.json which is the vector tile for this location: http://www.openstreetmap.org/edit#map=17/1.26857/103.83637

**Comment by nvkelso** [comment]
The given example is:

- https://www.openstreetmap.org/node/4244069990

tag | value
:-- | :--
crane:type | portal_crane
manmade | crane

**Comment by nvkelso** [comment]
I think we already have windmills, but are you looking for an additional tag like?

- http://wiki.openstreetmap.org/wiki/Tag:power%3Dgenerator

**Comment by nrdegroot** [comment]
Thank you for the reply. The vector data seems to omit the cranes and wind turbines as points of interest. Windmills do show up but they are different from wind turbines.

**Comment by nvkelso** [comment]
Looks like the required additional tag is:

- https://taginfo.openstreetmap.org/keys/generator%3Amethod#values

Remains to be seen if we'd expand some of these value combinations to `kind` or pass them thru as `kind_detail`.
