### ISSUE TITLE
kind = park for national park

### ISSUE THREAD

**Issue by matkoniecz** [tilezen/vector-datasource#1419]
* **What did you see?**

https://www.openstreetmap.org/relation/6757027 appears as 
```
area | 1737859968
-- | --
id | -6757027
kind | park
min_zoom | 4
osm_relation | true
sort_rank | 24
source | openstreetmap.org
tier | 2
```

* **What did you expect to see?**

```
kind | national_park
```

* **What map location are you having problems with?** _City and country are helpful, as well as tile coordinates or latitude / longitude._  

https://mapzen.com/tangram/play/?#10.0000/49.2987/19.7775

```

Name | mapzen
-- | --
Layer | landuse
Tile | 284/175/9

```

* **Screenshot?** _Props for animated gifs._

tested with https://github.com/ENT8R/streetcomplete-mapstyle/blob/59efbd4867e053811ea600fe8f9fa4869518fa9c/style.yaml

**Comment by nvkelso** [comment]
We've refactored the national_park logic a few times, including in the v1.7 milestone that is in final QA. Looking at v1.6, I see this as fixed:

10.0000/49.2987/19.7775

<img width="770" alt="screen shot 2019-02-13 at 09 51 50" src="https://user-images.githubusercontent.com/853051/52732425-039fe380-2f75-11e9-9ba3-86da0ebe97cf.png">
