### ISSUE TITLE
Add new kinds for full OSM.org / iD icon library support

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1425]
Around 39:

- [x] **art** - http://wiki.openstreetmap.org/wiki/Tag:shop%3Dart
    - This is different than tourism=artwork
- [x] **beach** kind_detail – add `surface` as `kind_detail` in the **landuse** and **pois** layers.
	- [x] beach_coarse from http://wiki.openstreetmap.org/wiki/Key:surface???
- [x] **beauty** - http://wiki.openstreetmap.org/wiki/Tag:shop%3Dbeauty
- [x] **car_wash** - http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcar_wash
- [x] **charging_station** - http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcharging_station
	- bicycle=yes - electric bikes (also called pedalec) can be charged
	- scooter=yes - electric scooters can be charged
	- car=yes - electric cars can be charged
	- truck=yes - electric trucks can be charged
- [x] **chemist** - http://wiki.openstreetmap.org/wiki/Tag:shop%3Dchemist
- [x] **coffee** - http://wiki.openstreetmap.org/wiki/Tag:shop%3Dcoffee
- [x] ~~~**communications** ???~~~
- [x] **deli** - http://wiki.openstreetmap.org/wiki/Tag:shop%3Ddeli
- [x] **elevator** - http://wiki.openstreetmap.org/wiki/Tag:highway%3Delevator
- [x] **embankment** - http://wiki.openstreetmap.org/wiki/Key:embankment *** this one gets a little complicated – put into the **landuse** layer.
- [x] **furniture** - http://wiki.openstreetmap.org/wiki/Tag:shop%3Dfurniture
- [x] **grave_yard** kind_detail (already loose in religion:*)
	- [ ] grave_yard_christian
	- [ ] grave_yard_generic
	- [ ] grave_yard_jewish
	- [ ] grave_yard_muslim
	- [ ] Also add `denomination` = * to allow for `jehovahs_witness` who don't like a cross symbol, and to allow other uses.
- [x] **hifi** - http://wiki.openstreetmap.org/wiki/Tag:shop%3Dhifi
- [x] **hunting_stand** - http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dhunting_stand
- [x] **leaf_type** kind_detail: - http://wiki.openstreetmap.org/wiki/Key:leaf_type – put into the **landuse** layer.
	- [ ] leaftype_broadleaved
	- [ ] leaftype_leafless
	- [ ] leaftype_mixed
	- [ ] leaftype_needleleaved
	- [ ] leaftype_unknown
- [ ] **lift_gate** - http://wiki.openstreetmap.org/wiki/Tag:barrier%3Dlift_gate
- [x] **marketplace** - http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dmarketplace
- [x] ~~~**military_red_hatch** ???~~~  – put into the **landuse** layer as military danger area?
- [x] **miniature_golf** - http://wiki.openstreetmap.org/wiki/Tag:leisure%3Dminiature_golf
- [x] **motorcycle_parking** - http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dmotorcycle_parking
- [x] **mud** - add to landuse http://wiki.openstreetmap.org/wiki/Tag:natural%3Dmud
- [x] **newsagent** - http://wiki.openstreetmap.org/wiki/Tag:shop%3Dnewsagent
- [x] **nightclub** - http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dnightclub
- [x] ~~~**oneway_reverse** - ??? uhhh oneway=-1? http://wiki.openstreetmap.org/wiki/Key:oneway~~~
- [x] **orchard** - also into landuse http://wiki.openstreetmap.org/wiki/Tag:landuse%3Dorchard
- [x] **perfumery** - http://wiki.openstreetmap.org/wiki/Tag:shop%3Dperfumery
- [x] **plant_nursery** - also into landuse: http://wiki.openstreetmap.org/wiki/Tag:landuse%3Dplant_nursery
- [x] **plaque** - http://wiki.openstreetmap.org/wiki/Tag:memorial%3Dplaque
- [x] ~~~**power_tower_small** - what's different from power_tower? ???~~~
    - We already have `power_pole`which is used for this artwork.
- [x] **reef** - also landuse - http://wiki.openstreetmap.org/wiki/Tag:natural%3Dreef
- [x] **shoes** - http://wiki.openstreetmap.org/wiki/Tag:shop%3Dshoes
- [ ] ~~~**square** ??? http://wiki.openstreetmap.org/wiki/Proposed_features/Square ***~~~
- [x] **stationery** - http://wiki.openstreetmap.org/wiki/Tag:shop%3Dstationery
- [x] **tobacco** - http://wiki.openstreetmap.org/wiki/Tag:shop%3Dtobacco
- [x] ~~~**transport_slipway** ??? we have leisure: slipway~~~
- [x] **travel_agency** - http://wiki.openstreetmap.org/wiki/Tag:shop%3Dtravel_agency
- [x] **variety_store** - http://wiki.openstreetmap.org/wiki/Tag:shop%3Dvariety_store
- [x] **wetland** kind_detail from wetland=* after natural=wetland for kind - http://wiki.openstreetmap.org/wiki/Tag:natural%3Dwetland – put into the **landuse** layer.
	- [ ] wetland_bog
	- [ ] wetland_mangrove
	- [ ] wetland_marsh
	- [ ] wetland_reed
	- [ ] wetland_swamp
	- [ ] wetland_tidalflat

**Dec. 12th:** Looking at https://github.com/gravitystorm/openstreetmap-carto/blob/master/amenity-points.mss, propose also: 

- [x] shop=cosmetics
- [x] shop=fishmonger
- [x] military=bunker
- [x] historic=wayside_cross
- [x] barrier=swing_gate
- [x] historic=memorial_plaque
- [x] man_made=obelisk
- [x] military=danger_area

**Comment by pnorman** [comment]
What should we do with objects which are shop=chemist amenity=pharmacy? amenity=pharmacy is already handled, this would add shop=chemist.

**Comment by nvkelso** [comment]
I would make sure shop=chemist is listed **after** amenity=pharmacy so
kind=pharmacy would result from that combo (lower line number matches win).

**Comment by pnorman** [comment]
> beach kind_detail
>  beach_coarse from http://wiki.openstreetmap.org/wiki/Key:surface???

I'm looking at this and am not sure about it.

The osm.org reference to beach is https://github.com/openstreetmap/openstreetmap-website/blob/e3357b27e61c3ee4f4cf51c87fdc94deeaaa7c6f/config/locales/en.yml#L666 and iD has nothing about beach surfaces that I see.

[Taginfo shows](https://taginfo.openstreetmap.org/tags/natural=beach#combinations) 19% of beach have surface, and 15% of beach have surface=sand. 1% have surface=pebblestone, and of the remaining 3%, they don't have a common enough tag to make taginfo.

**Comment by nvkelso** [comment]
This is from the OSM carto style, for the landuse polygons. We definitely need to include the ones that have polygon symbolizes. The others I care Less about. For now it can be a pass thru, with documenting the common values only.

**Comment by nvkelso** [comment]
Looks like only OSM Carto `beach_coarse` is a symbolizer for the following `surface` values [src](https://github.com/gravitystorm/openstreetmap-carto/blob/43817980ee756b1bde2e7ee77d94e9b6d731891f/landcover.mss#L674-L690):

```
 [natural = 'beach'],
    [natural = 'shoal'] {
      [surface = 'sand'] {
        polygon-pattern-file: url('symbols/beach.png');
        polygon-pattern-alignment: global;
      }
      [surface = 'gravel'],
      [surface = 'fine_gravel'],
      [surface = 'pebbles'],
      [surface = 'pebblestone'],
      [surface = 'shingle'],
      [surface = 'stones'],
      [surface = 'shells'] {
        polygon-pattern-file: url('symbols/beach_coarse.png');
        polygon-pattern-alignment: global;
      }
    }
```

**Comment by pnorman** [comment]
> Looks like only OSM Carto beach_coarse is a symbolizer for the following surface values src:

SVG files have no direct relationship to OSM tags, e.g. [square.svg](https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/square.svg) is just a 1px square used multiple places where we wanted a square for a symbol. The tags go through osm2pgsql to turn into columns (generally a trivial transformation) then the SQL to MSS. In most cases it's easy to read off what the original tag is from the MSS selectors fairly easy, 95% are either `[key = 'value']` or using a feature column and have `[feature = 'key_value']`. There are exceptions like like the `[railway = 'runway']` which used to be used to select objects with `aeroway=runway`.

I'll go through and strike out the ones that are only file names, not related to OSM tags.

**Comment by pnorman** [comment]
For `grave_yard_christian`, `grave_yard_generic`, `grave_yard_jewish`, `grave_yard_muslim` kind_detail, I have a PR doing that right now, but I'm wondering if those are the best values for kind_detail. I think it would make more sense to have kind_detail of christian, jewish, or muslim, and no kind_detail for where it's not tagged.

**Comment by nvkelso** [comment]
I agree, just the religion value should go into kind_detail for graveyards.

**Comment by pnorman** [comment]
Do we really want to duplicate the religion between `religion` and `kind_detail` fields?

**Comment by nvkelso** [comment]
Yes. Religion should then be marked deprecated for 2.0 release.

**Comment by nvkelso** [comment]
`barrier=lift_gate` is going into kind_detail (which is fine), but we'll need to add client logic for that.

**Comment by nvkelso** [comment]
Filed some followup issues for the next milestone but generally everything here is verified (or has an issue). Closing :)
