### ISSUE TITLE
PostgreSQL statistics information

### ISSUE THREAD

**Issue by pnorman** [tilezen/vector-datasource#1448]
To look at PostgreSQL performance, I need some information from production. I can't reasonably generate this locally, since it requires running everything the same way. Most of the information just requires checking system tables, but the `pgstattuple` requires sequential scans. I can do without the `pgstattuple` information if this load is an issue, but its much easier with it.

I also need to know if any settings have been set "unusually". Everything should be able to run with a migration that doesn't change DDL, but it'd be best to not have anything running but normal rendering and updates.

```sql
-- Time-related information
SELECT NOW();
SELECT stats_reset FROM pg_stat_database WHERE datname = current_database();

-- GUCs
-- Memory
SHOW shared_buffers;
SHOW work_mem;
SHOW maintenance_work_mem;
SHOW autovacuum_work_mem;
-- Planner
SHOW random_page_cost;

-- Total size information, from https://wiki.postgresql.org/wiki/Disk_Usage
SELECT *, pg_size_pretty(total_bytes) AS total
    , pg_size_pretty(index_bytes) AS INDEX
    , pg_size_pretty(toast_bytes) AS toast
    , pg_size_pretty(table_bytes) AS TABLE
  FROM (
  SELECT *, total_bytes-index_bytes-COALESCE(toast_bytes,0) AS table_bytes FROM (
      SELECT c.oid,nspname AS table_schema, relname AS TABLE_NAME
              , c.reltuples AS row_estimate
              , pg_total_relation_size(c.oid) AS total_bytes
              , pg_indexes_size(c.oid) AS index_bytes
              , pg_total_relation_size(reltoastrelid) AS toast_bytes
          FROM pg_class c
          LEFT JOIN pg_namespace n ON n.oid = c.relnamespace
          WHERE relkind = 'r' 
  ) a
  WHERE table_schema = 'public'
) a;

SELECT relname AS "relation", pg_size_pretty(pg_relation_size(C.oid)) AS "size"
  FROM pg_class C LEFT JOIN pg_namespace N ON (N.oid = C.relnamespace)
  WHERE nspname NOT IN ('pg_catalog', 'information_schema')
  ORDER BY pg_relation_size(C.oid) DESC;

SELECT relname, n_live_tup, n_dead_tup, last_vacuum, last_autovacuum, last_analyze, last_autoanalyze FROM pg_stat_user_tables;

-- These next steps require a sequential scan
CREATE EXTENSION IF NOT EXISTS pgstattuple;

SELECT * FROM pgstattuple('planet_osm_point');
SELECT * FROM pgstattuple('planet_osm_line');
SELECT * FROM pgstattuple('planet_osm_polygon');
SELECT * FROM pgstattuple('planet_osm_roads');
SELECT * FROM pgstattuple('planet_osm_ways');
SELECT * FROM pgstattuple('planet_osm_rels');

-- GIST indexes can't be checked, so the btree ones are used as a proxy
SELECT * FROM pgstatindex('planet_osm_point_pkey');
SELECT * FROM pgstatindex('planet_osm_line_pkey');
SELECT * FROM pgstatindex('planet_osm_polygon_pkey');
SELECT * FROM pgstatindex('planet_osm_roads_pkey');
SELECT * FROM pgstatindex('planet_osm_ways_pkey');
SELECT * FROM pgstatindex('planet_osm_rels_pkey');
```

After this, I'd also be interested in the system table information after a vacuum analyze. The vacuum analyze will take some time, but doesn't lock anything but DDL.

```sql
VACUUM ANALYZE;
-- Total size information, from https://wiki.postgresql.org/wiki/Disk_Usage
SELECT *, pg_size_pretty(total_bytes) AS total
    , pg_size_pretty(index_bytes) AS INDEX
    , pg_size_pretty(toast_bytes) AS toast
    , pg_size_pretty(table_bytes) AS TABLE
  FROM (
  SELECT *, total_bytes-index_bytes-COALESCE(toast_bytes,0) AS table_bytes FROM (
      SELECT c.oid,nspname AS table_schema, relname AS TABLE_NAME
              , c.reltuples AS row_estimate
              , pg_total_relation_size(c.oid) AS total_bytes
              , pg_indexes_size(c.oid) AS index_bytes
              , pg_total_relation_size(reltoastrelid) AS toast_bytes
          FROM pg_class c
          LEFT JOIN pg_namespace n ON n.oid = c.relnamespace
          WHERE relkind = 'r' 
  ) a
  WHERE table_schema = 'public'
) a;

SELECT relname AS "relation", pg_size_pretty(pg_relation_size(C.oid)) AS "size"
  FROM pg_class C LEFT JOIN pg_namespace N ON (N.oid = C.relnamespace)
  WHERE nspname NOT IN ('pg_catalog', 'information_schema')
  ORDER BY pg_relation_size(C.oid) DESC;

SELECT relname, n_live_tup, n_dead_tup, last_vacuum, last_autovacuum, last_analyze, last_autoanalyze FROM pg_stat_user_tables;
```

If it's easier, I can give this as a file of SQL.

-----

I also need some running query information. The best way to do this is to sample the running queries and treat it like the [German tank problem](https://en.wikipedia.org/wiki/German_tank_problem). This was useful in https://github.com/openstreetmap/operations/issues/105

This shell script needs to be run, and will sample active queries for two hours, with about 1k samples. The time is chosen to not align with 1 minute, which might result in lots of samples when monitoring is done. The `psql` connection variables will probably need adjusting

```sh
for i in `seq 1 1024`; do 
psql -AtqX -d postgres -c "COPY (SELECT pid, NOW(), NOW()-query_start AS query_duration, query FROM pg_stat_activity WHERE datname = 'osm' AND pid != pg_backend_pid() AND state != 'idle') TO STDOUT;" >> query_log.txt;
sleep 7;
done
```

**Comment by nvkelso** [comment]
@zerebubuth can help out on this...

@rmarianski to give a once over before he leaves on vacation, please.

**Comment by rmarianski** [comment]
LGTM :+1: From my reading of it, we can run the queries any time and don't need to be concerned about any locking, but definitely highlight if any part of it could impact production if I missed it. We do also have have a slow query log that might be of some use.

**Comment by pnorman** [comment]
> definitely highlight if any part of it could impact production if I missed it

The `pgstattuple` stuff has some seq scans, but a single seq scan of each table isn't a big issue. The `VACUUM ANALYZE` will also involve some IO. The total IO should be less than the difference between off-peak and peak hours.

> We do also have have a slow query log that might be of some use.

That would be good too.

**Comment by zerebubuth** [comment]
The output from running the stats: [stats.log](https://github.com/tilezen/vector-datasource/files/1528434/stats.log). Output of `VACUUM ANALYZE` might take a little longer to appear :wink:

**Comment by zerebubuth** [comment]
Log from running the `VACUUM ANALYZE`: [vacuum-analyze.log](https://github.com/tilezen/vector-datasource/files/1530739/vacuum-analyze.log).
