### ISSUE TITLE
Where is /tileserver?

### ISSUE THREAD

**Issue by vomc** [tilezen/vector-datasource#1472]
* **What did you see?**

I ran through the instructions from here https://github.com/tilezen/vector-datasource/wiki/Mapzen-Vector-Tile-Service setting this up on a new EC2 instance and everything installed. Now am on step 4 (Serve vector tiles)

* **What did you expect to see?**

I am in my `env` and am not finding a `tileserver` directory anywhere, neither can i find a `config.yaml.sample` file (can't find that in the repo either) and neither can I find the `tileserver/__init__.py` file... What am I missing?

![screen shot 2018-01-11 at 11 42 23 am](https://user-images.githubusercontent.com/78635/34836000-87c861e0-f6c4-11e7-86df-2cc8039fd94f.png)

**Comment by vomc** [comment]
btw the tests ran ok, so there must be something working?

Ran 102 tests in 2.638s
OK

**Comment by nvkelso** [comment]
Do you have the separate tileserver repo checked out besides Vector-datasource repo?

**Comment by vomc** [comment]
Haha - so sorry, I am a total newbie to this. I see that now, going to check that out and build from there.

**Comment by pranavpandey1998official** [comment]
hi I bummed into same issue where did you find the tileserver repo

**Comment by rmarianski** [comment]
https://github.com/tilezen/tileserver
