### ISSUE TITLE
import data shapefiles.tar.gz 404

### ISSUE THREAD

**Issue by m-abboud** [tilezen/vector-datasource#1479]
`make -f Makefile-import-data` fails with a 404 on http://s3.amazonaws.com/mapzen-tiles-assets/20171201/shapefiles.tar.gz now

and` make -f Makefile-prepare-data` fails on  http://s3.amazonaws.com/mapzen-tiles-assets/curated/buffered_land_05232017.zip

**Comment by va2ron1** [comment]
Apparently all the data of mapzen is already offline, we need to wait for updates or alternatives.

**Comment by rmarianski** [comment]
Right, it's because those buckets were removed recently. We'll be working on trying to provide an alternate way of getting started.

Depending on what your goals are, you could be able to hack it to move past this point. Most of the data comes from natural earth, with the details in the [assets yaml](https://github.com/tilezen/vector-datasource/blob/master/data/assets.yaml) file.

But if you're able to sit tight for a little bit we'll have updated instructions that will be easier.

**Comment by m-abboud** [comment]
Yeah found out about the yamls used for generating the makefile scripts already. Removed buffered_land from the list and regenerated shapefiles.tar.gz with the prepare-data makefile and threw it on our own s3 bucket.

Tileserver didn't barf when doing a wget for a tile so looks like it's somewhat happy without that one shapefile. (Haven't tested out actually displaying the tiles yet though)

Not really sure what's supposed to be in the buffered_land shape file I searched the repo for it and just found some issues that mention it needs to be updated nothing on how it's actually generated and the file only existed on mapzens s3. Luckily it appears to be the only truely missing file.

If anyone happens to have it lying around it would be awesome if you posted it here (sounds like it's only around 10mb) :)

**Comment by m-abboud** [comment]
oh looks like it was commited at one point: https://github.com/tilezen/vector-datasource/blob/b43f70dd1408d8fa3b781689d0850a90df1355a2/data/buffered_land.zip

Guess that will work for now

**Comment by nvkelso** [comment]
The latest buffered land file is attached to: https://github.com/tilezen/vector-datasource/issues/1257.

**Comment by nvkelso** [comment]
We'll repost these files to a Nextzen S3 bucket and update the documentation. @rmarianski for that.

**Comment by rmarianski** [comment]
Is it attached to that issue? It looks like it's just a link to a whosonfirst s3 location that no longer works. Any possibility that it's still floating around in another location?

**Comment by stepps00** [comment]
@rmarianski - [This ](https://github.com/tilezen/vector-datasource/files/1805335/buffered_land_05232017.zip) should be a copy of the `buffered_land_05232017.zip` file that contains an updated buffered land file with a fix for https://github.com/tilezen/vector-datasource/issues/1257.

**Comment by rmarianski** [comment]
Thanks @stepps00! I'll get this packaged up and put in a public bucket and get the instructions updated tomorrow.

**Comment by va2ron1** [comment]
Just a reminder that the shapefiles or buffred_land aren't the only one, also the dump database of wof_neighborhood doesn't exist.

**Comment by rmarianski** [comment]
Updated shapefiles at a new location: https://s3.amazonaws.com/nextzen-tile-assets/20180313/shapefiles.tar.gz

I need to still update the docs and get the whosonfirst data on there.

**Comment by m-abboud** [comment]
Awesome thank you!

**Comment by rmarianski** [comment]
A postgresql dump of the data of the whos on first data can at a [new location](https://s3.amazonaws.com/nextzen-tile-assets/wof/wof-neighbourhoods.pgdump). I updated the wiki instructions to point to this new location.

**Comment by nvkelso** [comment]
@rmarianski Does this buffered land reference also need updating?

- https://github.com/tilezen/vector-datasource/blob/master/data/assets.yaml#L25

**Comment by rmarianski** [comment]
> https://github.com/tilezen/vector-datasource/blob/master/data/assets.yaml#L25

It does, but it's a "code" update so holding off on that for the time being. But, I'm happy to put in a pr for it now if that's cool with you.

**Comment by nvkelso** [comment]
Noting here we'll need to modify:

- https://github.com/tilezen/vector-datasource/blob/master/data/assets.yaml#L1-L2

To reflect:

```
bucket: nextzen-tile-assets
datestamp: 20180313
```

**Comment by nvkelso** [comment]
Todo: 

- Make a new bucket with the new `tilezen-assets` name
- Copy old assets over to new bucket, kill the old bucket
- Update logic here in `vector-datasource`

**Comment by zerebubuth** [comment]
* New bucket created called `tilezen-assets`
* Assets copied over, but **old bucket not yet deleted**.
* Updated logic in #1486.

**Comment by zerebubuth** [comment]
#1486 has been merged. Apologies to everyone who has been blocked on this. Please try again and let us know if you run into any issues.
