### ISSUE TITLE
Link to better Mapbox GL styles in display-tiles.md

### ISSUE THREAD

**Issue by m-abboud** [tilezen/vector-datasource#1490]
Hey guys, we recently wrote a few mapbox styles that work with tilezen's tile format that can be found at [](https://github.com/apollomapping/ap-tilezen-mapbox-styles). 

The styles are much more complete than the example you guys link to in a few different places, this guy: [](https://github.com/mapzen/mapboxgl-vector-tiles). Also they work with style spec v8 and the latest gl js version v0.44.1 and come with public urls for our static fontstack and sprite resources instead of using a mapbox api key for fonts.

So wondering if you guys want to link to these styles instead in display-tiles.md? (and might be in some other places too). If so I can make a PR...

**Comment by nvkelso** [comment]
Sounds useful, yes! Can you link to the styles please? Then we can get specific about PR.

**Comment by m-abboud** [comment]
Oops the markdown link didn't show up cus I didn't put anything in the text part here you go: https://github.com/apollomapping/ap-tilezen-mapbox-styles

Sorry about that!

**Comment by nvkelso** [comment]
3 even! Is there a live demo?

**Comment by m-abboud** [comment]
You can use: https://stage-client.mapmavin.com/?id=26133 to see it (the base map switcher is in the bottom left corner). But it doesn't have a purpose made demo page yet.

**Comment by m-abboud** [comment]
an actual demo page: https://apollomapping.github.io/ap-tilezen-mapbox-styles/demo/demo.html

**Comment by nvkelso** [comment]
Nice work! Are the Mapbox GL styles also MIT licensed? 

FYI: lots of state road shields in here, MIT licensed so have at them: https://github.com/tangrams/icons.

We're happy to take a PR :)
