### ISSUE TITLE
Turkish Road Shields

### ISSUE THREAD

**Issue by zerebubuth** [tilezen/vector-datasource#1517]
Normalise Turkish `ref`s and `network`s.

See https://github.com/tilezen/vector-datasource/issues/1491#issuecomment-391825067, https://github.com/tilezen/vector-datasource/pull/1515#pullrequestreview-125754713 and https://github.com/tilezen/vector-datasource/pull/1515#pullrequestreview-125754833.

Subtask of #1491.

**Comment by nvkelso** [comment]
Verified on dev, closing.
