### ISSUE TITLE
Vietnamese Road Shields

### ISSUE THREAD

**Issue by zerebubuth** [tilezen/vector-datasource#1518]
Backfill network and shield text for [roads in Vietnam](https://en.wikipedia.org/wiki/Transport_in_Vietnam#Road_transport).

Subtask of #1491.

**Comment by zerebubuth** [comment]
See also https://github.com/tilezen/vector-datasource/pull/1515/files/28c06004411a57c4fabc29241d7315d81e182fc6#diff-e2b4972fb4f09e75e9a85c43ef5d8d41.

**Comment by nvkelso** [comment]
Verified on dev.
