### ISSUE TITLE
Swiss Road Shields

### ISSUE THREAD

**Issue by zerebubuth** [tilezen/vector-datasource#1519]
Use `CH:motorway` and `CH:national` (not  `CH:nationalstrasse`), and `CH:regional`.

See https://github.com/tilezen/vector-datasource/pull/1515#pullrequestreview-125733546 and https://github.com/tilezen/vector-datasource/issues/1491#issuecomment-394894677

**Comment by nvkelso** [comment]
There's not a whole lot of CH:national or CH:regional set in the sites but this is working as expected.
