### ISSUE TITLE
Spanish Road Shields I

### ISSUE THREAD

**Issue by zerebubuth** [tilezen/vector-datasource#1521]
* Autopistas with refs staring `RP` should return `ES:AP` network
* National routes with `ref`s starting `N` or `N-` should return `ES:N` network. Note some of these get shield text now, some don't.
* National routes with `ref`s staring `NA` should return `ES:AA` network. (yellow)
* "Provincial" roads with `ref`s starting with thier region code should return `ES:{region_code}`. Partial list: AS, BU, C-, EI, M-, PA, TF and AG, AS, BI, C-, CM, Ma, MA, Me, EI, EX, FV, GC, GI, LO, LR, LZ, M-, PA, RM, TF, V-. Shield text shouldn't include that prefix.

See https://github.com/tilezen/vector-datasource/issues/1491#issuecomment-391825067

Subtask of #1491.

**Comment by nvkelso** [comment]
This is working but OMG it's still broken in so many ways. We've documented further fixes in https://github.com/tilezen/vector-datasource/issues/1531 for the next release.
