### ISSUE TITLE
How to add another OSM file via osm2pgsql?

### ISSUE THREAD

**Issue by guyisra** [tilezen/vector-datasource#1536]
* **What did you see?**
going through the process with a clean db and a specific osm.pbf file works and is able to generate tiles. 
Trying to run another osm2pgsql command with a different osm file (different region in the world) causes some corruption in the DB which gives errors when trying to pull tiles:

```
2018-06-17 16:39:00.371 IDT [2788] ERROR:  column "mz_label_placement" does not exist at character 2107
```
and in tileserver:

```
    raise DataFetchException(async_exceptions)
DataFetchException: column "mz_label_placement" does not exist
LINE 102:     mz_label_placement,
              ^
, column "mz_label_placement" does not exist
LINE 64:     mz_label_placement,
             ^
, column "mz_poi_min_zoom" does not exist
LINE 60:       WHEN mz_poi_min_zoom IS NOT NULL AND
                    ^
^C%
```
* **What did you expect to see?**

The osm files attempted are https://download.bbbike.org/osm/bbbike/NewYork/NewYork.osm.pbf and and http://download.geofabrik.de/europe/andorra-latest.osm.pbf

Loading each separately to a clean db works

Is there a different way to load new osm data to the db ?

**Comment by ImreSamu** [comment]
> The osm files attempted are https://download.bbbike.org/osm/bbbike/NewYork/NewYork.osm.pbf 
> and and http://download.geofabrik.de/europe/andorra-latest.osm.pbf

my best workaround is merging all osm input files into one.
*  [ "osmium-merge - merge several sorted OSM files into one"](https://docs.osmcode.org/osmium/latest/osmium-merge.html)

but be sure :
* they must be from the same data source 
     * Merging "bbbike" and "geofabrik" sources probably not will work.
* and same "point in a time". 


for example - merging same geofabrik(180601)  versions should work:
* wget http://download.geofabrik.de/north-america/us/new-york-180601.osm.pbf
* wget http://download.geofabrik.de/europe/andorra-180601.osm.pbf
* `osmium merge new-york-180601.osm.pbf  andorra-180601.osm.pbf  -o mytestdata-180601.osm.pbf`

**Comment by guyisra** [comment]
Thanks
Once this merged osm is in the DB, how would you update the db with new new information on a region?
