### ISSUE TITLE
rawr + Metatile generation assistance

### ISSUE THREAD

**Issue by guyisra** [tilezen/vector-datasource#1537]
I'm having trouble understanding the flow of commands needed to produce metatiles. 
tileserver runs successfully, serving tiles from either tile store (local folder via `tilequeue process`) or directly from postgres.

From what I understand (and please correct me where I'm wrong):
- once data is in postgres, there are 2 flows:
  1. zoom <= 10
  2. zoom > 10

- for zoom <= 10, the tiles generation would be either with batch or on-demand to generate, store (in s3 or similar) and serve as is, via cdn and use caching (cdn or redis) where appropriate
- for zoom > 10, rawr files needs to be created from which the tiles will be generated 

rawr tiles, from what I gather,  are created via its own queue (differnet from the `tilequeue process` queue) and are seeded from the TOI? 
 - what command(s) are needed to generate them? `tilequeue rawr-process` produces a `admin_areas relation does not exist` and `tilequeue-rawr-seed-toi` explodes after some tiles due to the `assert len(coords) == 1`

I noticed a (undocumented) command for `metatile` and `meta-tile-low-zoom` which seems to fit the process described above but these command are a per tile commands, and do not read from a queue (which I'm not sure how the queue is populated, and by what logic and by who)

thanks

**Comment by zerebubuth** [comment]
Apologies for the confusion! We've changed how this works a few times, and we're still settling into a stable and documented way to do tile generation. A lot of this is still work in progress while we iterate towards something more automated.

You understand correctly about the split between low (`zoom < 10`) and high (`zoom >= 10`) tiles. Our current process (as used for the [Nextzen tiles](https://nextzen.org/)) is to batch generate all the tiles at all zooms. We've started trying to automate that with a package we call [tileops](https://github.com/tilezen/tileops). Although it's very much tied to AWS, it might be possible to adapt to other platforms.

An outline of the process is:

1. Import data into the database.
2. Generate RAWR tiles using [`tilequeue rawr-tile`](https://github.com/tilezen/tileops/blob/e35567367660a0d43d770e6a8e1527ac97f24225/batch-setup/batch.py#L98-L101).
3. Generate high-zoom meta tiles from the RAWR tiles using [`tilequeue meta-tile`](https://github.com/tilezen/tileops/blob/e35567367660a0d43d770e6a8e1527ac97f24225/batch-setup/batch.py#L104-L107).
4. Generate low-zoom meta tiles from the database using [`tilequeue meta-tile-low-zoom`](https://github.com/tilezen/tileops/blob/e35567367660a0d43d770e6a8e1527ac97f24225/batch-setup/batch.py#L110-L113).

For the database, we use AWS RDS, and "replicate" by taking a snapshot and starting several servers from the snapshot. For the tile generation (RAWR, high and low meta), we use AWS Batch. Tiles are stored in AWS S3 buckets.

Although all the logic in [`tileops`](https://github.com/tilezen/tileops) is to deal with AWS, the general pattern should be applicable to anything that can run databases, batch tasks and has a file store.

Hope that helps!

**Comment by zerebubuth** [comment]
At the moment, we've just been running the scripts from our laptops. It's not ideal, and hopefully at some point soon we'll bundle the "control" parts into a container which can be kicked off and monitored from a web page.

The `Ref::tile` is substituted by AWS Batch based on the value we [enqueued the job with](https://github.com/tilezen/tilequeue/blob/4062c1a579bdf965a4ebc711f238d8b37de8b926/tilequeue/command.py#L2026-L2029) (the `run_id` is just a string which gets echoed to the logs to help us distinguish between multiple runs). It's worth noting that we've been using a `queue_zoom` of 7 in order to keep the number of jobs down (`4**7 = 16k` rather than `4**10 = 1M`).

**Comment by guyisra** [comment]
So as I understand, using the rawr-tile job, means to enqueue the job (manually? with a loop?) with all of the tiles that would be in the sqs? 

would running `rawr-tile --tile z/x/y` be equivalent to running `rawr-process` from the queue after `rawr-seed`?

**Comment by zerebubuth** [comment]
[The `batch-enqueue` command](https://github.com/tilezen/tilequeue/blob/4062c1a579bdf965a4ebc711f238d8b37de8b926/tilequeue/command.py#L2490-L2499) handles enqueuing the Batch jobs for `rawr-tile`. By default (if `--file`, `--tile` and `--pyramid` are not specified) it [enqueues all the tiles](https://github.com/tilezen/tilequeue/blob/4062c1a579bdf965a4ebc711f238d8b37de8b926/tilequeue/command.py#L2008-L2020).

Making RAWR tiles through Batch + `rawr-tile` or SQS + `rawr-process` should be equivalent, yes. Although we've only been using Batch recently.

**Comment by nvkelso** [comment]
Please let us know if you have any other questions with a new issue :)
