### ISSUE TITLE
Road networks wrong at zooms 8-12 in Minnesota

### ISSUE THREAD

**Issue by zerebubuth** [tilezen/vector-datasource#1548]
At zoom 13, the `network` property on state roads in Minnesota is set to `US:MN`, as expected:

![Correct US:MN network](https://user-images.githubusercontent.com/271360/42540712-9b189904-846d-11e8-80f5-329eb6ca62fa.png)

But at zoom 12, the `network` is incorrectly set to `MN`:

![Incorrect MN network](https://user-images.githubusercontent.com/271360/42540672-63f98d2a-846d-11e8-8a34-1dda01317114.png)

This persists up to zoom 8, after which the data is replaced by NE data.

**Comment by nvkelso** [comment]
Verified on dev.
