### ISSUE TITLE
Some Greek roads wrongly assigned GR:motorway network

### ISSUE THREAD

**Issue by zerebubuth** [tilezen/vector-datasource#1550]
![image](https://user-images.githubusercontent.com/271360/42587716-90d5e91e-8509-11e8-9007-ffb0f29c2327.png)

Some roads have refs starting with Α (capital alpha), but are not motorway-class roads. Looks like they're all `GR:provincial:A1`, which are local roads in [the Attica region](https://en.wikipedia.org/wiki/Attica_(region)). They should keep their existing network tag rather than have it overridden.

**Comment by nvkelso** [comment]
This is fixed on dev, verified and closing.
