### ISSUE TITLE
Pacific ocean broken at zoom 5

### ISSUE THREAD

**Issue by zerebubuth** [tilezen/vector-datasource#1557]
* **What did you see?**

<img width="1678" alt="screen shot 2018-08-22 at 17 53 27" src="https://user-images.githubusercontent.com/271360/44478071-6f436c80-a634-11e8-9e56-dbf1b6d50f3c.png">

* **What were you expecting to see out of a Torquay hotel bedroom window? Sydney Opera House, perhaps? The Hanging Gardens of Babylon? Herds of wildebeest sweeping majestically -?**

Don't be silly. I expect to be able to see the sea.

* **What map location are you having problems with?** _City and country are helpful, as well as tile coordinates or latitude / longitude._  

Pacific ocean, west of 90W and in the whole northern hemisphere at (nominal) zoom 5.

**Comment by nvkelso** [comment]
Verified fix on dev, closing.
