### ISSUE TITLE
Palisades Interstate Park in NJ missing

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#158]
Ekta pointed this out:

![screen shot 2015-09-02 at 13 54 30](https://cloud.githubusercontent.com/assets/853051/9644126/5e9c96a2-517a-11e5-9e73-bf110a37f359.png)

**Comment by nvkelso** [comment]
https://www.openstreetmap.org/edit?#map=16/40.8704/-73.9467

Looks like we do include the feature in tiles:
http://vector.mapzen.com/osm/all/15/9652/12301.topojson?api_key=vector-tiles-HqUVidw

But it's tagged "woods", which is kinda weird. Is this a data problem (correct tag to park), or something we should address in the stylesheet / scene file?

**Comment by nvkelso** [comment]
```
],
"properties":
{
"area":
9632260,
"id":
-222299,
"kind":
"wood",
"name":
"Palisades Interstate Park",
"osm_relation":
true,
"source":
"openstreetmap.org"
},
"type":
"Polygon"
```

**Comment by rmarianski** [comment]
Looks like it's coming from here: http://www.openstreetmap.org/way/39649141

`natural=wood`

The relevant coalesce from the query:

```sql
COALESCE("landuse", "leisure", "natural", "highway", "aeroway", "amenity", "tourism", "man_made") AS kind,
```

**Comment by nvkelso** [comment]
Plenty of green areas here now:

![image](https://user-images.githubusercontent.com/853051/52679248-592eae80-2ee9-11e9-9241-b1d501d2cc9f.png)
