### ISSUE TITLE
Include turning_circle(, turning_loop, mini_roundabout)

### ISSUE THREAD

**Issue by westnordost** [tilezen/vector-datasource#1695]
In OSM, there are 
* [`highway=turning_circle`](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dturning_circle)
* [`highway=turning_loop`](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dturning_loop)
* [`highway=mini_roundabout`](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dmini_roundabout)

These features all have in common that they can be represented as a circular slub in the road-way at the node position where it is tagged.

On the default mapnik map, the first two look like this.
![](https://wiki.openstreetmap.org/w/images/8/8e/Mapping-Features-Turning-Circle.png)

In the vector-datasource though, they are not included, so it cannot be rendered. I think it would make sense to include it in one way or another because it is useful to see if one can easily turn at the end of dead end street or not.

**Comment by nvkelso** [comment]
Sounds good! We already have `mini_roundabout` in the **pois** layer: https://github.com/tilezen/vector-datasource/blob/767cc230410996a3974b146fa621ec2ab99e8751/yaml/pois.yaml#L1354-L1358

Can you submit a PR for the other two? Probably a min_zoom of `16` since they are terminal and not in normal traffic flow? Since they don't have names you'd need to also extend the list of highway PONI's in:

https://github.com/tilezen/vector-datasource/blob/767cc230410996a3974b146fa621ec2ab99e8751/yaml/pois.yaml#L191-L192

**Comment by westnordost** [comment]
I do not fully understand the configuration file, but I'll try. Not sure if I have to do more than this:
https://github.com/tilezen/vector-datasource/pull/1697

**Comment by nvkelso** [comment]
PR looks great! We can continue work thru the test part more in that PR together.

We're working on the v1.6 milestone and this change would go out in the next Nextzen prod build once that finalizes (but may be a month or two).

**Comment by nvkelso** [comment]
This all should probably be at **zoom 17** not 16 or (and mini_roundabouts at 17 not 15, to match OSM style). They'd still be overstuffed into tiles at zoom 16, though.

18/37.75586/-122.47092

![image](https://user-images.githubusercontent.com/853051/49976314-42260d00-fef6-11e8-9e17-96f8efaeb722.png)

19/37.77639/-122.44749

![image](https://user-images.githubusercontent.com/853051/49976378-78638c80-fef6-11e8-961d-a6d8a364d406.png)

19/37.90619/-122.55390

![image](https://user-images.githubusercontent.com/853051/49976420-a34de080-fef6-11e8-8a73-2d31aab4d6df.png)

**Comment by nvkelso** [comment]
Well, https://github.com/tilezen/vector-datasource/blob/master/SEMANTIC-VERSIONING.md#major-version-increments says +2 min_zoom change would be major version change so making `mini_roundabouts` to be 16 instead of 15 (and not 17).

**Comment by nvkelso** [comment]
Verified.
