### ISSUE TITLE
Slimming down boundaries

### ISSUE THREAD

**Issue by zerebubuth** [tilezen/vector-datasource#1715]
Since https://github.com/tilezen/tilequeue/pull/354 fixed a bug, we've been pulling in far more boundaries, median increase in _layer_ size of 40%. Note that the boundaries layer is generally fairly small, and by stripping long names off (#1683) we've reduced layer size significantly at lower zooms. The increase mainly affects mid zooms 9-11, although also zoom 5 (nominal).

We annotate the boundaries with the left and right OSM IDs of the relations they delineate, but these are probably not used in styling. We could remove them to save a significant amount of space in tiles with a lot of boundaries. In addition, this would open up opportunities for merging which are not available at the moment as the left/right ID pair is nearly-unique.

As well, or instead, we could consider showing detail boundaries (`kind: locality`) at higher zooms (currently start at 10). The problem is that countries vary wildly in the density of their localities, so it's possible that a good value for the `min_zoom` in one country wouldn't be appropriate for another. Annotating with the country code and clipping might be an option, although complex.

**Comment by zerebubuth** [comment]
E.g: `9/285/169` (512 tile, so that's zoom 10), near Warsaw, has a lot of very detailed localities. For example, [Robercin](https://www.openstreetmap.org/relation/4258233).

![image](https://user-images.githubusercontent.com/271360/49398875-8ae00800-f737-11e8-8cb1-2b57e981db57.png)

**Comment by nvkelso** [comment]
1. I'm fine always stripping off the `id` from OSM and NE at low zooms (say anything that's zoom 0-12), and possibly all the way up to the maximum zoom of 15 if we really needed it (keeping `id` at the max zoom), for all **boundaries** layer features.

2. Are we currently stripping the labels off the `region` lines per country as part of https://github.com/tilezen/vector-datasource/pull/1700 and https://github.com/tilezen/vector-datasource/issues/1683? That also might help?

3. Regarding stripping names off early `locality` **boundaries** lines, yes! I don't need to see those labels until zoom 13+.

4. In addition, it looks like we start including `locality` boundaries lines at zoom 10 (the same zoom as counties). We can drop `locality` min_zoom to 11, that'll save generally on file size.

**Back to locality names...**

Here's [zoom 12](http://tangrams.github.io/bubble-wrap/#12/37.8668/-122.3561), the point label is enough, along with boundary line (in tiles but not shown in Bubble Wrap).

![image](https://user-images.githubusercontent.com/853051/49407090-50ad4100-f70c-11e8-90a6-b031a0ccce6b.png)

At [zoom 13](http://tangrams.github.io/bubble-wrap/#13/37.9061/-122.4916)+ it's legit to show the locality names along the lines as long as they fit (drop locality kind before running fit dropping):

![image](https://user-images.githubusercontent.com/853051/49407064-3bd0ad80-f70c-11e8-886f-21f31944fdb4.png)

In practice, most basemaps don't show boundary lines with labels until [zoom 15](http://tangrams.github.io/bubble-wrap/#15/37.9364/-122.5259)+ (still not shown in Bubble Wrap, but suitable for some maps styles): 

![image](https://user-images.githubusercontent.com/853051/49406941-de3c6100-f70b-11e8-9493-458a5bca91a9.png)

**Comment by nvkelso** [comment]
PR #1725 looks good.

I filed 2 followup issues:

- #1737 Also drop is_relation property when dropping id tags from low and mid-zooms 
- #1738 Drop name, name:left, name:right from locality boundary lines at zoom 11 and 12
