### ISSUE TITLE
[REPEAT] Boundaries layer features tagged maritime_boundary = 1 in error

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1726]
The fix we landed in https://github.com/tilezen/vector-datasource/issues/1482 in v1.5 somehow didn't make it into the build?

![image](https://user-images.githubusercontent.com/853051/49835724-f6882d80-fd54-11e8-9f58-ce51248582f2.png)

**Comment by zerebubuth** [comment]
Hmmm.... That's really annoying. How many times have we "fixed" this now?

I tried to reproduce this locally and with the latest (internal v1.6c) build, and wasn't able to find the `maritime_boundary` property on the USA-CA border around zooms 7-10. Although there's so many name properties it's possible I missed it.

Could you let me know exactly which URL is being used to load those tiles, from the Chrome/Firefox inspector network tab ideally, please? Privately, if this is an internal build.

**Comment by nvkelso** [comment]
The Tag Explorer uses the public Nextzen build based on v1.5 schema:

https://tangrams.github.io/explorer/#9.0/48.6320/-123.0359/kind/country

Eg it's loading tiles like:

- https://tile.nextzen.org/tilezen/vector/v1/512/all/8/40/87.mvt

**Comment by nvkelso** [comment]
This looks fine in dev. Fingers crossed it looks good on staging as well.

**Comment by nvkelso** [comment]
Looks good in staging, closing :)

**Comment by nvkelso** [comment]
This happened again in dev, reopening into v1.7 milestone.
