### ISSUE TITLE
Boundary lines sometimes flipped

### ISSUE THREAD

**Issue by zerebubuth** [tilezen/vector-datasource#1770]
* **What did you see?**

Near `16.65/48.99711/-121.74050`, e.g: in tile `512/all/15/5303/11253`:

![image](https://user-images.githubusercontent.com/271360/50687437-3622fc00-1019-11e9-96f6-9d14e1c9c614.png)

* **What did you expect to see?**

British Columbia is in Canada, and Washington state is in the USA.

Confirmed in the `512/all/15/5303/11253` tile that the `kind: region` line runs west to east across the tile, so its left is the bottom and right is the top, however, the `name:left` is `British Columbia`. The `country` and `county` lines (at least in this tile) run east to west and have the correct left/right names for that direction.

This is the same in both MVT and GeoJSON tiles, so appears to be a fault in the tile (post)processing rather than in the formatting.

**Comment by nvkelso** [comment]
**First the good news:** The original bug about flipped boundaries does seem fixed!

**Bad news:** Looking at the original report area (near 16.65/48.99711/-121.74050, e.g: in tile 512/all/15/5303/11253), I no longer see any country boundaries. 

Digging a bit more, if I disable the client-side water boundary filter, then they are restoring. Meaning https://github.com/tilezen/vector-datasource/issues/1726 has cropped up again? I'll reopen that into this milestone :\

![image](https://user-images.githubusercontent.com/853051/52095541-2c3cdc00-2578-11e9-8f5c-77a2b664f77a.png)

![image](https://user-images.githubusercontent.com/853051/52095463-d0725300-2577-11e9-9deb-7dea69ca54f1.png)


Another bad spot from before:

![image](https://user-images.githubusercontent.com/853051/52095704-e16f9400-2578-11e9-9a54-24362afffda6.png)

Fixed:

![image](https://user-images.githubusercontent.com/853051/52095718-ef251980-2578-11e9-9004-abaa26f52fde.png)
