### ISSUE TITLE
Restore national forests at zoom 7

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1801]
Looks like #1608 removed national forest icons at zoom 7 (they're only included at zoom 8+ now).

Let's restore them, please!

7/40.470/-121.491

<img width="787" alt="screen shot 2019-01-22 at 16 26 16" src="https://user-images.githubusercontent.com/853051/51574433-9790fa80-1e62-11e9-893d-f0ac20db6fa6.png">

8/40.470/-121.491

<img width="1029" alt="screen shot 2019-01-22 at 16 26 08" src="https://user-images.githubusercontent.com/853051/51574434-9790fa80-1e62-11e9-8ee9-4e39851ae669.png">

**Comment by zerebubuth** [comment]
Ooops, sorry! I thought the `not-national-park` rule in https://github.com/tilezen/vector-datasource/issues/1608#issuecomment-424153934 was saying "if the feature has a name and the name does not contain either 'National Park' or 'National Monument' then do not display below zoom 8". I've re-enabled zoom 7 for national forest POIs in #1802.

**Comment by nvkelso** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/853051/52095850-838f7c00-2579-11e9-9215-05fd6d5fa9de.png)
