### ISSUE TITLE
Don't include deprecated WOF neigbourhoods (stale dump)

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1808]
* **What did you see?** `Tenderloin` neighbourhood label is visible in NYC.
* **What did you expect to see?** This label shouldn't be visible, it's been [deprecated in WOF](https://spelunker.whosonfirst.org/id/85869725/) upstream from 2018.
* **What map location are you having problems with?** Tenderloin label near Herald Square in New York City.
    - http://tangrams.github.io/bubble-wrap/#16/40.7518/-73.9849
* **Screenshot?** 
![image](https://user-images.githubusercontent.com/853051/51857742-dfdb6d00-22e7-11e9-9da4-b0cdc9b5dadb.png)

**Comment by nvkelso** [comment]
![image](https://user-images.githubusercontent.com/853051/51857876-334dbb00-22e8-11e9-8303-8bca4d60fe85.png)

**Comment by zerebubuth** [comment]
We do [support the `edtf:deprecated` tag](https://github.com/tilezen/tilequeue/blob/146dfbe0fcac645ffaf9ea9c79bfe90831f8d1df/tilequeue/wof.py#L329), so the problem could either be a bug or that the WOF dump we're using is older than the deprecation was added to the record.

**Comment by nvkelso** [comment]
Where is the WOF dump configured?

**Comment by zerebubuth** [comment]
It's just a [static dump](https://github.com/tilezen/tileops/blob/d7365f947156001328f4cd26753965126c14ee43/import/import_planet.sh#L169-L171) that we download and restore as part of `tileops`. Headers on the dump suggest it was last updated around 12 Apr 2018, although it's possible it might be older than that.

**Comment by nvkelso** [comment]
We should update the dump, then? Or really try for a "last good" distribution from WOF on DB setup?

Was it on a regular chron before, but then switching to RAWR tiles we just dump'd instead of doing a live load off the WOF distributions on DB setup?

See also:

- https://dist.whosonfirst.org/sqlite/
- https://dist.whosonfirst.org/sqlite/whosonfirst-data-latest.db.bz2

**Comment by zerebubuth** [comment]
Yes, we used to have an automatic update process for WOF which ran on a schedule, the same way we were updating with diffs from OSM. Setting up a database from scratch was still a manual and difficult process for both OSM and WOF. When we moved to the global build, we automated the OSM part of that, but left the WOF setup for later.

In the meantime, it looks like the WOF data has become much easier to consume, so we might want to look at automating the import of the latest data.

**Comment by nvkelso** [comment]
See also: https://github.com/tilezen/tilezen-tasks/issues/4 and https://github.com/tilezen/vector-datasource/issues/1358

**Comment by nvkelso** [comment]
WOF = Who's On First for future SEO

**Comment by nvkelso** [comment]
Working.
