### ISSUE TITLE
[REPEAT 2] Boundaries layer features tagged maritime_boundary = 1 in error

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1811]
This happened again in dev, reopening into v1.7 milestone.

_Originally posted by @nvkelso in https://github.com/tilezen/vector-datasource/issues/1726#issuecomment-459565580_

While QA'ing https://github.com/tilezen/vector-datasource/issues/1770:

**Bad news:** Looking at the original report area (near 16.65/48.99711/-121.74050, e.g: in tile 512/all/15/5303/11253), I no longer see any country boundaries. 

Digging a bit more, if I disable the client-side water boundary filter, then they are restoring. Meaning https://github.com/tilezen/vector-datasource/issues/1726 has cropped up again? I'll reopen that into this milestone :\

![image](https://user-images.githubusercontent.com/853051/52095541-2c3cdc00-2578-11e9-8f5c-77a2b664f77a.png)

![image](https://user-images.githubusercontent.com/853051/52095463-d0725300-2577-11e9-9deb-7dea69ca54f1.png)

**Comment by zerebubuth** [comment]
I think I have a fix for this in https://github.com/tilezen/tilequeue/pull/367 - was a bug I introduced in https://github.com/tilezen/tilequeue/pull/362.

**Comment by nvkelso** [comment]
Working
