### ISSUE TITLE
Aerodrome polygons over aeroways

### ISSUE THREAD

**Issue by bcamper** [tilezen/vector-datasource#1814]
* **What did you see?**

`aerodrome` polygons have a higher `sort_rank` than `aeroway` features (runways, taxiways, etc.). This causes the aeroways to be hidden.

* **What did you expect to see?**

Aeroways rendered over aerodromes.

* **What map location are you having problems with?** _City and country are helpful, as well as tile coordinates or latitude / longitude._  

#14.750063185324565/40.64191771698365/-73.77976573047053

* **Screenshot?** _Props for animated gifs._

See JFK airport (verified at SFO as well):

Default view:
![jfk-aerodrome](https://user-images.githubusercontent.com/16733/52185721-5b5d8280-27f0-11e9-94eb-52aa0315118f.png)

With landuse layer disabled, to show aeroways:
![jfk-runways](https://user-images.githubusercontent.com/16733/52185725-66181780-27f0-11e9-8a34-bfe45449ddee.png)

**Comment by nvkelso** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/853051/52752946-922e5800-2fa9-11e9-8856-efb7cfa76eb9.png)

![image](https://user-images.githubusercontent.com/853051/52752960-a1150a80-2fa9-11e9-9a0b-da2cdb1db04d.png)
