### ISSUE TITLE
Update osmdata.com water and land polygons

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1832]
We should make this part of every release as a checklist, until it's automated in #516.

**Comment by zerebubuth** [comment]
Fixed in #1820 - I just checked and the static assets bundle includes osmdata.com shapefiles from 4th Feb 2019, so it'll be in the next build.

Agree it should be a much more regular process than it is now. Do we have a release checklist to add it to?

**Comment by nvkelso** [comment]
Added release checklist making in https://github.com/tilezen/vector-datasource/issues/1834.
