### ISSUE TITLE
Add more kind:* POV from Natural Earth for low zooms and places layer

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1840]
_Originally posted by @nvkelso in https://github.com/tilezen/vector-datasource/issues/1552#issuecomment-463516835_

There's also work to add this in from the Natural Earth 1:50M and 1:110M scale sets (we've only added from 1:10M set in v1.7)... and from `populated_places` and `states_provinces` as some country and region capitals aren't recognized, and some regions aren't recognized.

This issue tracks integrating that data.

**Comment by nvkelso** [comment]
Sister issue to OSM data in #1810.

**Comment by nvkelso** [comment]
Nearterm, I'll prototype a sample data change in the 1:10m populated_placeas and region boundary lines, and same samples in the 1:110m and 1:50m scale sets to unblock Tilezen work. Then we'll do one other asset build once the final NE data is ready.

**Comment by nvkelso** [comment]
Prototype data:

- [ne_v5.0.0-pre3-boundaries-pov.zip](https://github.com/tilezen/vector-datasource/files/3083549/ne_v5.0.0-pre3-boundaries-pov.zip)

Notes: 

- All themes included here have the additional POV columns with the same naming schema.
- Some themes, like 1:50m and 1:110m state and province boundary lines include the schema but none of the line features are disputed so those columns are entirely blank. But there are requests to add that data for India and China so let's plumb it in here to future proof.
- The 1:10m state and province boundary lines _does_ include sample data for India, China.
- The populated places in Taiwan include the placetype swapping (eg country capital goes to region capital, and region capitals go to generic localities)
- The 1:50m and 1:110m international boundaries files have been updated with sample data.
- More work remains to flesh out the column values completely, but these are good sample to unblock development.

Flagging @zerebubuth for integration work.

**Comment by nvkelso** [comment]
Noting we should rename **kind** `unrecognized` to `unrecognized_country` so we can also support `uncrecognized_region`. 

Under our SemVer we can rename a recently added kind as a Patch release, but let's just bundle it in this minor update.

**Comment by nvkelso** [comment]
I've done more data work and need to post a new preview ZIP.

**Comment by nvkelso** [comment]
Here's v5.0.0-pre-4 with more detail filled out (not just samples) for the other themes, and some fixes in the 1:10m themes:

- [ne_v5.0.0-pre4-boundaries-pov.zip](https://github.com/tilezen/vector-datasource/files/3185025/ne_v5.0.0-pre4-boundaries-pov.zip)

Still needs more QA, but is close.

**Comment by nvkelso** [comment]
We're missing data / modeling around Cyprus, followup here: https://github.com/tilezen/vector-datasource/issues/1898.

**Comment by nvkelso** [comment]
For Crimea we should also support `FCLASS_UA` (since Ukraine is primary claimant with Russia there). I'll update Natural Earth and provide new file here.

![image](https://user-images.githubusercontent.com/853051/58600847-1051fa00-823b-11e9-95af-e8eee041f54d.png)

**Comment by nvkelso** [comment]
I'm not sure why most of the India - Pakistan boundary is coming thru as `kind:cn` of `line_of_control` as the data I see in my source copy of NE says it should just be basic `country` boundary – that POV shouldn't be exported in tiles for that boundary as no one disputes it:

![image](https://user-images.githubusercontent.com/853051/58601136-64a9a980-823c-11e9-91f8-29b644075ac2.png)

**Comment by nvkelso** [comment]
Similarly this `disputed` boundary is considered as `country` by Russia, China, and Pakistan, and is `unrecognized_country` by India in source Natural Earth data but those are all missing in this tile build - the red line between Kashmir and China:

![image](https://user-images.githubusercontent.com/853051/58601204-ab979f00-823c-11e9-8ae5-d59e85753142.png)

**Comment by nvkelso** [comment]
Missing gaps between China and India, Bhutan at low zooms (fine and mid-zoom from NE 1:10m see 4/31.58/82.53)

![image](https://user-images.githubusercontent.com/853051/58601468-b7d02c00-823d-11e9-85fc-349c30c5cf46.png)

**Comment by nvkelso** [comment]
I also need to plumb thru `unrecognized_*` versus the simpler `unrecognized` in NE and Tilezen logic needs to update.

**Comment by zerebubuth** [comment]
This is what I see in the `ne_50m_admin_0_boundary_lines_land.shp` shapefile from the `ne_v5.0.0-pre4-boundaries-pov.zip` NE pre-release:

![image](https://user-images.githubusercontent.com/271360/58624465-3671ab80-82c8-11e9-91a9-c9eee42e2a60.png)

Possibly it's just a typo? I don't see the same `FCLASS_CN` in the 1:10m version of the file.

**Comment by nvkelso** [comment]
Looks like POV for NE admin-1 region lines isn't fully wired up?

Here we see India's POV, but the Xinxang region line is still showing up inside of India's claim area:

![image](https://user-images.githubusercontent.com/853051/58676024-a8b7af80-830b-11e9-9a7d-bf011bebcb60.png)

![image](https://user-images.githubusercontent.com/853051/58675993-86259680-830b-11e9-85bd-41fb2c938691.png)

**Comment by nvkelso** [comment]
Same with China / India border in the east:

![image](https://user-images.githubusercontent.com/853051/58676078-d3096d00-830b-11e9-843c-064c189d47ae.png)

![image](https://user-images.githubusercontent.com/853051/58676066-c8e76e80-830b-11e9-9be4-39cd1193e73a.png)

**Comment by nvkelso** [comment]
This needs a new NE data asset bundle and fixes for POV on `region` lines.

**Comment by nvkelso** [comment]
Here's Natural Earth v5.0.0-pre5:

- [ne_v5.0.0-pre5-boundaries-pov.zip](https://github.com/tilezen/vector-datasource/files/3239842/ne_v5.0.0-pre5-boundaries-pov.zip)

**Comment by nvkelso** [comment]
@zerebubuth Can you look at https://github.com/tilezen/vector-datasource/issues/1840#issuecomment-497545789 again? I still don't see the POV wired up on NE sourced `region` lines.

**Comment by nvkelso** [comment]
There's also this oddness around zoom 2 where all the Kashmir lines go missing for some POV (they're in zoom 3). But looking at the data it's because those are POV "assertion" lines that need a lower min_zoom when they are part of a POV, even though normally we wouldn't want to see them that early. The easiest fix now is to revise their min_zoom.

<img width="241" alt="Screen Shot 2019-06-06 at 18 20 43" src="https://user-images.githubusercontent.com/853051/59075874-d2cb1d80-8887-11e9-89a2-3ab051354473.png">

**Comment by nvkelso** [comment]
I've verified https://github.com/tilezen/vector-datasource/pull/1904, which resolves all outstanding code change requirements.
