### ISSUE TITLE
Remove alias in tilequeue source lookup for openstreetmapdata.com

### ISSUE THREAD

**Issue by zerebubuth** [tilezen/vector-datasource#1859]
We treat `openstreetmapdata.com` and `osmdata.openstreetmap.de` the same way when determining a `Source` for a feature. This helps to guard against using the new code with older RAWR tiles and cached test data, both of which have the value baked-in. I think we should probably leave this in until we've done a few builds and remove it before the 1.8.0 release.

_Originally posted by @zerebubuth in https://github.com/tilezen/tilequeue/pull/372/review_comment/create_

**Comment by nvkelso** [comment]
See:

- https://github.com/tilezen/tileops/blob/d8fcfa14f5ec15718a4cf0b071de3bc4db966089/docker/meta-batch/config.yaml#L44
- https://github.com/tilezen/tileops/blob/d8fcfa14f5ec15718a4cf0b071de3bc4db966089/docker/rawr-batch/config.yaml#L24

**Comment by nvkelso** [comment]
@zerebubuth We've had a successful build, time to remove the alias before we cut release?
