### ISSUE TITLE
Defunct Tenderloin neighbourhood displays in NYC

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1869]
Related to https://github.com/tilezen/vector-datasource/issues/1808.

* **What did you see?** This `Tenderloin` neighbourhood in NYC has been deprecated / not current in WOF since 2016, but is included in 2018-2019 builds of Tilezen.
* **What did you expect to see?** Not current, deprecated neighbourhoods should be excluded from the build.
* **What map location are you having problems with?** _City and country are helpful, as well as tile coordinates or latitude / longitude._  
    - https://tangrams.github.io/refill-style/#15/40.7506/-73.9809
    - https://github.com/whosonfirst-data/whosonfirst-data/blob/master/data/858/697/25/85869725.geojson
* **Screenshot?** 

<img width="1207" alt="Screen Shot 2019-04-12 at 13 46 04" src="https://user-images.githubusercontent.com/853051/56065423-a4b6da80-5d29-11e9-8b48-8075d9c1ccf0.png">

**Comment by nvkelso** [comment]
By updating the WOF build via #1808 I initially thought we'd remove the bad Tenderloin label, but it's been deprecated for such a long time there might be an additional logic error related to processing `mz:is_current`.

**Comment by zerebubuth** [comment]
I loaded up the WOF data locally to check, and got this result:

```
# select is_visible from wof_neighbourhood where wof_id = 85869725;
 is_visible 
------------
 f
(1 row)
```

If `is_visible` is false, that should mean it gets selected by neither the [query code in vector-datasource](https://github.com/tilezen/vector-datasource/blob/472f9c05e453b2688b9b4235ef4fd027fa564d76/queries/wof.jinja2#L27) nor the [query code in raw-tiles](https://github.com/tilezen/raw_tiles/blob/d2fea18946cb4ac3166bc808683c266daa6eb916/raw_tiles/source/wof_neighbourhood.sql#L22). However, to be sure, we'll have to wait for the latest build to finish.

Although the property `edtf:deprecated: 2016-08-16` suggests deprecation in 2016, it looks like the WOF record was last modified on 2018-05-25. The WOF `pgdump` we store on S3 says `Last-Modified: Wed, 14 Mar 2018`, which is before the WOF record was last changed. I'm not sure how to check the previous versions of a WOF record, but it seems possible that the deprecated date was modified after the last static dump we created.

**Comment by nvkelso** [comment]
Hard to say, even looking at the blame:

- https://github.com/whosonfirst-data/whosonfirst-data/blame/master/data/858/697/25/85869725.geojson

Let's wait for a new build before researching anymore :)

**Comment by nvkelso** [comment]
No longer in dev build, closing.
