### ISSUE TITLE
Backfill kind_detail on aerodromes based on iata codes

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1873]
In https://github.com/tilezen/vector-datasource/issues/1277 we added `kind_detail` for aerodrome landuse (AOI), pois, and roads (runway) layers features. But it turns out `aerodrome:type` isn't very consistently filled in. We want to use this property to filter features at low zooms – there are a medium amount of not international airports at the low and mid-zooms that are large but not meaningful to show that early. 

* **What did you see?** I saw `public` on SFO airport south of San Francisco, California, USA.
* **What did you expect to see?** I expected to see `international`, based on it having a 3-char IATA code (SFO)
* **What map location are you having problems with?** 15/37.6201/-122.3775
* **Screenshot?** 

It is on the landuse:

![image](https://user-images.githubusercontent.com/853051/56513933-cb72cf00-64e8-11e9-9fa2-23c41a560df9.png)

It is passing to the POI:

![image](https://user-images.githubusercontent.com/853051/56513707-25bf6000-64e8-11e9-8d62-7b5da9ddd6c1.png)

I expect the runway lines to also have a `aerodrome_kind_detail` property via https://github.com/tilezen/vector-datasource/pull/1854:

![image](https://user-images.githubusercontent.com/853051/56513903-b72ed200-64e8-11e9-9207-c2862c3099ad.png)

**Comment by zerebubuth** [comment]
> I expected to see `international`, based on it having a 3-char IATA code (SFO)

Would you also expect to see `international` for [Arrabury Airport](https://www.openstreetmap.org/node/1042093163)? Although it has a 3-char IATA code (AAB), it looks like it only serves a [remote cattle station](https://en.wikipedia.org/wiki/Arrabury) and I'd be quite surprised if it serves any international routes. Although it does have 2 runways, from aerial imagery it looks like neither are paved.

Perhaps we could use this [list of international airports](https://en.wikipedia.org/wiki/List_of_international_airports_by_country) to override `public` → `international`?

**Comment by nvkelso** [comment]
Huh, that's odd! Maybe it's got an IATA code because it's an emergency landing strips for international flights that need a quick landing spot in the middle of the outback?

Rather than relying on an external list... what about allowing the OSM tags to drive this?

In this proposal, since the [Arrabury Airport](https://www.openstreetmap.org/node/1042093163) doesn't have an `aerodrome:type` tag, we'd default it because of the `iata` value being present to **kind_detail** of `international`... but that can be fixed by adding an `aerodrome:type` tag of [`airfield`](https://wiki.openstreetmap.org/wiki/Tag%3Aaerodrome%3Atype%3Dairfield). Which is admittedly confusing since we generally use `airfield` in Tilezen's **kind** to indicate a _military_ use, while this **kind_detail** use would be for rural airstrips.

Alternatively, we could opt to only do the backfill when the airport has a polygon? Because Arrabury is a node it'd fail that test.

**Comment by zerebubuth** [comment]
[Bunbury airport](https://www.openstreetmap.org/way/123414925) has a polygon, `aerodrome:type=public` and `iata=BUY`, although the [Wikipedia entry](https://en.wikipedia.org/wiki/en:Bunbury%20Airport) says it has no control tower and seems to suggest that it's mainly for flying clubs and light aircraft.

Bunbury has a `aerodrome=regional` tag, which we could use for excluding it (although I'm not convinced it's really a regional airport - seems more like an airfield).

However, [Kerang airport](https://www.openstreetmap.org/way/133341451) has no tags which obviously exclude it from being an international airport. It has `iata=KRA` and `aerodrome:type=public`, but a look at the aerial imagery suggests that it probably lacks the facilities to do international immigration / customs checks (I don't see a terminal building).

I'm not sure that simply _having_ an IATA code indicates that an airport is of international importance.

I agree that it would be better to drive this from OSM tags, but it seems like `aerodrome:type` is just totally inconsistent. We could fix the data by looking at the airports that the external list says should be `aerodrome:type=international` but currently aren't and double-checking them.

There are 913 such airports, according to my researches (probably not all of them are indeed international airports) and most (484) are simply lacking `aerodrome:type`. A further 306 are tagged as `public` and the rest are a mix of `military/public`, `civil`, `regional`, `military`, etc...

Ironically, a small number of airports tagged `aerodrome:type=regional` are actually called something "international", e.g: [General Santos International Airport](https://osm.org/way/303726565) - although a look at [Wikipedia](https://en.wikipedia.org/wiki/en:General%20Santos%20International%20Airport) suggests it no longer has any scheduled international routes, but operates as a diversion alternative for nearby international airports.

**Comment by nvkelso** [comment]
@zerebubuth can you take another pass at this, please?

![image](https://user-images.githubusercontent.com/853051/57431663-5db4eb80-71e8-11e9-9f9d-2b83131562cc.png)

But I was expecting `international` as well on the runways:

![image](https://user-images.githubusercontent.com/853051/57431694-73c2ac00-71e8-11e9-80d9-7da84e3e9621.png)

I think that's not right because the POIs logic needs to be applied also to the landuse polygon?

![image](https://user-images.githubusercontent.com/853051/57431727-8dfc8a00-71e8-11e9-9112-03652b82f5da.png)

**Comment by zerebubuth** [comment]
> I think that's not right because the POIs logic needs to be applied also to the landuse polygon?

Ooops! Well spotted, thanks. Looks like I meant to apply the same logic to polygons, but just forgot.  Should be fixed in #1893.

**Comment by nvkelso** [comment]
This is working on landuse polygons for runways, woot!

Noting here that we don't include this for `runway` lines or `taxiway` lines in the **roads** layer, but that's fine – those aren't shown at mid zooms and it's the mid-zooms that are most important to solve.

![image](https://user-images.githubusercontent.com/853051/58597835-9c115980-822e-11e9-8870-89bf981bcf5e.png)
