### ISSUE TITLE
Missing capital POV from NE for region at high zooms

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1906]
* **What did you see?** Region capitals in Taiwan aren't getting any POV properties at high zooms.
* **What did you expect to see?** Those should be included by joining from OSM to NE via Wikidata_ID values. That seems to be working for country capitals, but not region capitals.
* **What map location are you having problems with?** Taiwan
* **Screenshot?** 

Low zoom from Natural Earth:
<img width="299" alt="Screen Shot 2019-06-12 at 16 51 38" src="https://user-images.githubusercontent.com/853051/59393948-9dfd1180-8d32-11e9-9d98-56729324cb1e.png">

High zoom from OSM missing NE POV properties:
<img width="293" alt="Screen Shot 2019-06-12 at 16 54 03" src="https://user-images.githubusercontent.com/853051/59393966-b53bff00-8d32-11e9-9c33-de2cf01b95d8.png">

**Comment by nvkelso** [comment]
@zerebubuth can you take a look, please?

**Comment by nvkelso** [comment]
OSM node: 

- https://www.openstreetmap.org/node/60655918
    - doesn't have `state_capital` property
    - does have Relation Taichung (2921154) (as `admin_centre`)

**Comment by travisgrigsby** [comment]
@nvkelso can you list which of the properties that aren't making it in to the high zoom should be?  
I see `region_capital`, `region_capital:cn` that seem obviously missing and related, but then I also see a lot of name differences due to the different data sources providing the properties.  

One that may be important is, in the low zoom, the `name:zh` field has a value with 1 less char than in the high zoom.  Is this relevant? Anything else?

**Comment by travisgrigsby** [comment]
A lot of this can be modeled off the description here: #2020 
Basically, add a join query like in `functions.sql`, call it to pull the data into the properties that vector datasource sees, then make sure they're exported (probably in `places.yaml`)

**Comment by travisgrigsby** [comment]
Nm looks like this was already committed.

**Comment by peitili** [comment]
does that mean we can close this issue?

**Comment by travisgrigsby** [comment]
not sure yet!

**Comment by nvkelso** [comment]
Yes, we can close this issue. It should have been closed in 2019 via https://github.com/tilezen/raw_tiles/pull/34 and https://github.com/tilezen/vector-datasource/pull/1907.
