### ISSUE TITLE
Shield text version of ref

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#192]
By [adding the network tags](https://github.com/mapzen/vector-datasource/issues/121) from the relations onto features we know, for instance, that a way for "US 101" is network "US:US" and should have use US Route style artwork. But we can't shove the ref value into the shield's text straight because it duplicates "US ". 

Two options:

* We modify the ref to strip out values like "US ", but this a destructive change and might impact other users of the data, especially non-Tangram users.

* We create a new shield text property and store the result there.

**Comment by zerebubuth** [comment]
Is it possible to add a third option: filter the prefix out of the ref client-side? It seems like it's something that would be style-dependent anyway: If you wanted to render a plain, non-specialised shield then you'd want to see "US 101", as it's the shield symbol itself which tells you it's a "US-" road, and it's the style which determines what shield will be rendered?

**Comment by nvkelso** [comment]
See also: #896.

**Comment by bcamper** [comment]
While it's possible to process the `ref` client-side with regex/JS string operations and we can prototype it this way (and always preserve that option for people who want flexibility), I think it is worth having a server-side provided "shield text" field to avoid this work client-side (both to avoid the cost of all those regexes client-side and to support renderers that don't have this ability).

**Comment by nvkelso** [comment]
We already calculate the shield type and export that as the `network` property on roads (see "mz_get_rel_network" in **functions.sql** . We need to iterate over all the route relations, not just the first one (export multiple with `;` separator?), and do some regEx to pull out the shield text part of the "name" and export that in a new property.

**Comment by nvkelso** [comment]
See also: http://www.openstreetmap.org/user/Minh%20Nguyen/diary/39123

**Comment by nvkelso** [comment]
💯 This is super cool, and verified :)

**Comment by nvkelso** [comment]
Clarified documentation in 7112bf1c22c4f1a76755cae8b2442ebef1e09590.

**Comment by nvkelso** [comment]
Reopening as I'm seeing many cases in Europe where the `shield_text` is **A ##** or **M ##** or **N ##** or **E ##** (there may be others) with a space between the leading character and the numbers, which impacts artwork creation on the spritesheet side & matching logic in Tangram scene files. 

**There shouldn't be a 2nd char space in the `shield_text` values (but the leading character seems convention to keep).**

Examples:

- E road: 
  - http://tile.dev.mapzen.com/vector/v1/all/9/257/174.topojson
  - http://tile.dev.mapzen.com/vector/v1/all/9/254/170.topojson (even though ref says M...)
- A road: 
  - http://tile.dev.mapzen.com/vector/v1/all/10/518/351.topojson

<img width="290" alt="screen shot 2016-09-07 at 23 34 31" src="https://cloud.githubusercontent.com/assets/853051/18339372/0ac01d5c-7554-11e6-8b92-1c6fc4716eed.png">

<img width="302" alt="screen shot 2016-09-07 at 23 34 14" src="https://cloud.githubusercontent.com/assets/853051/18339373/0afcf1f0-7554-11e6-81f3-8369e58f52c5.png">

**Comment by bcamper** [comment]
I'm also trying to find the example again, but I've seen cases where the `shield_text` has a value like "90 Truck" -- my understanding was the text wouldn't include a second word like that.

**Comment by zerebubuth** [comment]
Just to check, do you want:

* [SR70var1](http://www.openstreetmap.org/relation/449595) to have a `shield_text` of "70var1"?
* [CTH J](http://www.openstreetmap.org/relation/4010101) to have a `shield_text` of "J"?
* [Purple Belt](http://www.openstreetmap.org/relation/544634) to have no `shield_text`?
* [Т-02-16](http://www.openstreetmap.org/relation/1296750) to have a `shield_text` of "02-16"?
* [FI-PI-LI](http://www.openstreetmap.org/relation/1587534) to have no `shield_text`?
* [CR 315A](http://www.openstreetmap.org/relation/2564219) to have a `shield_text` of "315A"?
* [ΕΟ1α](http://www.openstreetmap.org/relation/5641878) to have a `shield_text` of "1α"?

In the case where there's no shield text, would it be better to drop the entry entirely, or have a blank or null `ref`?

**Comment by zerebubuth** [comment]
Oh, and [SD 37 Truck (Huron, SD)](http://www.openstreetmap.org/relation/5903811) to have a `shield_text` of "37" or "37 Truck"?

**Comment by zerebubuth** [comment]
[CTH PV](http://www.openstreetmap.org/relation/5179634)? I'm starting to think that someone's making these up just to complicate figuring out what the `shield_text` should be!

**Comment by nvkelso** [comment]
Responding to examples:

* [SR70var1](http://www.openstreetmap.org/relation/449595) to have a `shield_text` of "70var1"? **YES**, `70var1`.
* [CTH J](http://www.openstreetmap.org/relation/4010101) to have a `shield_text` of "J"? **YES**, `J`.
* [Purple Belt](http://www.openstreetmap.org/relation/544634) to have no `shield_text`? **NO**, I expect `Purple Belt`.
* [Т-02-16](http://www.openstreetmap.org/relation/1296750) to have a `shield_text` of "02-16"? **NO**, I expect `Т0216`.
* [FI-PI-LI](http://www.openstreetmap.org/relation/1587534) to have no `shield_text`? **NO**, I expect `FI-PI-LI`.
* [CR 315A](http://www.openstreetmap.org/relation/2564219) to have a `shield_text` of "315A"? **YES**, `315A`.
* [ΕΟ1α](http://www.openstreetmap.org/relation/5641878) to have a `shield_text` of "1α"? **NO**, I expect `ΕΟ1α`. This one is a little odd, there is a correctly ref'd `A1` that parallels the route you link to. But suggest not special casing this for now.
* [SD 37 Truck (Huron, SD)](http://www.openstreetmap.org/relation/5903811) to have a `shield_text` of "37" or "37 Truck"? **37**
* [CTH PV](http://www.openstreetmap.org/relation/5179634)? I'm starting to think that someone's making these up just to complicate figuring out what the `shield_text` should be! **PV**

> In the case where there's no shield text, would it be better to drop the entry entirely, or have a blank or null `ref`?

If the OSM `network` is provided but there is no OSM `ref` value to populate the Tilezen `shield_text` with, I think the Tilezen `network` should still be exported with a null Tilezen `shield_text` value (but not export Tilezen `ref` at all). I think this would be more consistent treatment for the **all** multi-variants.

**Comment by nvkelso** [comment]
Regarding comment in in https://github.com/tilezen/vector-datasource/issues/192#issuecomment-245509369: 

Is #1039 stripping off all leading `A ` characters from strings like `A 100` resulting in just `100` in the shield text instead of `A100`?

**Comment by nvkelso** [comment]
@zerebubuth for above comment.

**Comment by zerebubuth** [comment]
That should be the behaviour. There's a [couple of examples](https://github.com/tilezen/vector-datasource/blob/v1.0.0-pre3/test/test_transform.py#L561-L568) in the tests. Have you found an example where that's not happening?

**Comment by nvkelso** [comment]
Drrr, we got our wires crossed for https://github.com/tilezen/vector-datasource/issues/192#issuecomment-245509369, and I didn't catch it in the review (sorry!). 

The leading character should be kept for E-road and A-road examples – it's the 2nd space character that should be dropped.

But looking at TagInfo these aren't commonly tag'd in Europe so I think this is a v1.1 cleanup task, not a v1.0 ship block. Filed: https://github.com/tilezen/vector-datasource/issues/1062.

**Comment by nvkelso** [comment]
Spot checked most of these, looking good!
