### ISSUE TITLE
admin_level odd values not included

### ISSUE THREAD

**Issue by rwrx** [tilezen/vector-datasource#1933]
Hello, I would like to kindly ask you something related to the tag admin_level.
In the Vector-datasource https://github.com/tilezen/vector-datasource/blob/1485de82a4d7b733b3d314e89078548e9a056f1c/yaml/boundaries.yaml the tag admin_level which is transformed into kind_detail has values: 2, 4, 6 and 8. Why there are used only even numbers for this tag’s values? In OSM you can see that there are also values with odd numbers, like 9.

![screenshot](https://user-images.githubusercontent.com/2378743/66926689-c5d8ea80-f02e-11e9-99ee-7055c115984e.png)

**Comment by nvkelso** [comment]
This is a complicated topic, see a HUGE table in the OSM Wiki which details which levels are used in which countries:

- https://wiki.openstreetmap.org/wiki/Tag:boundary%3Dadministrative#10_admin_level_values_for_specific_countries

Generally speaking the "even" (2, 4, 6, 8) levels are common, and the "odd" (3, 5, 7, 9) levels are not common and vary largely by country. A minority of countries are modeled with 11 admin_levels while most are modeled with 10 (but in practice only 3 to 4 are filled in with data).

We're not opposed to adding more of them... but we need to solve specific problems. It's rare to label these lines on a map so even the current supported admin_levels could be considered excessive compared to their real world map display usage.

**Comment by rwrx** [comment]
Thank you a lot for the explanation. I will close this issue.
