### ISSUE TITLE
Introduction of network to traffic_flow and traffic_incidents

### ISSUE THREAD

**Issue by conor-ettinoffe-here** [tilezen/vector-datasource#1935]
Hi,

We are looking at using the attribute `network` from the [Road Layer Network Values](https://github.com/tilezen/vector-datasource/blob/master/docs/layers.md#roads-layer-network-values) value in the `traffic_flow` and `traffic_incidents` layer when `linear_ref_id` is unavailable as it has become apparent that one may want to stylize traffic based on its country.

Would this be acceptable for one to add this as an optional property of the two layers as such:

`network`: 2-character country code and optional region (eg. `DE:Berlin`) of the traffic information (See: [Road Layer Network Values](https://github.com/tilezen/vector-datasource/blob/master/docs/layers.md#roads-layer-network-values))

Thanks in advance :slightly_smiling_face:

**Comment by nvkelso** [comment]
Yes, that works with me as an optional property. The `network` value should match what's in the road layer for that road segment.

**Comment by conor-ettinoffe-here** [comment]
Thanks @nvkelso , created a PR :slightly_smiling_face:

**Comment by nvkelso** [comment]
Closed via https://github.com/tilezen/vector-datasource/pull/1936.
