### ISSUE TITLE
Add new axles hgv_restriction

### ISSUE THREAD

**Issue by Nazariii** [tilezen/vector-datasource#1937]
Hi

We have faced with the case when there is the hgv restriction on axles counts without weight specified. 

Would it be acceptable to add new hgv_restriction: `axles` to the roads layer that will represent a restriction on axle number?

Thanks

**Comment by nvkelso** [comment]
Sounds reasonable – I see that on road signs on my travels. Can you submit a PR, please?

**Comment by Nazariii** [comment]
Thanks @nvkelso, created a PR

**Comment by nvkelso** [comment]
Merged, thanks!
