### ISSUE TITLE
Can't see osm data on map

### ISSUE THREAD

**Issue by cyfugr** [tilezen/vector-datasource#1943]
I do not see data on the maps like country name, building names etc.

I expected to see text describing thr data.

 I have created a db with cyprus extract from osm, i went throught the wiki tutorial and i can see the map but i dont see any text, i am using vector_datasource?v1.8.0 and tileserver?v2.2.0 i am accessing the map throguht tangram hitin `host/all/8/153/101.mvt` endpoint 

<img width="825" alt="Screenshot 2020-09-16 at 17 07 54" src="https://user-images.githubusercontent.com/13256398/93348672-2ecc7200-f83f-11ea-9811-294c1341840b.png">

**Comment by nvkelso** [comment]
Hi Anything to document to make setup easier for other folks now that you got it working?

**Comment by cyfugr** [comment]
@nvkelso The document was pretty straight forward, the fix for this issue is on tangram side, i had to specify the admin names etc. Although i am now trying to get into the tileque and rawr because it's slow to work with tileserver but there isnt a document like the `vector-datasource` for tileque and its pretty confusing.

**Comment by nvkelso** [comment]
See also:

- https://github.com/tilezen/tileops

Particularly the cron.py script there.

**Comment by cyfugr** [comment]
@nvkelso will it work without AWS at all?

**Comment by nvkelso** [comment]
The scaled global build does rely on AWS services.

The earlier manual approach with tilequeue does still work, but I suggest you'd want to pre-cache a list of your popular tiles (or use OSM's popular tile list as a seed).

**Comment by cyfugr** [comment]
Thank you, if and when get my head around it I will make a document to explain how to set up tileque in detail and make an MR

**Comment by cyfugr** [comment]
@nvkelso is there are tool or code to pre-cache high zoom levels in redis or file?

**Comment by nvkelso** [comment]
See the `seed` section in Tilequeue:

- https://github.com/tilezen/tilequeue#running

**Comment by cyfugr** [comment]
Hi, i have made the config by tileque and i am running it, it throws an error `'Missing queue-mapping configuration'` not sure what this means

**Comment by rmarianski** [comment]
Do you have the [queue-mapping](https://github.com/tilezen/tilequeue/blob/752daf1fdb1426ac12a50ed754426a3b029e2fd3/config.yaml.sample#L9-L24) section in your config?
