### ISSUE TITLE
Add disputed boundary for South China Sea

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1983]
China's disputed claim in the South China Sea is now available in Natural Earth v5 as a new data file and should be added to tiles as **kind** `unrecognized_country` in boundaries layer, and the **kind:cn** would be `country`, and the hard coded **min_zoom** should be `1`.

**Comment by nvkelso** [comment]
- The earlier [Natural Earth v5 preview ZIP](http://naturalearth.s3.amazonaws.com/beta/v5.0.0-pre9-boundaries-pov-chinese-pops-hydro-admin.zip) does include:
    - Relevant SHP inside that ZIP: `ne_10m_admin_0_boundary_lines_disputed_areas_chn.shp`
- Modifying the assets bundle to include the new SHP file:
    - https://github.com/tilezen/vector-datasource/blob/0a760a16ad941bc9860fc93274fc4e78d06e144b/data/assets.yaml#L177-L181
- Build a new shapefiles asset bundle and deploying on S3
- Config new tables in Postgres
    - https://github.com/tilezen/vector-datasource/search?q=ne_10m_admin_0_boundary_lines_disputed_areas
    - https://github.com/tilezen/vector-datasource/blob/024909ed8245a4ad4a25c908413ba3602de6c335/data/apply-updates-non-planet-tables.sql#L22-L28
    - https://github.com/tilezen/vector-datasource/blob/024909ed8245a4ad4a25c908413ba3602de6c335/data/apply-updates-non-planet-tables.sql#L134-L136
    - https://github.com/tilezen/vector-datasource/blob/024909ed8245a4ad4a25c908413ba3602de6c335/queries/ne-boundaries-10m.jinja2#L7-L8
    - https://github.com/tilezen/vector-datasource/blob/024909ed8245a4ad4a25c908413ba3602de6c335/data/apply-schema-update.sql#L98
- Perhaps the `ne` table reference here will just work?
    - https://github.com/tilezen/vector-datasource/blob/master/yaml/boundaries.yaml#L225-L247
   - But it's also related to https://github.com/tilezen/vector-datasource/issues/1970

**Comment by nvkelso** [comment]
@peitili let's also match **min_zoom** = `1` here with your other work.

**Comment by peitili** [comment]
> China's disputed claim in the South China Sea is now available in Natural Earth v5 as a new data file

@nvkelso how do we find the link of the `Natural Earth v5` file?

**Comment by nvkelso** [comment]
First part of this comment: https://github.com/tilezen/vector-datasource/issues/1983#issuecomment-956445860

**Comment by peitili** [comment]
![Snip20211114_5](https://user-images.githubusercontent.com/62725319/141717400-77f80c3b-3301-4ca8-912a-0772da80e1a4.png)
