### ISSUE TITLE
Add top-level-countries DBF from Natural Earth

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#2075]
The following archive:

https://naciscdn.org/naturalearth/5.1.0/housekeeping/ne_admin_0_details.zip

Includes a new table:

ne_admin_0_details_top_level_countries.dbf

That table needs to be added to Postgres as source of truth for "country-ness". Currently it's a join against the admin-0 countries table, which doesn't include all the data we want. This new file does.

**Comment by travisgrigsby** [comment]
@nvkelso I'm looking at this - may need to meet with you to figure out how to wire this in

**Comment by nvkelso** [comment]
You could load it using a tool like: https://pgloader.readthedocs.io/en/latest/ref/dbf.html

Though see my comment below about loading 2 separate shapefiles instead which pattern matches better with what we already do. 

Add it/them to the list of assets around here:

- https://github.com/tilezen/vector-datasource/blob/master/data/assets.yaml#L142-L146

You'll want to configure the extra TLC point-of-view around here:

- https://github.com/tilezen/vector-datasource/blob/734e48d74fd1b4d84f785af4cbd9074fd07574b6/queries/ne.jinja2#L2

But that assumes `fclass_tlc` is present on all related SHPs, which might not be true yet? I'll see if I need to unblock you there.

Then for the lookup for the "country" min_zoom, that's in:

- https://github.com/tilezen/vector-datasource/blob/215fd7a072b84368ce442d0480ca05a8cbffcea1/data/functions.sql#L996-L1052

Which spans across multiple tables today (across input Natural Earth themes across feature classes and kinds), which is problematic because the same Wikidata can be present in multiple tables, sometimes for the same conceptual feature and sometimes not (eg fuzzy versus strict matching) – take France for example. 

So the reason we want to load this new table is we want to get only the curated set of strict matches. 

There is an alternate way of doing this, which is to load 2 new shapefiles instead of 1 DBF, and then splitting the current function so admin-0 is treated separately from admin-1, localities & etc. For the new admin-0 it'd could be a coalesce across the ISO and TLC shapefiles instead (I'd first look in ISO, then in TLC). That should include 100% of what's in the source DBF (which is used as input for both these SHP).

- http://naciscdn.org/naturalearth/5.1.0/10m/cultural/ne_10m_admin_0_countries_iso.zip (smaller, most conservative list)
- http://naciscdn.org/naturalearth/5.1.0/10m/cultural/ne_10m_admin_0_countries_tlc.zip (larger list than ISO, but misses some ISO groupings like Palestine)

Bonus points for picking up the curated `label_x` and `label_y` properties out of those tables, as well as `fclass_iso` and `fclass_tlc`.

**Comment by travisgrigsby** [comment]
Looks like our whole shapefile bundle build expects shp files.  Adding a dbf will break a few assumptions in the process so I'm going to go with the two shp's approach

**Comment by travisgrigsby** [comment]
Reducing scope here a little for simplicilty.  Going to: 
* use the iso and tlc shp files @nvkelso mentioned above.  
* modify tz_get_min_and_max_zoom to do lookups in iso and tlc only if it's place=country or place=unrecognized, and then if it's not, look up in the admin1+ tables

**Comment by nvkelso** [comment]
Fixed via https://github.com/tilezen/vector-datasource/pull/2078.
