### ISSUE TITLE
Rename `disputed_relation_overpass_query.txt` to `disputed_relation_overpass_query.overpassql`

### ISSUE THREAD

**Issue by FloEdelmann** [tilezen/vector-datasource#2109]
`*.overpassql` is now the recommended file extension for Overpass QL: [OSM Wiki: Overpass QL § File extension](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#File_extension)
*(**Disclaimer:** I added that section after [some discussion](https://wiki.openstreetmap.org/wiki/Talk:Overpass_API/Overpass_QL#Recommended_file_extension?).)*

I propose to rename all Overpass QL files in this repo to `*.overpassql` for consistency.

Context: GitHub's syntax highlighting engine requires that 200 repositories use the same file extension before they consider supporting that syntax and file extension: https://github.com/github/linguist/issues/5890

**Comment by FloEdelmann** [comment]
@peitili Would a pull request be accepted?

**Comment by peitili** [comment]
Do you have an example file in the repo to be renamed?

**Comment by FloEdelmann** [comment]
It's only one file: https://github.com/tilezen/vector-datasource/blob/master/scripts/disputed_relation_overpass_query.txt

**Comment by peitili** [comment]
@nvkelso @iandees @travisgrigsby what do you think?

**Comment by nvkelso** [comment]
@FloEdelmann Thanks for the suggestion! Yes we'll gladly take a PR. Ideally we do that this week as I'm about to tag the v1.9 release :)

This file is also referenced in [docs/disputed-features.md](https://github.com/tilezen/vector-datasource/blob/034ac5f16ddfb7c7fb51f4beebc8f6d661e94063/docs/disputed-features.md), so a PR should both change the name of the script and change the documentation that names and links to the script.

For those curious... The manually run script (proposed for a name change here) generates a well known file that is then merged during OSM planet file construction. Renaming this script won't affect the output file, so we're fine to go ahead.

**Comment by FloEdelmann** [comment]
@nvkelso I created a PR: #2112.
