### ISSUE TITLE
Adjust landuse & water area threshold for mid zooms

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#213]
We're including too much random data at some zooms, let's throttle that back a bit.

We want to include slightly more data than might normally be visible on a map at that zoom, but not loads more data. 

We currently threshold that by a square "pixel" on screen at that zoom. Let's consider raising that to 2+ pixels. Let's comp what 2, 3, 4, and 5 thresholds look like and review which new setting to use.

**Comment by rmarianski** [comment]
Would be easiest to tackle this first: https://github.com/mapzen/vector-datasource/issues/202

**Comment by nvkelso** [comment]
Should the queries have hard coded areas (based on the 1 pixel threshold at that zoom, or make use of the change in #202?

**Comment by rmarianski** [comment]
That minimum area filter for the 1 pixel threshold will get applied to all features across all layers, so we won't have to add anything to the queries for that. But if we wanted to be more aggressive as to what gets filtered out in a particular layer, we can add that to the queries.

**Comment by nvkelso** [comment]
https://github.com/tilezen/vector-datasource/issues/473 should most address the landuse portion of this. 

Moving this to v1.1 to track any additional cleanup that might be needed.

**Comment by nvkelso** [comment]
Let's track the remainder of this with https://github.com/tilezen/vector-datasource/issues/1822.
