### ISSUE TITLE
Consider thinning roads in z8, z9

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#251]
In dense urban areas like the Eastern seaboard of the USA, England, and Europe we have a ton of roads in zoom 8 and z9. 

Consider thinning so only national and international roads are included (looking at things like ref to determine this).

**Comment by nvkelso** [comment]
From Matt: 

```
ideally, we'd show important roads where we pull the importance out of a network algorithm (perhaps part of Valhalla) where it's the structural importance of the road that determines how important it is, not the class. (e.g: the only ferry route to an island is way more important than a similar ferry route across a bay or to a peninsula)
```

**Comment by dnesbitt61** [comment]
Ah, that is the $1,000,000 question in Valhalla. How do we override the highway tag to create valid "network classifications".  Reach-based routing seems to be a solution but looks to be incredibly expensive. Open to any and all ideas here!

**Comment by nvkelso** [comment]
Deferred.
