### ISSUE TITLE
Investigate seam in Australia

### ISSUE THREAD

**Issue by rmarianski** [tilezen/vector-datasource#262]
At zoom level 2, we're seeing a seam in tangram.

![australia-seam-z2](https://cloud.githubusercontent.com/assets/53770/10148438/81d6a2ac-6601-11e5-8ed8-78aed615cd43.png)

**Comment by rmarianski** [comment]
I couldn't find an easy to plug in python library to encode topojson. I thought of trying to find a way to rule out the encoding, and instead of coming up with a one-off to pull down geojson and convert to topojson, I figured it wouldn't be more effort to just create a small proxy to help test.

https://github.com/rmarianski/topojsontest
(I put this in my personal area to avoid cluttering up the other orgs)

When I plugged in this proxy in tangram for the `mapzen-local` anchor url, a different seam came up and Australia seemed to disappear. There were other rendering artifacts that appeared too.

![australia-seam-z2-proxy](https://cloud.githubusercontent.com/assets/53770/10168709/fcc98eee-669b-11e5-89b7-1528f3677ae2.png)

@bcamper mind giving this a try to see if it helps figure out what's going on?

**Comment by zerebubuth** [comment]
Hmm... interesting. What happens if you swap that around so that the proxy is decoding topojson to geojson? Are there any artefacts with that?

**Comment by rmarianski** [comment]
That's a good idea. I'll give this a try.

**Comment by bcamper** [comment]
I remain suspicious if we are not using a commonly used topojson encoder :)

**Comment by nvkelso** [comment]
Closing this old issue. Data seems fine now:

![image](https://user-images.githubusercontent.com/853051/52679583-5e402d80-2eea-11e9-9372-c6d790e92d2f.png)
