### ISSUE TITLE
Remove centroid column

### ISSUE THREAD

**Issue by rmarianski** [tilezen/vector-datasource#287]
The mz_centroid column was used to return back centroids for the landuse labels layer. That's done in a post process step now, so the centroid column and relevant portion of the polygon trigger can be removed.

**Comment by nvkelso** [comment]
Good catch.

**Comment by nvkelso** [comment]
We might want to keep these pending #302.

**Comment by nvkelso** [comment]
Closing as expired, no longer relevant.
