### ISSUE TITLE
Refine water / land mask for martime_boundary

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#294]
This data file needs updates:
- http://s3.amazonaws.com/mapzen-tiles-assets/curated/buffered_land.zip

**Comment by nvkelso** [comment]
Channel Islands off California need to be added to the maritime SHP (we shouldn't see boundary here):

<img width="836" alt="screen shot 2015-10-03 at 16 57 59" src="https://cloud.githubusercontent.com/assets/853051/10265684/0c4373c4-69f0-11e5-9480-865460931e20.png">

**Comment by nvkelso** [comment]
Near Virginia and Washington DC:
#9/37.8427/-75.6437

<img width="749" alt="screen shot 2015-10-03 at 17 05 57" src="https://cloud.githubusercontent.com/assets/853051/10265711/10867d36-69f1-11e5-9650-f1b747ed6b6d.png">

**Comment by nvkelso** [comment]
South Carolina:
#9/33.2973/-79.3591

<img width="686" alt="screen shot 2015-10-03 at 17 06 44" src="https://cloud.githubusercontent.com/assets/853051/10265717/2dcde5aa-69f1-11e5-994d-c0966b7670ac.png">

**Comment by nvkelso** [comment]
Florida:
#8/27.496/-79.579

<img width="333" alt="screen shot 2015-10-03 at 17 07 32" src="https://cloud.githubusercontent.com/assets/853051/10265724/44a3a134-69f1-11e5-9dbf-b4ff8cb7a4c5.png">

**Comment by zerebubuth** [comment]
TODO: export "maritime" boundaries from OSM to shape for @nvkelso.

**Comment by nvkelso** [comment]
Paging @stepps00!

**Comment by nvkelso** [comment]
(There are a lot more funky areas in Europe.)

**Comment by stepps00** [comment]
@zerebubuth - Can you please dump a shapefile of the country (admin level 2) and region (admin level 4) ways for me, please?

**Comment by stepps00** [comment]
Dates:

**October 24th** - Alpha data revisions in to Nathaniel for review
**October 28th** - Beta data revisions in to Nathaniel for final push (for 1.1 build)

**Comment by nvkelso** [comment]
Related: https://github.com/tilezen/vector-datasource/issues/735

**Comment by stepps00** [comment]
Note: A draft copy of the updated `land_buffer` file is in S3 ([here](https://whosonfirst.mapzen.com.s3.amazonaws.com/misc/updated_land_buffer.zip)) for Monday's review.

**Comment by stepps00** [comment]
Shapefile ready for the dev build are in S3 ([here](https://whosonfirst.mapzen.com.s3.amazonaws.com/misc/buffered_land_10272016.zip)). Compressed file includes the following:

* **updated_buffered_land.shp** - The main land polygon, minus areas closest to the coastline
* **buffered_bits.shp** - Extra pieces that extend from `updated_buffered_land.shp`
* **buffered_land_10272016.shp** - Combined file that should replace `buffered_land`

`buffered_land_10272016.shp` size: **7.6MB**

**Comment by rmarianski** [comment]
Updated prepared assets on s3 to include new buffered land.

**Comment by nvkelso** [comment]
Waiting for a dev build to verify this.

**Comment by nvkelso** [comment]
@rmarianski Thinking more about the "tiled" earth data today on Ian's merge land/water issue, should this buffered land be "tiled"? It's being intersected with a ton of boundaries data in almost every tile.

**Comment by rmarianski** [comment]
@nvkelso good idea. I see that it's also just a single feature in that shape file, and think it would be better to tile it as well. I'll go ahead and make another pr for that.

**Comment by nvkelso** [comment]
Verified on dev:

_Some screenshots show red for region lines that are newly tagged as maritime, others have it hidden as in the prod Bubble Wrap design._

<img width="733" alt="screen shot 2016-11-11 at 08 37 37" src="https://cloud.githubusercontent.com/assets/853051/20222452/3ba1437e-a7ea-11e6-8553-e5ce0ab48118.png">
<img width="996" alt="screen shot 2016-11-11 at 08 25 26" src="https://cloud.githubusercontent.com/assets/853051/20222453/3bde7dd4-a7ea-11e6-8614-b74f44ca99ff.png">
<img width="979" alt="screen shot 2016-11-11 at 08 25 00" src="https://cloud.githubusercontent.com/assets/853051/20222454/3bdf64ba-a7ea-11e6-9e9c-81e1ed05435a.png">
<img width="1078" alt="screen shot 2016-11-11 at 08 24 45" src="https://cloud.githubusercontent.com/assets/853051/20222455/3be17f02-a7ea-11e6-8058-5f4edc67cb87.png">

<img width="402" alt="screen shot 2016-11-11 at 08 39 53" src="https://cloud.githubusercontent.com/assets/853051/20222513/720563b4-a7ea-11e6-8603-14ff840f46a9.png">
<img width="592" alt="screen shot 2016-11-11 at 08 39 32" src="https://cloud.githubusercontent.com/assets/853051/20222516/7245ee02-a7ea-11e6-831c-bbf213706a2a.png">
<img width="573" alt="screen shot 2016-11-11 at 08 39 14" src="https://cloud.githubusercontent.com/assets/853051/20222515/72445d08-a7ea-11e6-8e3a-45eb7eb7e339.png">
