### ISSUE TITLE
Parking areas that have height are buildings

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#295]
Around the new Mapzen SF office are a bunch of parking garage buildings with height information, but they don't show up as buildings. Seems like they should be show up as (parking) buildings.

**Comment by bcamper** [comment]
What are they tagged as?

**Comment by nvkelso** [comment]
See the way on OSM: https://www.openstreetmap.org/way/192306745

```
amenity	parking
building	yes
height	30 m
parking	multi-storey
```

I added `building=yes` yesterday, but it already had a `height` and `parking=multi-storey` which to me implies `building=yes`.

**Comment by zerebubuth** [comment]
Looks like there's about [18,000 uses of multi-storey](http://taginfo.openstreetmap.org/tags/parking=multi-storey), and while [most appear to have some kind of building tag too](http://taginfo.openstreetmap.org/tags/parking=multi-storey#combinations), it's easy enough to make multi-storey imply building.

Should we do a similar thing with the underground parking and have it imply building and `layer=-1`?

**Comment by bcamper** [comment]
My 2 cents: it might be useful to have some kind of general `underground`
designation, for easier filtering (and just less obscure to consumers than
layer=-1).

**Comment by nvkelso** [comment]
We’re using `location=underground` for buildings like BART starting in
v0.4.0

**Comment by nvkelso** [comment]
We set those as kind parking_garage as of a couple releases ago, closing.
