### ISSUE TITLE
Building outlines endpoint now returns points too (and breaking all ViziCities demos)

### ISSUE THREAD

**Issue by robhawkes** [tilezen/vector-datasource#296]
I've been receiving reports today that [ViziCities](http://github.com/vizicities/vizicities/tree/0.2.0) has been spitting out errors and not outputting buildings – this only started in the past day or so.

I dug into it and it looks like the `/osm/buildings/...` endpoint is now mixing in `Point` features alongside the `Polygon` features – this wasn't how the API was originally structured and as such ViziCities has been built around the assumption that everything would be a `Polygon` feature (ie. a footprint [as per the docs](https://github.com/mapzen/vector-datasource#buildings)). It has broken all existing ViziCities visualisations using the Mapzen endpoint and is causing me a lot of headaches (I'll most definitely be adding in more validation from now on!).

You can see an example of this [from the following tile](http://vector.mapzen.com/osm/buildings/15/16382/10896.json):

![](http://cl.ly/image/2K1g2c2e3M2s/Screen%20Shot%202015-10-09%20at%2010.33.55.png)

It would be good to know the following:
- Is this an expected change?
- If so, where should I be looking to be notified of significant changes to the API output like this?
- Is it possible to get an endpoint that only returns `Polygon` footprints?

**Comment by nvkelso** [comment]
Hey @robhawkes, I'm very sorry for the headache this caused you! We're excited you're using Mapzen's vector tiles in Polygon City, neat project :)

I'm working to setup an better communication around Mapzen vector tile changes, more on that soon.

> Is this an expected change?

Yes. The old implementation resulted in duplicate building labels for features that spanned multiple tiles (one label per tile part). We are now generating a new `label_position` feature to address this. I believe it was part of the v.0.2.0 release last month. Also note that we've started versioning at all :)

> If so, where should I be looking to be notified of significant changes to the API output like this?

Each Mapzen vector tiles release is now tagged in Github (for the last 3 releases), and we're keeping tracking an overview of changes in the new [CHANGELOG](https://github.com/mapzen/vector-datasource/blob/master/CHANGELOG.md). The Mapzen vector tiles didn't change much after launch but there's been a recent focus on improving them that will continue. It's very important to me to maintain backwards compatibility during this time, and to communicate about changes.

> Is it possible to get an endpoint that only returns Polygon footprints?

Maybe, I'll discuss with the team. For instance, it's possible to move the new `label_position` features out of the `buildings` layer in the `pois` layer, but then we should also move the newish `kind=address` point features out of the `buildings` layer in to the `pois` layer, too, and suddenly all building things aren't together, and it doesn't follow the same packaging logic as the `water` (collection of polygons, lines, and points) or `landuse` (collection of polygons and points) layers.
