### ISSUE TITLE
Only include minor roads starting zoom 9

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#305]
We're including minor roads starting at zoom 8 now, but that clogs up the database payload (and we don't render these until much later until zoom 11). Let's start including them at zoom 9 so there's still a little wiggle room on the cartography styling side.

CORRECTION: I had said zoom 10, but let's do zoom 9 instead. It allows someone to show more detail in areas where road hierarchy hasn't been added yet.

**Comment by zerebubuth** [comment]
@nvkelso, could you clarify what you mean by "minor road", please? We shouldn't be including anything thats `kind=minor_road` before zoom 12 at the moment. If there's stuff that's `kind=minor_road` then that's a bug! If so, a pointer to where that's happening would be very helpful. It sounds like you mean "minor road" in a context-dependent way, which might be the same as "not a highway" at zoom 8.

**Comment by nvkelso** [comment]
This took some digging! The `minor roads` reference comes from a comment you made here: https://github.com/mapzen/vector-datasource/pull/304#issuecomment-147729779. I think I took that literally when creating this issue (#305), and looking the code, but I think this got garbled along the way :/ We can dig into this more in the v0.7 release?

**Comment by nvkelso** [comment]
This also smells like a possible duplicate of: https://github.com/mapzen/vector-datasource/issues/251

**Comment by zerebubuth** [comment]
Haha, yes! I clearly meant "minor roads" in a context-dependent way in https://github.com/mapzen/vector-datasource/pull/304#issuecomment-147729779 too!

Are there whole classes of roads that we're not displaying at zoom 8? The `kind:major_road` ones, perhaps? If not, then something like #251 is going to be necessary, but it's a tough one...

Note that #358 would have a beneficial effect on the tile sizes, if that's our goal rather than thinning out the display.

**Comment by nvkelso** [comment]
This is turning into a research project, let's pick it up again in v0.7.

**Comment by nvkelso** [comment]
Looking at Bubble Wrap house style with all roads added for debug in blue at 1 px width, there seems to be a perfect correspondence between what's in tiles and what we symbolize. This might have been a problem awhile ago, but it seems to have sorted itself out.
