### ISSUE TITLE
Add boundary=protected_area and boundary=national_park to Landuse (and Landuse labels)

### ISSUE THREAD

**Issue by spatialhast** [tilezen/vector-datasource#318]
Please add boundary=protected_area and boundary=national_park kind to Landuse (and Landuse labels)
Example OSM tags:
http://www.openstreetmap.org/way/370717639 - protected_area
http://www.openstreetmap.org/relation/4270269 - national_park
Thanks!

**Comment by nvkelso** [comment]
Great idea! We made changes in [v0.3.0](https://github.com/mapzen/vector-datasource/blob/master/CHANGELOG.md#v030), (see also: https://github.com/mapzen/vector-datasource/issues/149). a few weeks ago that should have accomplished this and those should have been live for a couple weeks now. Can you confirm it's working, please?

> http://www.openstreetmap.org/way/370717639 - protected_area

**Preview:** http://nvkelso.github.io/tangram-skin-and-bones/#9/51.3263/33.5632
**Screenshot:**
![screen shot 2015-10-20 at 13 37 47](https://cloud.githubusercontent.com/assets/853051/10620417/d546dab2-772f-11e5-927a-0f0d69f37a8d.png)

> http://www.openstreetmap.org/relation/4270269 - national_park

**Preview:** http://nvkelso.github.io/tangram-skin-and-bones/#12/49.5696/36.3225
**Screenshot:** 
![screen shot 2015-10-20 at 13 39 16](https://cloud.githubusercontent.com/assets/853051/10620451/001e63fe-7730-11e5-98b5-f606e36bda4d.png)
