### ISSUE TITLE
Add sort_key to transit layer

### ISSUE THREAD

**Issue by zerebubuth** [tilezen/vector-datasource#353]
Sort key is useful on roads, and probably would be useful on transit as well.

What criteria do we want to use to sort on?

**Comment by blair1618** [comment]
Off the top of my head it'd be nice to have:

 - Any stable relative ordering between subway lines so that we can render intersections consistently
 - Whether or not the transit line is above ground? It would be good for rendering to have some way to get this information but maybe it's in another tag already.

**Comment by nvkelso** [comment]
Should the existing sort function be modified or are we creating a special `transit` layer "roads" sort function?

Looks like the `layer` tag is on a lot of these transit features, and bridges & tunnels are marked (just like we have on roads).

Related tags? 

* http://wiki.openstreetmap.org/wiki/Key:service
* http://wiki.openstreetmap.org/wiki/DE:Key:highspeed with https://taginfo.openstreetmap.org/keys/highspeed#map

**Proposal**

Reviewing [list of railway types](http://wiki.openstreetmap.org/wiki/Railways) and [2nd](http://wiki.openstreetmap.org/wiki/Key:railway), I propose the following sort order (top rail item should sort above bottom tram item):

* railway=rail
* railway=subway
* railway=preserved
* railway=narrow_gauge
* railway=abandoned
* railway=disused
* railway=funicular
* railway=monorail
* railway=miniature
* railway=light_rail
* railway=tram

Modified up and down for `highspeed` like we just added for `service`?

Related is `usage`, though that seems more like a landuse thing. I think we should try with `service` and see where we get.

* http://wiki.openstreetmap.org/wiki/Key:usage

Question:

At ~zooms 12+ it's helpful to have rail above subway. But after then the opposite is true zoomed out. This could be included in the sort function, or be a client side scene file directive.

**Comment by zerebubuth** [comment]
We'll have a different function for transit sorting. We already have different functions for adding `sort_key` to landuse and roads, so it's best to stick with that pattern. If we want to make `sort_key` consistent across layers (i.e: so that transit features sort consistently relative to road features) the we might want to consider doing something different, and changing the range over which we generate `sort_key`.

The OSM wiki is just a mixture of noise and wishful thinking - it's better to look at taginfo to find out what's actually available in the data.

**Comment by zerebubuth** [comment]
I've managed to confuse myself about the purpose of this issue. Some things:

1. We already sort transit types (rail, subway, tram lines, etc...) as [part of the roads layer](https://github.com/mapzen/vector-datasource/issues/332), in which they've been sitting for [some time](https://github.com/mapzen/vector-datasource/commit/d1d60105).
2. The transit layer is all about transit _routes_ which are higher level relations grouping the ways which make up the line, and aren't generally broken into sections based on the physical (above, below ground) situation of that part of track.
3. We are limited in the range of values we can use, as they're used for depth buffer offsets.

So... questions:

1. Has this been superseded by #332?
2. What relative ordering do we want between road and rail features in the same layer?
3. It looks like roads doesn't currently include any subway features, those are only in transit, should roads include those too?
4. Can we increase the range used from 0-39 up to 0-100 to make way for more distinct classifications (@nvkelso seems to be mostly a style question - will we be edging out other feature orders)?
5. I'm not sure that [this layer override](https://github.com/mapzen/TileStache/blob/7e86ba67690a8e592ecfdea5ed8e51f995bdc342/TileStache/Goodies/VecTiles/transform.py#L337-L350) is necessarily right - do we not want a primary road to render on top of a railway (for example) even if both were at `layer=N`?
6. It's unlikely we have enough bits spare to provide a globally-unique sort order for rail/subway lines, but would it be helpful to have a hashed order to at least remove some of the collisions?

**Comment by nvkelso** [comment]
This work needs to be coordinated with landuse sort changes, which are a v0.7 task.

**Comment by nvkelso** [comment]
Moving to align with other transit changes in v0.8

**Comment by nvkelso** [comment]
Some work was done on this for v0.8 milestone. Is that enough or do we need to do more to meet the goals of this issue?

**Comment by nvkelso** [comment]
in v0.8 we set these to:

```
kind,sort_key
tram,415
light_rail,415
platform,385
*,275
```

But if someone is building a transit map style, these should really be higher rank. Should we include this as a new `sort_key_promoted` sort key?

```
kind,sort_key_priority
tram,467
light_rail,467
platform,435
subway,468
*,465
```

**Comment by zerebubuth** [comment]
I think if we're talking about decisions that someone might want to make in the style, then might we want to leave that as a client-side operation? Is it not possible to offset the transit features by having `order: function() { return feature.sort_key + 40; }` or something like that?

**Comment by nvkelso** [comment]
`+ 40` might be a good option now, but later on it might need to be `+ 65`. Rather that leaving that to documentation, we could include the recommended value on the feature.

**Comment by nvkelso** [comment]
Related: This approach is also useful for the ski pistes in the roads layer.

**Comment by nvkelso** [comment]
It's also possible to adjust the sort_key based on service (for "national" rail features) now, see #616.

**Comment by nvkelso** [comment]
This one needs to bake more before we burn the suggested sort_key values into tiles. Moving out a release.

**Comment by nvkelso** [comment]
Regarding the **tourism train** in the SF Zoo... turns out the list above includes `miniature`, but we're not yet whitelisting that for inclusion in tiles. That will either be covered here, or split of into it's own compilation issue.

/cc @burritojustice

**Comment by nvkelso** [comment]
This is working.

Doing some sort of `sort_key_transit_map` is out of scope for v1.0, and a separate issue if it needs doing.

Let's track miniature in https://github.com/tilezen/vector-datasource/issues/955.
