### ISSUE TITLE
Places of worship pois shown too late?

### ISSUE THREAD

**Issue by zerebubuth** [tilezen/vector-datasource#373]
> We're missing a label position for Grace Cathedral in SF:
> 
> http://vector.mapzen.com/osm/all/14/2620/6331.topojson?api_key=vector-tiles-HqUVidw
> http://vector.dev.mapzen.com/osm/all/14/2620/6331.topojson?api_key=vector-tiles-HqUVidw
> 
> It does finally show in in zoom 15 in the POIs layer instead:
> 
> http://vector.dev.mapzen.com/osm/all/16/10483/25327.topojson?api_key=vector-tiles-HqUVidw

Since #201, places of worship are in the POIs layer, but it sounds like it comes in too late. @nvkelso, what would be an appropriate zoom for a place of worship with an area of 4079 to come in?

**Comment by nvkelso** [comment]
Closing stale issue.
