### ISSUE TITLE
🌍 road through sea: source earth/water from OSM at zoom 8

### ISSUE THREAD

**Issue by musicformellons** [tilezen/vector-datasource#389]
**tl;dr**

Bring in OSM earth and water at zoom 8 instead of zoom 9.

===

At this zoom and coords:
#8.71/51.9235/4.2742

I get:
![screenshot from 2015-11-05 14-59-42](https://cloud.githubusercontent.com/assets/10334123/10970323/370ced54-83ce-11e5-920c-2968371aaa85.png)

At higher zoom it is correct:
#9.05/51.9686/4.2487

![screenshot from 2015-11-05 15-00-01](https://cloud.githubusercontent.com/assets/10334123/10970343/4f9c344c-83ce-11e5-9538-933e5cd4c239.png)

**Comment by nvkelso** [comment]
We're still using Natural Earth earth shapes at zoom 8, and at 9 we transition to simplified OSM. 

We switch most everything else over to OSM at zoom 8, but land and water were too noisy without additional simplification tuning to do this right away. As an interim step, Natural Earth could update the land shape here and we'd pick it up, or we could invest the time to optimize OSM at this zoom.

**Comment by musicformellons** [comment]
Ok, thanks for explaining.

**Comment by nvkelso** [comment]
Reopening as this is probably systemic and we should consider a change to address it.

**Comment by zerebubuth** [comment]
Another example, thanks to @tallytalwar. The lakes and coastline move: http://tangrams.github.io/tangram-play/?scene=https://raw.githubusercontent.com/tangrams/eraser-map/gh-pages/eraser-map.yaml#9.025416666666656/-44.0125/169.5039

**Comment by zerebubuth** [comment]
An example thanks to SK53 & KDDA: http://tangrams.github.io/cinnabar-style/#9/54.4021/-7.8429 - zoom out and Lower Lough Erne (and many other water bodies) disappears.

Also, this "crack" appears: http://tangrams.github.io/cinnabar-style/#9.975/54.2719/-8.7711 - seems to be related to simplification of the coastline?

**Comment by nvkelso** [comment]
I'm open to moving OSM water / land up an earlier zoom. We just need to work on the simplification.

**Comment by nvkelso** [comment]
Subtask of: https://github.com/tilezen/vector-datasource/issues/155

**Comment by matteblair** [comment]
Another fun example, this gigantic river in Northeast India vanishes from zoom 9 to zoom 8: http://tangrams.github.io/cinnabar-style/#9.079166666666643/27.4777/95.0254

**Comment by nvkelso** [comment]
@matteblair Regarding https://github.com/tilezen/vector-datasource/issues/389#issuecomment-327340448 we'll need to bring in Natural Earth river lines as the OSM river polygons don't hold up at low zooms. This is covered in https://github.com/tilezen/vector-datasource/issues/155.

**Comment by nvkelso** [comment]
This was fixed a while ago, and incorrectly re-opened. Closing again.
