### ISSUE TITLE
Road construction missing?

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#394]
Looking around Union Square in SF, it seems like we're dropping roads that are under construction. We should include those, but mark them as under construction.
#17/37.78636/-122.40449

<img width="604" alt="screen shot 2015-11-06 at 10 39 55" src="https://cloud.githubusercontent.com/assets/853051/11005513/12cd762a-8473-11e5-933d-44f0d988026c.png">

**Comment by nvkelso** [comment]
In these cases, the roads are still open for pedestrian use, so it's especially weird to drop them.

**Comment by zerebubuth** [comment]
Yup, these will be tagged `highway=construction`, which presumably isn't in our whitelist. What's the best way to include these in a way which means people don't get caught out? For example, we could:

1. Include them as `kind=construction` with the `foot`, `bicycle`, `motor_vehicle` access tags.
2. Synthesize a limited-access way, e.g: `kind=path, highway=footway` from the access tags, and simply add construction as a separate tag `construction=yes`.

The former has the advantage that it's closer to the original data. The latter requires fewer special cases in the style to work correctly if people don't really care about the construction - just that it's passable by horse or whatever.

**Comment by nvkelso** [comment]
http://www.openstreetmap.org/way/290080810#map=19/37.78655/-122.40653

**Comment by zerebubuth** [comment]
@nvkelso: which of the options (`kind=construction`, synthesizing, or something different?) would be best in the tiles for styling?

**Comment by nvkelso** [comment]
For option 2 (synthesize)... if there's still some access on the way tagged with construction, we evaluate which next best highway tag would be equivalent and mark it `kind=path` in this case?

Is there a downside? What about a highway that is under construction that does allow some pedestrian access still (like shoulder "sidewalks", not a separate path feature)? Would the way show up in tiles as `kind=path`? How would the renderer know that it's a highway under construction to dash the line (like on OSM.org)? Would there be enough tags to build that back up?

**Comment by nvkelso** [comment]
For option 1 (pass thru), would we add `construction` to the list of highway values [here](https://github.com/mapzen/vector-datasource/blob/master/queries/roads.jinja2#L42-L44) and to the line above (so the `construction=*` value comes thru, too)?

Looks like the gravity-storm stylesheet uses the pass thru method:

* https://github.com/gravitystorm/openstreetmap-carto/blob/db1bb40c21a0dac93016b17e109b086365646b27/roads.mss#L1068-L1163

**Comment by nvkelso** [comment]
See more: 

* https://wiki.openstreetmap.org/wiki/Key:construction

**Comment by zerebubuth** [comment]
Option 1: Yes, this one's simpler to implement, but puts all the burden of figuring out how to display a construction thing onto the person writing the style. This may mean writing many cases for handling the different types of construction which closely mirror the existing cases. At the moment, that would be impossible as we don't even put access properties (`foot`, `bicycle`, `motor_vehicle`, etc...) in the tiles.

Option 2: Right, so something that's tagged as `highway=construction, foot=yes` would become `kind=path, highway=footway, construction=major_road` or something like that. We'd basically try to make the properties in the tile as similar as possible to an equivalent kind to make it easier for styling (i.e: if you don't handle construction, it just appears to be a path).

In the case where only one style is being rendered (e.g: the OSM-carto style) then it's no big deal whether it's done in the "tile" or in the "style" (except that OSM-carto isn't a vector style, so, rather if it's done in the "query" or "style"). We, on the other hand, have to decide whether the extra work & flexibility should be on the style side, or the server side.

**Comment by matkoniecz** [comment]
Note that option 2:

- will make it complicated for people wishing to make car-only map displaying highway=construction as currently unavailable (standard method present in navigation aps that I tested)
- kind=construction is still necessary for cases where road is unavailable for all kind of traffic
- may result in weird situations if sidewalks are separately mapped

**Comment by nvkelso** [comment]
Let's prototype using option 1.

**Comment by nvkelso** [comment]
Verified:

![image](https://user-images.githubusercontent.com/853051/56544369-2c21fc00-6529-11e9-80e9-10e203c4fff8.png)
