### ISSUE TITLE
WOF neighbourhoods should export localized names

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#418]
https://whosonfirst.mapzen.com/spelunker/id/85910293/

This neighbourhood has a default name in Japanese, which is what we're exporting as the name in tiles. But there are other languages, and we should export those, too.

**Comment by nvkelso** [comment]
Moving out of the v0.7 milestone to load balance.

There's also some changes in the works on the WOF side for default name and localized names that might require additional work, so would like to batch with that.

Plus Tangram still doesn't have ability to auto-switch displayed languages, so...

**Comment by nvkelso** [comment]
And again to v0.9

**Comment by thisisaaronland** [comment]
See also: https://github.com/whosonfirst/whosonfirst-data/issues/183

**Comment by rmarianski** [comment]
@zerebubuth what do you think of making a new hstore column in the database to store all of these? That way, we can include it as the tags value in the query, and it should just get included in the output via the usual transform. We'd have to make sure that we used the same i18n scheme as osm when we save the data, or maybe it makes more sense to have the transform be more flexible to support both schemes.

**Comment by zerebubuth** [comment]
Hstore sounds good.

If we start translating between schemes, then it makes it more work for us later on. Reading the [WOF name docs] I'm confused as it keeps referring to country codes, and we use [ISO 639-1 language codes](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)...

I feel it might be easier to just expose the data that WOF has and let whoever's making the map choose what's the appropriate country / language codes for them.

**Comment by nvkelso** [comment]
We need should resolve this inconsistency for customers on the server as part of this issue.

**Comment by rmarianski** [comment]
@dianashk we'd like to be consistent with what you end up doing in search. What do you think?

**Comment by thisisaaronland** [comment]
That the WOF documentation refers to country codes is a bug. The docs _mean_ to indicate that we are using ISO-639-3 language codes. See also:

https://www.w3.org/International/articles/language-tags/#language

I will update the docs, shortly, when I am not using my hands to put food in my mouth...

**Comment by rmarianski** [comment]
Just spoke with @dianashk and @orangejulius, and we'll update to use iso-693-3 codes across the board. We'll normalize the tags from osm to convert the iso-693-1 codes to iso-693-3 codes.

**Comment by nvkelso** [comment]
This is pretty awesome :)

<img width="988" alt="screen shot 2016-08-09 at 23 13 23" src="https://cloud.githubusercontent.com/assets/853051/17543651/f59811ac-5e86-11e6-94c2-3812ed1ffb7e.png">

<img width="948" alt="screen shot 2016-08-09 at 23 13 37" src="https://cloud.githubusercontent.com/assets/853051/17543650/f5954af8-5e86-11e6-9b12-ffede6eec9cd.png">

/cc @thisisaaronland
