### ISSUE TITLE
Not all pistes are in the database

### ISSUE THREAD

**Issue by zerebubuth** [tilezen/vector-datasource#423]
Because `piste:type` isn't listed in `osm2pgsql.style`, a feature which just has "piste" tags on it won't be considered "interesting". This happens quite a lot with interconnecting bits of piste, where they don't have a name that would make them "interesting".

It's a simple one-line fix to add `piste:type` as an "interesting" tag, but this would require a full database reload, which is a lot of time and effort. So this is just here as a placeholder - perhaps if we collect several of these kinds of issues it'll sum up to being worth doing.

**Comment by zerebubuth** [comment]
Refs #342.

**Comment by zerebubuth** [comment]
Examples:

* [Way 294549962](http://www.openstreetmap.org/way/294549962)
* [Way 403291852](http://www.openstreetmap.org/way/403291852)
* [Way 395093666](http://www.openstreetmap.org/way/395093666)

**Comment by nvkelso** [comment]
Way 294549962 did finally render on dev :)
