### ISSUE TITLE
Misleading area tag on OSM ocean polygons

### ISSUE THREAD

**Issue by zerebubuth** [tilezen/vector-datasource#428]
(For background, see #407)

We're using the [OpenStreetMapData split ocean polygons](http://openstreetmapdata.com/data/water-polygons) and each split part has its area calculated separately. This can be confusing, as each individual split polygon has no geographic meaning - it's purely a convenience for indexing and rendering.

We might want to consider either dropping the area property on OSM ocean polygons, or setting it to something like the total ocean area of the world, as this would be less confusing to anyone manipulating the features later (e.g: trying to drop or count small bodies of water).

**Comment by rmarianski** [comment]
Will we have this issue with area any time we have polygons that were split in osm2pgsql?

**Comment by zerebubuth** [comment]
It looks like osm2pgsql only splits multipolygons into individual polygons. I can't find any other reference to splitting polygons.

It looks like the way area is [calculated per individual polygon](https://github.com/openstreetmap/osm2pgsql/blob/master/output-pgsql.cpp#L183-L191) when they are split not per multipolygon. This might mean we're excluding small parts of a polygon which would sum to a large enough area to be included. I'm not sure what's the right behaviour here... there's an area for the feature (e.g: ocean), but the area for the individual polygon is important for some uses too...

**Comment by nvkelso** [comment]
This is really an upstream problem, and our recommendation is to not use the `area` tag on ocean water features. Closing.
