### ISSUE TITLE
Normalise oneway property

### ISSUE THREAD

**Issue by zerebubuth** [tilezen/vector-datasource#453]
In #249, the values of `is_link`, `is_tunnel`, and `is_bridge` were normalised so that by default they were not present (indicating "no") and only present when their value was positive. All of these values are comparatively rare, only being set to "yes" on a small proportion of elements. Normalising them makes it slightly easier to extract the meaning from these properties in the stylesheet, and also means that tiles didn't contain extraneous `is_something:no` properties for each road feature, reducing tile size.

The "oneway" tag is similar, except:
1. We don't set it unless it already has a value, unlike `is_link`, `is_tunnel`, and `is_bridge` which were set on every road feature.
2. While `is_link`, `is_tunnel`, and `is_bridge` always default to false, I think there are [some road types for which oneway defaults to true](http://wiki.openstreetmap.org/wiki/Key:oneway#Implied_oneway_restriction), so we would need to include that in the processing if we were to elide `oneway: no`.

Should we normalise the oneway property?

**Comment by nvkelso** [comment]
`is_oneway`, ftw

**Comment by nvkelso** [comment]
We'll probably need to adjust the road merging behavior to take oneway into account, too.

**Comment by nvkelso** [comment]
Outdated, closing.
