### ISSUE TITLE
Add barrier=toll_booth to POIs layer

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#479]
These are mostly OSM nodes, but are sometimes attributed onto buildings?

See: http://wiki.openstreetmap.org/wiki/Tag:barrier%3Dtoll_booth

**Comment by zerebubuth** [comment]
Most are on nodes, and it looks like they're connected to the highway. The ones tagged on ways seem to be mostly buildings which overlap the highway, but as far as I can tell don't have the node as well. From a quick visual inspection, the remainder are a small proportion of lines crossing the highways and buildings off to one side of the highway.

What we do will depend on how much we want to process the data, and how difficult we want to make it for ourselves. Some options:

1. Take the centroid of anything tagged as a toll booth and output these as points. Advantage: simplicity, captures all data. Disadvantage: sometimes won't be aligned with the roads, particularly if one booth building crosses multiple lanes.
2. Take the centroid(s) of the intersection of any roads and toll booths. Care needs to be taken not to lose the centroid of any building which doesn't intersect any roads. Advantage: captures a point for each lane. Disadvantage: more complex.

The good news is that there are so few non-point toll booths that it's likely any processing would take a negligible amount of time for the average tile. So any complexity is a problem only insofar as it makes the code harder to understand / write.

**Comment by nvkelso** [comment]
I'm fine with option 1 (basic centroid of polygons + the point features).

**Comment by nvkelso** [comment]
Interesting, `toll_booth` is often applied to the entrance gate to gardens and zoos (not just highway toll plazas).

Verified.
