### ISSUE TITLE
Not all attractions and zoo features are in the database.

### ISSUE THREAD

**Issue by zerebubuth** [tilezen/vector-datasource#485]
Because the `attraction` and `zoo` tags aren't in our `osm2pgsql.style`, we might be missing some of these features. Most places with a one of those tags will also be tagged with a `name` which will mean that they get included in the database, but not all. This is probably a very minor issue, similar to #423 and #433, and we should just track it to make sure that whenever we next do a full database re-load from scratch, we include this.

**Comment by zerebubuth** [comment]
Note: example [relation 4028929](http://www.openstreetmap.org/relation/4028929), [relation 3802167] (http://www.openstreetmap.org/relation/3802167). Although there aren't many - most include another tag which was already a column (e.g: area, landuse, building).

**Comment by nvkelso** [comment]
Verified both of these now show up in http://tile.dev.mapzen.com/vector/v1/all/16/36013/19312.topojson, confirming the DB is good to go.
