### ISSUE TITLE
Clean up duplicate functions in databases

### ISSUE THREAD

**Issue by rmarianski** [tilezen/vector-datasource#514]
When we create new functions with different parameters, sometimes we leave the old ones. This is usually fine, but it can end up masking problems where we don't update all invocations. We should clean up the duplicates on dev/prod just in case.

Here's how we can find the duplicates:

``` sql
SELECT proname, count(*) FROM pg_proc WHERE proname LIKE 'mz_%' GROUP BY proname HAVING count(*) > 1;
```

**Comment by rmarianski** [comment]
We didn't end up actually doing this yet. Gonna re-open for now and clear milestone.

**Comment by nvkelso** [comment]
Process changed.
