### ISSUE TITLE
Consider more granular "kind" property (roads)

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#536]
For roads layer in particular, we have a high-level generalized values (based on High Road) for `kind` properties, but the end-use must know a lot about the OSM source tags to know if they should look one property or another for more granular kind / type values. Another approach is to coalesce those into a new general property.

eg, a new property that coalesces across these road layer tags: 
- highway
- aeroway
- railway
- route
- aerialway
- leisure
- man_made

If we pack those values into a new property, should we keep including those individual key:value pairs in exported tiles?

There might be some opportunity for this in the places, boundary, and POIs layers, but that should be covered in other tickets.

**Comment by zerebubuth** [comment]
The end user will have to know a lot about OSM source tags to understand what `motorway`, `trunk`, `secondary`, `tertiary`, etc... mean.

I don't think we should be doing any more coalescing - it leads to more issues than it solves. E.g: #282 & #532.

**Comment by nvkelso** [comment]
Agree on not doing a database coalesce, was think about end-user experience of a "single subcategory property" to look at. 

Knowing more or less about specific OSM tags seems related but not blocking.

**Comment by nvkelso** [comment]
This was resolved for v1.0 release.
