### ISSUE TITLE
Update to NE 3.x for bundled shapefiles.

### ISSUE THREAD

**Issue by zerebubuth** [tilezen/vector-datasource#584]
Natural Earth is mostly UTF-8 now (yes for populated places file, probably for the others). If the `-merc` shapefiles bundled with vector-datasource are from the 2.x series which was still Windows-1252, then they should be updated to 3.x.

Any remaining encoding conversion funk should be fixed and reported upstream.

Context: #582.

**Comment by nvkelso** [comment]
Closed via #582.
