### ISSUE TITLE
Building should be fitness, but isn't

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#589]
- **What did you see?** I expected to see `kind:fitness` on the Funky Door Yoga fitness building `id=264528016`.
- **What did you expect to see?** It's instead `kind:building`.
- **What map location are you having problems with?** 
  - San Francisco's Haight neighbourhood.
  - http://vector.mapzen.com/osm/all/19/83809/202660.topojson?api_key=vector-tiles-HqUVidw 
  - [202660.topojson.zip](https://github.com/mapzen/vector-datasource/files/169592/202660.topojson.zip)
- **Screenshot?** 

<img width="808" alt="screen shot 2016-03-11 at 08 48 14" src="https://cloud.githubusercontent.com/assets/853051/13708984/5b849b04-e766-11e5-8509-18a92b7e30e6.png">

Earlier chatter from the other issue:

@nvkelso:

```
Another example for Indy's Fitness blog post:
In some tile cut runs this building is kind:yes, others it's kind: fitness_centre:
https://www.openstreetmap.org/way/264528016
```

@zerebubuth:

```
If this is displaying non-determinism, then it is a different issue. That building / fitness centre 
doesn't seem to have been edited recently, and we don't coalesce the building value in the 
POI kind calculation. There is some extra processing for fitness, but it only sets the kind to 
fitness, never yes. Likewise, there's some extra processing for buildings, but these explicitly 
avoid setting kind: yes.

Currently, I'm seeing kind: fitness on both dev and prod - if anyone sees a different value for 
this feature, please file a new bug with the full GeoJSON/TopoJSON tile attached!
```

**Comment by zerebubuth** [comment]
I disagree that we should have two feature in two different layers with the same kind from this one feature. We generate a point in the `pois` layer with `kind: fitness`, and leave the building as just a building. I think it makes more sense that way.

**Comment by nvkelso** [comment]
Duplicate of https://github.com/tilezen/vector-datasource/issues/487, closing.
