### ISSUE TITLE
Add highway=corridor and crossing=*, sidewalk=* tags for roads layer

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#605]
**New `roads` layer features:**

* `highway=corridor` - starting at zoom 16, to support indoor mapping and layering on top of buildings. [Example in SFO](https://www.openstreetmap.org/way/300867020), read more on [OSM wiki]()

**New attributes on `roads` layer features:**

* `crossing=*` - starting at zoom 17, to support pedestrian mapping. [Example in NYC](http://www.openstreetmap.org/way/382535027), read more on [OSM wiki](http://wiki.openstreetmap.org/wiki/Key:crossing). Drop this attribute at earlier zooms.
* `sidewalk=*` - starting at zoom 15, to support pedestrian mapping. [Example in SF](http://www.openstreetmap.org/way/23766104), read more on [OSM wiki](http://wiki.openstreetmap.org/wiki/Sidewalks). Drop this attribute at earlier zooms.

**Comment by rmarianski** [comment]
It looks like elements can have [crossing](http://taginfo.openstreetmap.org/keys/crossing#values) and [sidewalk](http://taginfo.openstreetmap.org/keys/sidewalk#values) keys, as well as having [footway values](http://taginfo.openstreetmap.org/keys/footway#values). Do we want to normalize these somehow?

I originally read the issue as passing the truthy `crossing` and `sidewalk` tags through to the tile properties, but the [nyc example](http://www.openstreetmap.org/way/382535027) only has `footway=crossing` and no `crossing` tag.

**Comment by nvkelso** [comment]
We added `footway=*` in the v0.10 release so that's already done.

**Comment by nvkelso** [comment]
We added some `footway=*` (mostly sidewalk and crossing) in v0.10 release. Let's take this opportunity to normalize (whitelist) values and share that whitelist with `crossing=*` and `sidewalk*=*` values.

**Comment by nvkelso** [comment]
**Corridors** are coming thru, but we might want to set their default sort order above buildings?

I've adjusted them above in the screenshot below:
18/37.61770/-122.38177

<img width="843" alt="screen shot 2016-08-09 at 22 09 04" src="https://cloud.githubusercontent.com/assets/853051/17542484/04ceda06-5e7e-11e6-9620-7fe03fe275f2.png">

**Comment by nvkelso** [comment]
For `sidewalk`, it looks like the vast majority of values (850,000) are in the primary `sidewalk` key, but there are optional `sidewalk:left` and `sidewalk:right` tags [listed in TagInfo](https://taginfo.openstreetmap.org/search?q=sidewalk), like we support for bicycle lanes, but both those side variants have less than 1000 uses. But it seems like for complete streets inventories the gaps are important and we should also pass them thru.

**Comment by nvkelso** [comment]
**Crossings** are showing up.

**Comment by nvkelso** [comment]
Not seeing this on dev yet.

**Comment by nvkelso** [comment]
Verified.
