### ISSUE TITLE
project route_master transit properties onto transit routes?

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#606]
- **What did you see?** The N-Judah in SF to have a "blue" color. The "route_master" feature it's part of **does** have blue set, and the other child relation also has "blue" set (manually by me).
- **What did you expect to see?** The color was missing from the route feature. Should we ask people to edit the color in the `route` or the `route_master`? In this case it's an "inbound" and an "outbound, so they'd need to enter it twice (one for each direction). Which isn't terrible, but just needs to be documented.
- **What map location are you having problems with?** 
  - route: https://www.openstreetmap.org/relation/3435877
  - route_master: https://www.openstreetmap.org/relation/3435884
- **Screenshot?** 

<img width="745" alt="screen shot 2016-03-14 at 16 31 25" src="https://cloud.githubusercontent.com/assets/853051/13763273/39f7803e-ea02-11e5-9031-634a1ee4c1ef.png">

/cc @IndyHurt

**Comment by zerebubuth** [comment]
Doing this kind of "relation exploring" is costly. I've hand-waved about it before and dismissed the cost on the basis that stations are rare features, but we're including stations ever-earlier, and the transit routes are also much more common (in terms of being included in more tiles). This is _possible_, but it won't be nice and could significantly impact tile performance.

This kind of processing would be more efficiently and cleanly done "upstream" either in `osm2pgsql` or NEAT.

**Comment by nvkelso** [comment]
Removing from v0.9 milestone but holding onto the issue.

Recommendation right now is to edit the **route relations**. Someday we might make use of the route_master relations.

**Comment by nvkelso** [comment]
Collapsing this into general fix in https://github.com/tilezen/vector-datasource/issues/1247.
