### ISSUE TITLE
no attribute 'normalize_and_merge_duplicate_stations'

### ISSUE THREAD

**Issue by AndrewIK** [tilezen/vector-datasource#609]
Hi there!
I went through https://github.com/mapzen/vector-datasource/wiki/Mapzen-Vector-Tile-Service following the instructions. Unfortunately I'm getting 

**KnownUnknown: Tried to import TileStache.Goodies.VecTiles.transform.normalize_and_merge_duplicate_stations, but: 'module' object has no attribute 'normalize_and_merge_duplicate_stations'**

while running any of these requests
    **http://localhost:8080/buildings/16/19293/24641.json
    http://localhost:8080/buildings/16/19293/24641.mvt
    http://localhost:8080/all/16/19293/24641.json**

Please see below for console output (I'm attaching a screenshot as well).

The workaround was to comment out TileStache.Goodies.VecTiles.transform.normalize_and_merge_duplicate_stations function from queries.yaml. It worked but obviously that's not how you want to get it fixed.

Thank you for doing such a great job on Mapzen!

![knownunknown](https://cloud.githubusercontent.com/assets/17868769/13801972/761fcdd0-eaf4-11e5-8d51-c568a903ef69.png)

127.0.0.1 - - [15/Mar/2016 20:31:47] "GET /buildings/16/19293/24641.mvt HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/john/Documents/application/tileserver/tileserver/**init**.py", line 188, in **call**
    response = self.handle_request(request)
  File "/home/john/Documents/application/tileserver/tileserver/**init**.py", line 284, in handle_request
    [], [])
  File "/home/john/Documents/application/env/lib/python2.7/site-packages/tilequeue/process.py", line 391, in process_coord
    padded_bounds, scale, layers_to_format)
  File "/home/john/Documents/application/env/lib/python2.7/site-packages/tilequeue/process.py", line 326, in _process_feature_layers
    padded_bounds)
  File "/home/john/Documents/application/env/lib/python2.7/site-packages/tilequeue/process.py", line 83, in _postprocess_data
    fn = loadClassPath(step['fn_name'])
  File "/home/john/Documents/application/env/lib/python2.7/site-packages/TileStache/Config.py", line 497, in loadClassPath
    raise Core.KnownUnknown('Tried to import %s, but: %s' % ('.'.join(classpath), e))
KnownUnknown: Tried to import TileStache.Goodies.VecTiles.transform.normalize_and_merge_duplicate_stations, but: 'module' object has no attribute 'normalize_and_merge_duplicate_stations'
127.0.0.1 - - [15/Mar/2016 20:31:47] "GET /buildings/16/19293/24641.mvt?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [15/Mar/2016 20:31:47] "GET /buildings/16/19293/24641.mvt?**debugger**=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [15/Mar/2016 20:31:47] "GET /buildings/16/19293/24641.mvt?**debugger**=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [15/Mar/2016 20:31:47] "GET /buildings/16/19293/24641.mvt?**debugger**=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [15/Mar/2016 20:31:47] "GET /buildings/16/19293/24641.mvt?**debugger**=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [15/Mar/2016 20:31:47] "GET /buildings/16/19293/24641.mvt?**debugger**=yes&cmd=resource&f=source.png HTTP/1.1" 200 -

**Comment by nvkelso** [comment]
Related: https://github.com/mapzen/vector-datasource/pull/608/files.

**Comment by zerebubuth** [comment]
Hi @kalynaa!

Sorry about this - there were linked PRs in both the TileStache repo (mapzen/TileStache#130) and this repo (#607), and it looks like you managed to get the former but not the latter. They are both up to date now, and as @nvkelso mentioned a further bug fixed, so please try updating to the latest versions of the vector-datasource and TileStache repos and try again.
