### ISSUE TITLE
More simplification to roads & boundary layers at zoom 9

### ISSUE THREAD

**Issue by zerebubuth** [tilezen/vector-datasource#641]
Context, [this comment](https://github.com/mapzen/vector-datasource/issues/583#issuecomment-202573059):

> I suspect the `roads` and `boundary` layers need additional geom simplifying. 
> 
> We could also strip some properties off the boundary layer at low zooms (like `name` and the name variants) at zooms less than 8 as the zoom isn't large enough to provide screen space to do the labeling.
> 
> ![screen shot 2016-03-28 at 13 35 53](https://cloud.githubusercontent.com/assets/853051/14089500/04a88642-f4ea-11e5-8c8c-ede2258343d3.png)
> 
> ![screen shot 2016-03-28 at 13 35 24](https://cloud.githubusercontent.com/assets/853051/14089488/fa3fa9d8-f4e9-11e5-989a-7f199ab53d3d.png)

@nvkelso: what would be an appropriate level of simplification for the roads & boundaries features?

**Comment by nvkelso** [comment]
This will be needed at both zoom 8 and 9 if we do the earlier NE to OSM switchover.

**Comment by nvkelso** [comment]
Let's try doubling the existing simplification and review.

**Comment by nvkelso** [comment]
We didn't see a huge drop in file size from this, but it did reveal an interesting bug we fixed.

No visual impact, closing.
