### ISSUE TITLE
Remove `osm/` from default tile URL path

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#652]
We use several different data providers in our tiles, calling these `osm/` is not accurate. Either we drop it or replace it with another name.

Proposed:
`url: https://vector.mapzen.com/all/{z}/{x}/{y}.topojson`
or
`url: https://vector.mapzen.com/newname/all/{z}/{x}/{y}.topojson`

Existing:
`url: https://vector.mapzen.com/osm/all/{z}/{x}/{y}.topojson`

Still support the old syntax, though (especially for the archived v0.7, v0.8, & etc tile sets).

**Comment by zerebubuth** [comment]
It's 99.89% OSM by size, which means calling it "osm" is accurate. However, because we label each data item with a source, it's superfluous to name the dataset as well. My first thought was to drop the prefix completely, but perhaps we should think about what the most appropriate way is to handle tilesets with default "extra" data baked in: Is it preferable to have additional "meta-layers" like `all`, or use a different prefix?

**Comment by nvkelso** [comment]
Redirect users asking for the `osm` prefix to the no-prefix version.

**Comment by nvkelso** [comment]
Or: `https://tile.mapzen.com/vector/v1/all/{z}/{x}/{y}.topojson`

**Comment by nvkelso** [comment]
`https://tile.mapzen.com/raster/normal/v1/all/{z}/{x}/{y}.png`

**Comment by nvkelso** [comment]
`https://tile.mapzen.com/neat/v1/all/{z}/{x}/{y}.topojson`

**Comment by nvkelso** [comment]
Drop raster, `https://tile.mapzen.com/normal/v1/all/{z}/{x}/{y}.png`

**Comment by bcamper** [comment]
This is heading in a logical direction. Not sure `all` make sense for raster tiles (or at least normals/elevation, maybe it would for rendered rasters if we ever did that)?

**Comment by nvkelso** [comment]
Yep.

* `https://tile.mapzen.com/vector/v1/all/{z}/{x}/{y}.topojson`
* `https://tile.mapzen.com/neat/v1/{z}/{x}/{y}.neat`
* `https://tile.mapzen.com/normal/v1/{z}/{x}/{y}.png`

**Comment by rmarianski** [comment]
@nvkelso should the tilejson urls look like this?

    https://tile.mapzen.com/vector/v1/tilejson/mapbox.json

**Comment by nvkelso** [comment]
Working for me.

**Comment by nvkelso** [comment]
As discussed in the tiles meeting today, we should add a **user account** part to the URL pattern:

General pattern:

- `https://tile.mapzen.com/{username}/{projectname}/v{versionnumber}/{optional_layername}/{z}/{x}/{y}.{format}`

Specific examples:

- `https://tile.mapzen.com/mapzen/vector/v1/all/{z}/{x}/{y}.topojson`
- `https://tile.mapzen.com/mapzen/terrain/v1/normal/{z}/{x}/{y}.png`
- `https://tile.mapzen.com/mapzen/neat/v1/{z}/{x}/{y}.neat`

And we're still searching for a better name besides `vector` for the default basemap project.

**Comment by nvkelso** [comment]
We should track any additional work for final production deploy in https://github.com/mapzen/tile-tasks/issues/94.

**Comment by nvkelso** [comment]
Confirmed with product & documentation teams that we'll stick with `vector` as the project name for v1 launch. There isn't a compelling alternative & there's cost of getting people to adopt whatever the new thing might have been.

**Comment by nvkelso** [comment]
Nothing more to do here.
