### ISSUE TITLE
Extend WOF neighbourhoods to include new borough placetype

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#654]
`borough` features were recently added for NYC (something between localadmin and macrohood), and in the neighbourhood class of features. Let's update the WOF neighbourhood logic in tiles to pass these features thru, too.

**Comment by nvkelso** [comment]
I mean, what's not to like about `name:tam: "இசுட்டேட்டன் தீவு",` for Staten Island?!

**Comment by nvkelso** [comment]
Well, that's actually on a neighbourhood feature. And I can't find Brooklyn either. 

@rmarianski Is there a test verifying this works? When I look upstream at WOF for say [Brooklyn](https://whosonfirst.mapzen.com/spelunker/id/421205765/#11/40.6529/-73.9379) it seems like it aught to come thru, but maybe the data isn't configured correctly?

**Comment by rmarianski** [comment]
It's in there? http://tile.dev.mapzen.com/vector/v1/all/16/19307/24658.topojson

**Comment by nvkelso** [comment]
Ah, I see. Confirmed.

What's happening here is the `mz:min_zoom` property is not present upstream in Who's On First so we default the zoom to 15 (and I was looking in the earlier tile where the old junk "neighbourhood" is). Tracking the upstream data fix in https://github.com/whosonfirst-data/whosonfirst-data/issues/441.
