### ISSUE TITLE
Don't include historic transit stops

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#661]
Looks like there's another use case around historic transit features we need to guard against. 

* **What did you see?** A `kind:stop` feature in NYC for a stop that isn't in service, it's marked `historic=yes` at OSM.org. 
* **What did you expect to see?** This feature shouldn't be included in tiles at all. It hasn't had service in a long time. We should only be showing current transit in our tiles.
* **What map location are you having problems with?** [node 3039734895](https://www.openstreetmap.org/node/3039734895) in NYC at 5th Av and 3rd St.
* **Screenshot?** 

<img width="682" alt="screen shot 2016-04-03 at 21 17 59" src="https://cloud.githubusercontent.com/assets/853051/14238103/9ca23456-f9e1-11e5-949f-173f65a3f038.png">

/cc @bcamper

**Comment by nvkelso** [comment]
Moving to next release for load balancing.

**Comment by okavvada** [comment]
* Does this refer to transit stops only or all transit features?
* `railway: stop` is included in both the `transit.yaml` and the `pois.yaml`. Do we want to _not include_ both layers if historic?
* Is it limited to `historic=yes`? or any `historic` tag value? example from [TagInfo](https://taginfo.openstreetmap.org/keys/historic#values):
`historic = yes`, `historic = railway`, `historic = railway_station`

**Comment by nvkelso** [comment]
* Stops & stations only (generally all points, but not rail lines). We've only had reports of points, so let's keep this issue scoped to that.
* Yes, filter it out in both layers.
* Good TagInfo sleuthing, let's black list all 3 of those values.

**Comment by okavvada** [comment]
No instances of historic tags in the transit layer, so it is not included in the filtering process. The filtering exists for the pois layer for features in railway: [stop, halt, tram_stop] with historic: [yes, railway_station].

**Comment by nvkelso** [comment]
Good sleuthing!

**Comment by nvkelso** [comment]
Erased!

![image](https://cloud.githubusercontent.com/assets/853051/17960551/9a9efb36-6a5b-11e6-8c45-d6bd1e538e55.png)
