### ISSUE TITLE
Add highway=raceway to roads layer

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#664]
- [x] [highway=raceway](http://wiki.openstreetmap.org/wiki/Tag:highway%3Draceway), [roads](https://www.openstreetmap.org/way/28825404) and [2](https://www.openstreetmap.org/way/59440900), init zoom 13. Around 15,000.

**Comment by nvkelso** [comment]
I think this would be in the general (default) `kind:minor_road` High Road classification.

**Comment by rmarianski** [comment]
We do have a kind for `racetrack`. Should this also get that kind? Or are those completely separate?

Any thoughts for the `sort_key`? Or will the default work?

**Comment by nvkelso** [comment]
> We do have a kind for racetrack. Should this also get that kind? Or are those completely separate?

Different kind. Racetrack is more for people running. Raceway is for cars driving fast. 

We need docs, starting that work with:

* https://github.com/mapzen/vector-datasource/issues/802
* https://github.com/mapzen/vector-datasource/issues/803

> Any thoughts for the sort_key? Or will the default work?

It should probably get it's own. We're putting it in minor_road, but sometimes shouldn't be symbolized like that (and would z-fight tilted). Propose something? Might impact a few tests :\ So bundle up with #605?

**Comment by rmarianski** [comment]
> It should probably get it's own. We're putting it in minor_road, but sometimes shouldn't be symbolized like that (and would z-fight tilted). Propose something? Might impact a few tests :\ So bundle up with #605?

I made the sort_key one higher than links, and bumped those down one in 038d56d.

**Comment by nvkelso** [comment]
LGTM
