### ISSUE TITLE
Normalize ne places kind with osm values

### ISSUE THREAD

**Issue by rmarianski** [tilezen/vector-datasource#701]
The `kind` values on `places` coming from natural earth should be normalized with osm values.

**Comment by rmarianski** [comment]
Should just be matter of updating the `kind` values in the [yaml](https://github.com/mapzen/vector-datasource/blob/e66cdd2c076ed0e537dbac3f0d5a056500674153/yaml/places.yaml#L58-L89).

**Comment by nvkelso** [comment]
For all, we still want to preserve the original Natural Earth value as `subkind`.

##### OSM uses a population size lookup to generally declare the kind of place:
http://wiki.openstreetmap.org/wiki/Key:place

* population >= 100,000 then `kind:city`
* population < 100,000,  population >= 10,000 then `kind:town`
* population < 10,000,  population >= 500 then `kind:village`
* population < 500 then `kind:hamlet`

##### Without the lookup:

* `Admin-0 region capital` > `city` with `capital`:`yes`
* `Admin-0 capital alt` > `city` with `capital`:`yes`
* `Admin-1 capital` > `city` with `state_capital`:`yes`
* `Admin-1 region capital` > `city` with `state_capital`:`yes`
* `Historic place` > `hamlet`
* `Populated place` > `hamlet` (all but McMurdo are less than 300 people)
* `Admin-0 capital` > `city` with `capital`:`yes`
* `Scientific station` > `hamlet` (all but McMurdo are less than 300 people)

##### Capital assignment is currently in TileStache transform:

https://github.com/mapzen/TileStache/blob/integration-1/TileStache/Goodies/VecTiles/transform.py#L326-L334

```
def place_ne_capital(shape, properties, fid, zoom):
    source = properties.get('source', '')
    if source == 'naturalearthdata.com':
        kind = properties.get('kind', '')
        if kind == 'Admin-0 capital':
            properties['capital'] = 'yes'
        elif kind == 'Admin-1 capital':
            properties['state_capital'] = 'yes'
    return shape, properties, fid
```

**Comment by rmarianski** [comment]
> Capital assignment is currently in TileStache transform

Nice catch! We should remove the TileStache transform as part of this work because the yaml output syntax should support generating it directly.

**Comment by zerebubuth** [comment]
Assigning `kind`, or anything else, based on `population` is completely bogus. We should just rely on the information coming from OSM `place` or NE `featurecla` and update the data upstream if it's wrong.

The `places` layer got caught between the shuffle of converting to CSV and converting to YAML, so we should definitely revisit it now that we've got the ability to add `capital` and extra properties like that.

**Comment by nvkelso** [comment]
Agree we shouldn't mess with OSM data & that should be fixed upstream. But we do want to normalize all the kinds so they are interoperable – for Natural Earth this means adopting more the OSM style `kind`s. Primarily we look at the population values directly to do styling, so I'm fine with skipping the conditional Natural Earth kind transform based on the population values and do the 2nd option (e.g.: `Admin-0 region capital` > `city` with `capital:yes`). Seems like that would work better with the new YAML, too. (Natural Earth isn't going to adopt OSM's `place` tagging, just the same as OSM not adopting WOF tagging – we need to normalize these in our tiles for users.) Updated guidance above.

**Comment by nvkelso** [comment]
This requires coordination with all the house styles so city labels remain on the map, moving to next release due to coordination timing issues.

**Comment by nvkelso** [comment]
This was changed again in the city > locality patch, but it's working.
