### ISSUE TITLE
`park or protected area` and `urban area` landuse kinds from NE needs normalized values

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#713]
These are all National Parks, they should get similar tags as the OSM features of the same class.

**Comment by nvkelso** [comment]
Moving to next release for load balancing.

**Comment by zerebubuth** [comment]
Could you give an example of this, please? I tried looking, but I couldn't find one, and it seems the low zoom landuse areas are coming from OSM anyway (apart from the `urban area` polygons). For example, in tile `5/5/12`, I couldn't find any non-OSM ones:

```
$ curl -s http://vector.dev.mapzen.com/osm/landuse/5/5/12.json | \
  jq '.features[].properties.kind' | sort | uniq -c
    225 "national_park"
     51 "nature_reserve"
    831 "protected_area"
     23 "urban area"
```

**Comment by zerebubuth** [comment]
`urban area` is coming from [this query](https://github.com/mapzen/vector-datasource/blob/master/queries/landuse.jinja2#L47-L54) in `landuse`. Changing what it's called should be a simple matter of changing the string there - I don't think we do any further processing to it.

**Comment by nvkelso** [comment]
Verified on dev.
