### ISSUE TITLE
Consider moving some POIs to new infrastructure, other layers

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#715]
Following up from discussion in https://github.com/mapzen/vector-datasource/pull/706, if we create a new `infrastructure` layer for putting power lines, gas lines and other "utility" infrastructure, should we also move some of the related POIs into the same layer, or leave them in the `pois` layer?

For instance, `power_pole` and `power_tower` are paired with power lines. 

But there are many other values that could be included (maybe they should, maybe they shouldn't). For instance: 

* should all `man_made` features go here? 
* `bbq`
* `amenity: life_ring`
* `amenity: picnic_table`

**The pro:** Moving features into a dedicated infrastructure layer would mean there's less chance of them getting displayed mixed in with regular business pois, but...

**The con:** it also increases the complexity of where to find things to build the map style. 

We had been discussing centralizing even more "poi" like features into the pois layer – we do this now for shops and other tags present on buildings, we peal those off and put them into the pois layer leaving only (icon-less) label placements behind. But in the landuse layer label placements should generally have icons so we already mix this up a bit.

Where would features like amenity: bbq and amenity: life_ring and amenity: picnic_table go? Seems like most of these features could just go into an infrastructure layer just as well as a pois layer. Sure they have an amenity tag from OSM, but looking at it not knowing the history it's not clear. Less layers seems better.

**Comment by zerebubuth** [comment]
I've found it useful to imagine that someone has a style which renders everything in the `pois` layer with at least a generic POI icon, and then thinking whether it would make sense for something (e.g: a power pole) to show up as a generic POI.

Personally, I think BBQs and picnic tables would fit that "generic POI" description, although it's definitely a grey area. But I think showing a power pole or pylon as a generic POI would be pretty confusing.

It's a bit like when we added ferries to the `roads` layer, and some styles were showing everything in the roads layer as a generic road, so it looked a bit odd. I think it's useful to imagine the same situation for POIs.

**Comment by nvkelso** [comment]
Straw man proposal:

# `infrastructure` related, move to new layer?

* `adit`
* `bbq`
* `beacon`
* `bench`
* `block`
* `bollard`
* `communications_tower`
* `cross`
* `drinking_water`
* `emergency_phone`
* `ford`
* `gate`
* `halt`
* `hazard`
* `level_crossing`
* `life_ring`
* `lifeguard_tower`
* `lift_gate`
* `lock`
* `mast`
* `maze`
* `memorial`
* `mineshaft`
* `mini_roundabout`
* `motorway_junction`
* `offshore_platform`
* `petroleum_well`
* `phone`
* `picnic_table`
* `post_box`
* `power_pole`
* `power_tower`
* `power_wind`
* `pylon`
* `recycling`
* `shower`
* `waste_basket`
* `waste_disposal`
* `water_point`
* `water_tower`
* `water_well`
* `watering_place`
* `windmill`

# move to `landuse` layer?

* `tree`

# move to `earth` layer?

* `cave_entrance`
* `peak`
* `rock`
* `saddle`
* `sinkhole`
* `stone`
* `volcano`

¿Should some of the polygon "natural" values currently in the `landuse` layer move to `earth` as well?

# move to `water` layer?

* `rapid`
* `spring`

# places that are destinations in their own right, stay in `pois` layer

* `alpine_hut`
* `amusement_ride`
* `animal`
* `artwork`
* `atm`
* `attraction`
* `aviary`
* `carousel`
* `dune`
* `egress`
* `enclosure`
* `fishing`
* `geyser` - but it's water related
* `hot_spring` - but it's water related
* `information`
* `landmark`
* `lighthouse`
* `put_in_egress`
* `put_in`
* `slipway`
* `snow_cannon`
* `summer_toboggan`
* `toilets`
* `traffic_signals`
* `trailhead`
* `viewpoint`
* `wilderness_hut`
* `water_slide`

# transportation related, used enough to stay in `pois` layer?

* `bicycle_parking`
* `bicycle_repair_station`
* `bus_stop`
* `car_sharing`
* `tram_stop`

**Comment by nvkelso** [comment]
Process changed.
