### ISSUE TITLE
Transit layer's route_name should be simply name

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#729]
* http://vector.mapzen.com/osm/all/12/654/1584.topojson

The convention in Mapzen vector tiles is to have `name` regardless of source OSM feature type. But I see `route_name` on all transit line features.

(In this case we also indicate that `"osm_relation": true,` on these features already.)

**Example 1:**

```
{
"colour":
"#008752",
"id":
-3433314,
"kind":
"light_rail",
"operator":
"San Francisco Municipal Railway",
"osm_relation":
true,
"ref":
"M",
"route_name":
"M-Ocean View: Outbound to Balboa Park",
"sort_key":
418
},
"type":
"LineString"
```

**Example 2:**

```
{
"colour":
"red",
"id":
-2851509,
"kind":
"subway",
"operator":
"BART",
"osm_relation":
true,
"ref":
"Red",
"route_name":
"Richmond-Daly City",
"sort_key":
275
},
"type":
"LineString"
},
```

**Comment by rmarianski** [comment]
We have a [transform](https://github.com/mapzen/TileStache/blob/0019a2d3a004dac780635f27aa7df17096f7bb61/TileStache/Goodies/VecTiles/transform.py#L279-L285) that removes `route_name` from the results if it's the same as `name`. Presumably there are cases where `route_name` is not the same value as `name`?

How about:
* if `route_name` exists but not `name` -> move to `name`
* if `name` exists and equals `route_name` -> drop `route_name`
* if both exist and are different -> keep both

We have this transform configured for the `roads` layer too.

**Comment by nvkelso** [comment]
Sounds good to me :)

**Comment by nvkelso** [comment]
Working
