### ISSUE TITLE
force protect_class to be an integer

### ISSUE THREAD

**Issue by rmarianski** [tilezen/vector-datasource#747]
The protect_class tag looks to [always be an integer value](http://taginfo.openstreetmap.org/keys/protect_class#values). Should we coerce it to an integer in the output in the `landuse` layer?

**Comment by nvkelso** [comment]
Maybe: I see 1A and 1B values in there. Need to research if those should just be `1` or something else.

**Comment by nvkelso** [comment]
This has been an issue for a while. Suggest holding off on fix until next release to this release gets out the door.

**Comment by nvkelso** [comment]
From the [wiki](http://wiki.openstreetmap.org/wiki/Tag:boundary%3Dprotected_area):

- `1a` **Strict Nature Reserve:** ... strictly protected areas ... are strictly controlled and limited ... can serve as indispensable reference areas for scientific research and monitoring.
- `1b` **Wilderness Area:** ... usually large unmodified or slightly modified areas, retaining their natural character and influence within permanent or significant human habitation, ...
You can keep them apart by an additional zone-Tag.

Don't think we need to sort this out for v1, moving to v1.1

**Comment by nvkelso** [comment]
Non-int values are allowed, closing.
