### ISSUE TITLE
Project walking route ref onto roads and paths

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#775]
- **What did you see?** Many hiking paths are grouped into relations which have `ref` values, but no `ref` value on the way. The trail's `ref` is the primary method of way finding in this mountain area.
- **What did you expect to see?** I expect to see the relation's `ref` value on the way.
- **What map location are you having problems with?** 
  - https://www.openstreetmap.org/way/127908481
  - https://www.openstreetmap.org/relation/103942

**Comment by nvkelso** [comment]
Followup to: https://github.com/mapzen/vector-datasource/issues/596.

**Comment by nvkelso** [comment]
<img width="1146" alt="screen shot 2016-04-30 at 08 33 39" src="https://cloud.githubusercontent.com/assets/853051/14934362/467c5e58-0eae-11e6-96ac-601a7d72b26e.png">

**Comment by zerebubuth** [comment]
At the moment, we get `mz_networks` from the relations for some road types, which can end up populating the `network` property of the feature. Where we use `mz_networks` we ignore the `network` tag, if present, and set it from the "most important" network from the relations. However, we keep the `ref` tag, even though it might have referred to a network that we ignored.

There are `walking_network` properties, which are fetched from the relations, but only the "most important" single network. The `network` property on lower grade roads is set from the tag, which may or may not be the same as the `walking_network` network. The `ref` will be left as-is.

Does it make sense to rationalise all of these by including the `network` and `ref` from the way along with all the other `network` and `ref` values from the relations, and always setting `network` and `ref` from the "most important" network?

That approach might break a bunch of things, though. :worried:

**Comment by nvkelso** [comment]
Can we isolate the car, walking, cycling refs into their own shield names spaces?

So a way's `walking_network` relation has a ref, than it'd show up as `walking_shield_text` on the way.

And a way's `bicycle_network` relation has a ref, than it'd show up as `bicycle_shield_text` on the way.

**Comment by nvkelso** [comment]
This way has 3 different walking networks:

- https://www.openstreetmap.org/way/373532611
- `JMT`, `PCT`, and ` ` some weird section thing without a ref.

This way has cycle, bus, and driving networks!

- https://www.openstreetmap.org/way/417097119
- `23` (bus), `50` (bicycle), and `35` (driving)

**Comment by zerebubuth** [comment]
Yup, good point.

What I was trying to get at is that if the way itself has `network=lwn`, `ref=1` and it's part of a walking route relation with `network=rwn`, `ref=10`, then would we want `all_walking_networks=['rwn','lwn']` and `all_walking_shield_text=['10','1']`?

At the moment, we'd leave the `ref=1` on the way, which seems confusing to me, given that the `walking_network` would be `rwn`. Would it be better to set the `ref` to the same as `shield_text` (or `walking_shield_text` / `bicycle_shield_text`), or remove it in favour of `shield_text`?

**Comment by nvkelso** [comment]
Re: https://github.com/tilezen/vector-datasource/issues/775#issuecomment-292104415, I'm fine following the same convention we've used for road shields. If there's time, the extra logic you describe is better though (and I saw this type of dual / confusing tagging in Washington DC just this week editing OpenStreetMap).

**Comment by nvkelso** [comment]
I've been able to verify this I think because most of the test locations weren't pre-cached.

@zerebubuth For the [Pacific Crest Trail example](https://www.openstreetmap.org/way/373532611) it looks like we're duplicating the way's ref and network with one of the relations that has the same exact details. I don't think we do that for roads, is it possible to dedup here as well?

**Comment by nvkelso** [comment]
Verified :)

<img width="599" alt="screen shot 2017-04-19 at 22 50 13" src="https://cloud.githubusercontent.com/assets/853051/25215483/aba9b2c4-2552-11e7-81fb-eff8000e0573.png">
<img width="458" alt="screen shot 2017-04-19 at 22 48 34" src="https://cloud.githubusercontent.com/assets/853051/25215481/aba7c20c-2552-11e7-9000-f044be946358.png">
<img width="688" alt="screen shot 2017-04-19 at 22 43 23" src="https://cloud.githubusercontent.com/assets/853051/25215479/aba6d040-2552-11e7-82fe-d87b26f106ec.png">
<img width="762" alt="screen shot 2017-04-19 at 22 43 10" src="https://cloud.githubusercontent.com/assets/853051/25215480/aba75dee-2552-11e7-9e09-caafbfb37a11.png">
<img width="679" alt="screen shot 2017-04-19 at 22 53 29" src="https://cloud.githubusercontent.com/assets/853051/25215534/0af49898-2553-11e7-8975-55a19ccd958a.png">
