### ISSUE TITLE
Normalize cycleway (& left, right, both variant) values & oneway

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#782]
1. Looking at the values in `cycleway`, `cycleway:left`, `cycleway:right`, and `cycleway:both`, there are **some values that should be whitelisted, blacklisted, or normalized.**
   - http://taginfo.openstreetmap.org/keys/cycleway#values
   - http://taginfo.openstreetmap.org/keys/cycleway:left#values
   - http://taginfo.openstreetmap.org/keys/cycleway:right#values
   - http://taginfo.openstreetmap.org/keys/cycleway:both#values
   - http://wiki.openstreetmap.org/wiki/Bicycle
   - http://taginfo.openstreetmap.org/keys/cycleway#values
2. Another complication: **sometimes the variants can add up to something that should end up in cyclewa**y (e.g.: if cycleway:left=yes and cycleway:right=yes, then really it's just cycleway=yes). 
3. Similarly, seems like the `oneway:bicycle=no` thing is to counteract when the parent road is oneway:yes (to mean the cycleway is bidirectional and both directions probably on one side of the road).

**Comment by nvkelso** [comment]
@rmarianski Did we complete this already in the v0.10 work?

**Comment by rmarianski** [comment]
I think what's still [outstanding](https://github.com/mapzen/vector-datasource/pull/760#discussion_r61763296) is figuring out what we want to do for all combinations of the `oneway` tag and the `bicycle:oneway` tag when they both exist on the element.

**Comment by nvkelso** [comment]
Nominating for v1.1

**Comment by nvkelso** [comment]
This is working as is.
