### ISSUE TITLE
Convert sort_key tests to use a generative approach

### ISSUE THREAD

**Issue by rmarianski** [tilezen/vector-datasource#805]
At the moment, we're adding tests to verify `sort_key`s in the high level vector-datasource tests. This makes them brittle though, because any time we change the ordering, all affected tests need to get updated.

What we really care about is the relative ordering between the different kinds of features. We can take a generative testing approach where the relative orderings would be our properties or invariants.

**Comment by nvkelso** [comment]
Replaced by https://github.com/tilezen/vector-datasource/issues/1823.
