### ISSUE TITLE
TileStache.Core.KnownUnknown

### ISSUE THREAD

**Issue by jojoaddison** [tilezen/vector-datasource#807]
Traceback (most recent call last):
  File "/home/jack/tileserver/tileserver/**init**.py", line 190, in **call**
    response = self.handle_request(request)
  File "/home/jack/tileserver/tileserver/**init**.py", line 286, in handle_request
    [], [])
  File "/home/jack/env/lib/python2.7/site-packages/tilequeue/process.py", line 399, in process_coord
    padded_bounds, scale, layers_to_format)
  File "/home/jack/env/lib/python2.7/site-packages/tilequeue/process.py", line 305, in _process_feature_layers
    transform_fns = resolve_transform_fns(transform_fn_names)
  File "/home/jack/env/lib/python2.7/site-packages/TileStache/Goodies/VecTiles/server.py", line 53, in resolve_transform_fns
    return map(loadClassPath, fn_dotted_names)
  File "/home/jack/env/lib/python2.7/site-packages/TileStache/Config.py", line 497, in loadClassPath
    raise Core.KnownUnknown('Tried to import %s, but: %s' % ('.'.join(classpath), e))
KnownUnknown: Tried to import TileStache.Goodies.VecTiles.transform.boundary_kind, but: 'module' object has no attribute 'boundary_kind'

After a fresh installation of vector-datasource and tileserver, I run into this error.

Am using mapzen extracts for accra ghana.
https://s3.amazonaws.com/metro-extracts.mapzen.com/accra_ghana.osm.pbf

Thank you

**Comment by rmarianski** [comment]
Looks like you're not picking up the [integration-1 branch of the mapzen fork of tilestache](https://github.com/mapzen/TileStache). Can you verify that's the case on your pythonpath?

`python -c 'import TileStache; print TileStache.__file__'`

That should print out the location of the mapzen fork.

**Comment by jojoaddison** [comment]
Hello Guys,

Thanks a million for your support efforts.

`python -c 'import TileStache; print TileStache.__file__'`
Returns:
`/home/jack/tileserver/env/local/lib/python2.7/site-packages/TileStache/__init__.pyc`

![vector-tileserver-shot](https://cloud.githubusercontent.com/assets/4488104/15180067/ae6f3d62-177f-11e6-8040-f94980ba90a4.png)


As in screenshot above

**Comment by rmarianski** [comment]
I had originally thought that the version of tilestache was out of date, but it seems like it might be vector-datasource. Can you check to see if you're using the latest version of vector-datasource? Specifically in the queries.yaml file, there shouldn't be a reference to `boundary_kind`.

**Comment by jojoaddison** [comment]
Hello @rmarianski,
Thank you very much for your insight. 
The version of vector-datasource am using has reference to `boundary_kind`.

![vector-datasource-error-boundary_kind](https://cloud.githubusercontent.com/assets/4488104/15212756/e8cbf8f6-1842-11e6-8af3-33fff1967dfb.jpg)


I will update to the latest version and return my feedback.

**Comment by nvkelso** [comment]
We haven't used TileStache for quite some time, closing.
