### ISSUE TITLE
Normalize place layer kinds

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#840]
In preparation for our v1.0 release I've been auditing `kind` values across all the layers.

The `places` layer need some normalizing to `region` for administrative subdivisions and `locality` for city like things. We'll use the new `kind_detail` property to store the raw OSM values.

```
tile_layer	tile_kind	tile_kind_detail	osm_key	osm_value	old_tile_kind
places	region	state	place	state	state
places	region	province	place	province	province
places	locality	city	place	city	city
places	locality	town	place	town	town
places	locality	village	place	village	village
places	locality	hamlet	place	hamlet	hamlet
places	locality	locality	place	locality	locality
places	locality	isolated_dwelling	place	isolated_dwelling	isolated_dwelling
places	locality	farm	place	farm	farm
```

**Comment by rmarianski** [comment]
@nvkelso what should we do, if anything, for the other places we have configured to pull in? Do we want to normalize those too?

osm data:

* country
* borough
* suburb
* quarter

For ne data, specifically the capitals, we always assign `kind: city`, and then add in either `capital: true` or `state_capital: true`. Then, for historic places and scientific places we assign `kind: hamlet`.

**Comment by nvkelso** [comment]
Removing `borough`, `suburb`, and `quarter` is covered in https://github.com/tilezen/vector-datasource/issues/744. That issue wasn't marked breaking (to your point earlier today!), it is now.

`country` remains a valid `kind` value. 

The Natural Earth data assignments should go to `kind: locality` with the capital stuff modified to say `region_capital: true` For historic places and scientific places I think the kind would be `locality` with `subkind: hamlet`? Or just ditch the subkind for that one?

**Comment by rmarianski** [comment]
> Removing borough, suburb, and quarter is covered in #744. That issue wasn't marked breaking (to your point earlier today!), it is now.

Ah, I forgot about that. Sounds good.

> `country` remains a valid kind value. 

Cool, I'll leave it be since it sounds like it doesn't need any `kind_detail` value.

> The Natural Earth data assignments should go to kind: locality with the capital stuff modified to say region_capital: true

Do you think it's worth trying to normalize it with the osm scheme? We could say: `kind: locality, kind_detail: region_capital` and maybe something like `kind: locality, kind_detail: state_capital`?

> For historic places and scientific places I think the kind would be locality with subkind: hamlet? Or just ditch the subkind for that one?

Yea, I like that for consistency with the rest `kind: locality, kind_detail: hamlet`.

**Comment by nvkelso** [comment]
Let’s keep the existing (separate) capital logic & properties. It works
better with cascading stylesheets client-side.

**Comment by nvkelso** [comment]
We did this for OSM places in #891, but we forgot to do it for NE places. So that's not on dev, but Olga did the work in https://github.com/tilezen/vector-datasource/commit/71bcda642c0892ae8cbc766b2900def5893d6ac5 so we're good overall.
