### ISSUE TITLE
Normalize boundaries layer kind & kind_detail values

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#841]
In preparation for our v1.0 release I've been auditing kind values across all the layers.

1) The `boundaries` layer need some normalizing to `region` for administrative subdivisions and `locality` for city like things:

```
tile_layer	tile_kind	tile_kind_detail	osm_key	osm_value	old_tile_kind
boundaries	region	4	admin_level	4	state
boundaries	locality	8	admin_level	8	municipality
```

2) We'll use the new `kind_detail` property to store the admin_level from OSM and that we sometimes calculate. Set the `kind_detail` value of the following to `2` as they are "country" related:

- disputed
- indefinite
- indeterminate
- country
- lease_limit
- line_of_control
- overlay_limit

**Related:** `places` layer kinds https://github.com/mapzen/vector-datasource/issues/840.

**Comment by nvkelso** [comment]
Related: https://github.com/mapzen/vector-datasource/issues/842

**Comment by rmarianski** [comment]
Are we removing `admin_level` throughout and naming it `kind_detail`?

**Comment by nvkelso** [comment]
Yes, putting the `admin_level` into `kind_detail` and then dropping `admin_level`.

**Comment by rmarianski** [comment]
@nvkelso what should the `kind_detail` be for `macroregion`? `2`?

**Comment by nvkelso** [comment]
Macroregion is between country and region so `3`?

**Comment by nvkelso** [comment]
Verified.
