### ISSUE TITLE
Cleanup POI kind filters (remove dups, rename, and remove totally)

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#844]
The following `kind` filters are specified 2 or more times. We should remove the later instances:

- `amenity=boat_storage`
- `shop=dry_cleaning`
- `leisure=firepit`
- `craft=sawmill`
- `craft=sawmill` (yes, it's in there 3 times!!!)
- `amenity=theatre`
- `amenity=toilets`
- `craft=winery`
- `craft=brewery`

The following `kind` filters specify should specify a different output `kind`:

- `shop=gas` should output `kind:gas_canister` (was `gas`)
- `aeroway=gate` should output `kind:aeroway_gate` (was `gate`)
- `rental=ski` should output `kind:ski_rental` (was `ski`)
- `iwn_ref=TRUE`  should output `kind:walking_junction` with `kind_detail:iwn` (was `kind_detail:rwn`)
- `landuse=wood` should  output `kind:wood_landuse` to differentiate it from the `natural=wood` value. This has caught us up several times (see Stanley Park in Vancouver and at Mt Diablo east of SF). Or maybe we should just normalize it to `kind:park` since that seems to be how it is used? 
- ¿`kind=park` is also ambiguous from the `landuse` or `natural` tags. But in this case I think it's ok to coalesce them?

The following `kind` filters specify a OSM feature that is essentially non-existent and we should remove it: 

- `highway=gate` (we already support `barrier=gate` which is the recommended usage)
- `amenity=picnic_site` (we already support several other ways of specifying this)

**Comment by nvkelso** [comment]
* `landuse=wood` = `kind:wood`
* `natural=wood` = `kind:natural_wood`
* `landuse=forest` = `kind:forest`
* `natural=forest` = `kind:natural_forest`
* `landuse=park` = `kind:park`
* `natural=park` = `kind:natural_park` – this is probably bogus, research and consider blacklisting.

**Comment by rmarianski** [comment]
@nvkelso couple of questions that came up while I was implementing:

1. You mentioned `kind_detail` for the iwn change above. The yaml currently calls it `walking_network`. Should I replace `walking_network` -> `kind_detail` too as part of this pr?

2. For the landuse/natural updates, there are some instances where *both* are set, eg `natural=wood` *and* `landuse=wood`. Which should take precedence?

**Comment by nvkelso** [comment]
> 1) You mentioned kind_detail for the iwn change above. The yaml currently calls it walking_network. Should I replace walking_network -> kind_detail too as part of this pr?

I think it'd be `kind: walking_network` and `kind_detail:iwn` then?

> 2) For the landuse/natural updates, there are some instances where both are set, eg natural=wood and landuse=wood. Which should take precedence?

I think landuse should take precedence OR we should generate 2 different polygons? Where are some examples?

**Comment by rmarianski** [comment]
> I think it'd be kind: walking_network and kind_detail:iwn then?

It was `kind: walking_junction` and `walking_network: iwn` previously. Should we transition to what you mentioned? I assume that the `kind`s would need to get updated in the stylesheets from `walking_junction` -> `walking_network`. And we should probably be consistent with bicycle too, which also calls it `kind: bicycle_junction` at the moment.

> I think landuse should take precedence OR we should generate 2 different polygons? Where are some examples?

Imho 2 polygons would be unexpected, and that landuse probably makes more sense as taking preference. This has `natural=wood` and `landuse=wood` set:
http://www.openstreetmap.org/way/52497271

**Comment by nvkelso** [comment]
I think it'd be `kind: walking_junction` and `kind_detail:iwn` ...

**Comment by nvkelso** [comment]
Agree on preferring landuse.

**Comment by nvkelso** [comment]
Verified all the renames, spot checked the redundant removals, all looking good.
