### ISSUE TITLE
Package for easy installation

### ISSUE THREAD

**Issue by zerebubuth** [tilezen/vector-datasource#854]
Since #211 was fixed, our dependencies are much easier to manage.

It would be nice, if it's possible, to get a `pip install`able tile server from this repo, with released versions.

I think at a minimum, this would need:
- [ ] A public, versioned `vector-datasource` package in PyPI.
- [ ] Scripts/commands to set up the config files.
- [ ] Scripts/commands to download all the data and set up the database.

A workflow like this seems like it would be possible:

```
apt-get install osm2pgsql
pip install vector-datasource
vector-datasource config --init
vector-datasource setup --metro-extract new-york-new-york
vector-datasource server
```

@rmarianski what do you think?

**Comment by nvkelso** [comment]
Seems like we should rename this repo to `tilezen` instead of `vector-datasource`, then?

**Comment by rmarianski** [comment]
:+1:

We might want to discuss whether we want to host the package on pypi though. That'll require that we push all other dependent packages on pypi as well. I'm not against this; we'll just need to update our tagging/release process to also push to pypi whenever we create new releases. A first transition step might be to just host a requirements file and have the the pip install command point to the requirements file on github using a raw link, and then consider pushing all packages to pypi.

We might also want to consider starting a new repo and avoid checking in any data there, eg the shape files, which would make any clones much faster. The scripts can pull these down from external sources, or on an s3 bucket so we can guarantee they won't change.

We should also set up some automation that exercises these steps on a regular basis so we get notified when something breaks.

**Comment by nvkelso** [comment]
We've automated much of this, process changed.
