### ISSUE TITLE
Missing bridleway in Central Park

### ISSUE THREAD

**Issue by sensescape** [tilezen/vector-datasource#859]
* **What did you see?** I didn't see a bridleway, and the paths had a gap in them.
* **What did you expect to see?** Full trail coverage
* **What map location are you having problems with?** https://www.openstreetmap.org/way/387216146
* **Screenshot?** 
<img width="979" alt="screen shot 2016-06-14 at 3 30 33 pm" src="https://cloud.githubusercontent.com/assets/466585/16061949/0906cb7a-3245-11e6-94d9-cb17b03c2c10.png">

**Comment by sensescape** [comment]
For outdoor style

**Comment by nvkelso** [comment]
Looking good!

![image](https://cloud.githubusercontent.com/assets/853051/17959972/6b308a20-6a58-11e6-8662-342e3e328cb1.png)
