### ISSUE TITLE
Audit transforms ordering

### ISSUE THREAD

**Issue by rmarianski** [tilezen/vector-datasource#866]
Now that simplification and clipping is a transformation step, we can reorder transforms for efficiency purposes. In particular, moving any geometry processing transforms that don't need the full geometry _after_ simplification and clipping should be a win.

A bigger audit should happen anyway, to determine if there are other efficiency wins. For example, any transforms that drop features should run as early as possible.

**Comment by nvkelso** [comment]
Moving to v1.1 as this shouldn't result in breaking changes to the API (just performance tuning).

**Comment by nvkelso** [comment]
Closing as process changed and build is pretty fast.
