### ISSUE TITLE
Update tilejson files

### ISSUE THREAD

**Issue by rmarianski** [tilezen/vector-datasource#872]
The tilejson metadata files are out of date. We should update them now and ensure that we have all the layers represented.

Longer term we should consider an automated process to auto-generate them so they don't fall out of date.

**Comment by nvkelso** [comment]
Let's split off the automated piece into a separate issue for the backlog & fix the immediate issue now (add missing layers).

**Comment by nvkelso** [comment]
This is on prod now.
