### ISSUE TITLE
Camp grounds (camp_site) with areas should show up early

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#875]
* **What did you see?** Only at zoom 16 now for Fallen Leaf Campground near Tahoe.
* **What did you expect to see?** Up to zoom 13 if they are big
* **What map location are you having problems with?** 16.86866/38.92667/-120.05147
* **Screenshot?** 
<img width="821" alt="screen shot 2016-06-29 at 14 53 55" src="https://cloud.githubusercontent.com/assets/853051/16471407/5d603012-3e11-11e6-9b0f-2f80f4fa7bb1.png">

**Comment by nvkelso** [comment]
Good news: Zoom ranges are working!

Bad news: The sort order is defaulting to 11, it should be much higher.

**Comment by okavvada** [comment]
That is because they are not specified in the sort key spreadsheet. What should they be set to?

**Comment by nvkelso** [comment]
Between these to (so it gets 92, and everything maze and above gets +1):

```
maze,*,92
generator,*,91
```

**Comment by nvkelso** [comment]
Woot!

![image](https://cloud.githubusercontent.com/assets/853051/17960716/9b286186-6a5c-11e6-9d9f-62cf91418055.png)

And the node only features (here Angle Island) are still only shown later:

![image](https://cloud.githubusercontent.com/assets/853051/17960754/d488263c-6a5c-11e6-9299-23c26107a054.png)
