### ISSUE TITLE
Add lxml.etree to requirements

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#882]
When running the tests on a clean install of macOS it fails to import lxml.etree from: https://github.com/tilezen/vector-datasource/blob/3dc2b1e5a07401051487653a9d74b799e2304f8e/integration-test.py#L14.

**Comment by nvkelso** [comment]
```
$ OVERPASS_SERVER=0.0.0.0 ./scripts/setup_and_run_tests.sh
=== Creating database "vector_datasource_9101"...
=== Enabling database extensions...
CREATE EXTENSION
CREATE EXTENSION
=== Dumping test data...
Traceback (most recent call last):
  File "./scripts/../integration-test.py", line 14, in <module>
    import lxml.etree as ET
ImportError: No module named lxml.etree
```

**Comment by zerebubuth** [comment]
Hmm... there must be something going on that I don't understand. LXML is [included in `requirements.txt`](https://github.com/tilezen/vector-datasource/blob/3dc2b1e5a07401051487653a9d74b799e2304f8e/requirements.txt#L6) and `etree` doesn't look like its a different package.

Do you have the output of running `pip install -r requirements.txt`? Perhaps something went wrong with the lxml install?

**Comment by nvkelso** [comment]
I re-installed the requirements and tests are no longer failing.
