### ISSUE TITLE
Natural Earth Road and Ferry need normalized kind values

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#890]
The Ferry between UK and France and the two islands of New Zealand are showing up as `Ferry` at zoom 7, and then it's `ferry` from OSM after that.

/cc @sensescape

**Comment by rmarianski** [comment]
@nvkelso looks like the ne roads will come back with a kind of `Road` too. We should probably normalize those as well. What should they be? `highway`, `major_road`?

**Comment by rmarianski** [comment]
We're passing through some more of the [ne properties](https://github.com/tilezen/vector-datasource/blob/15513013f4fbd5c55c2106773029171b2bc93491/yaml/roads.yaml#L109-L121). Should we try to normalize those into a `kind` to match what we do for osm data?

**Comment by nvkelso** [comment]
@rmarianski what does this line do? https://github.com/tilezen/vector-datasource/blob/15513013f4fbd5c55c2106773029171b2bc93491/yaml/roads.yaml#L116

```
name: {col: name, ignore: true}
```

**Comment by rmarianski** [comment]
Looks to be an implementation detail to work around duplicate parameters in the function signature. It still worked for me locally when removing all `ignore` references from the yaml, so maybe we should drop them to prevent confusion in the future.

**Comment by nvkelso** [comment]
> @nvkelso looks like the ne roads will come back with a kind of Road too. We should probably normalize those as well. What should they be? highway, major_road?

Good idea! Here's a lookup table using the Type values in NE using the High Road lens and moving towards the new `kind_detail` to store the equivalent OSM values (but not in the highway property). 

```
"ne:Type","tilezen:kind","tilezen:kind_detail"
"Major Highway","highway","motorway"
"Beltway","highway","motorway"
"Bypass","highway","motorway"
"Secondary Highway","major_road","trunk"
"Road","major_road","primary"
"Track","path","track"
"Unknown","minor_road","unclassified"
"Ferry Route","ferry",""
"Ferry, seasonal","ferry","seasonal_ferry"
```

**Comment by rmarianski** [comment]
Do we still want to pass through the ne properties? Sounds like the normalization can allow us to remove `type`. That ok with you?

Is `level` still useful?

For roads the `level` values are:
* U/C
* Federal
* Other
* Interstate
* State
* Ferry
* E

And for ferries:
* Other
* Ferry
* E

**Comment by rmarianski** [comment]
Looking through the data, it seems like we'll never show any seasonal ferries from ne, because they all have a scalerank of 9, and we only query osm data starting at z8+.

**Comment by nvkelso** [comment]
Should we ignore them or keep them in there in case someone changes the
ne-osm zoom switchover later?

**Comment by nvkelso** [comment]
Looking more closely at the data, there are only 5 **seasonal ferries** so let's just ignore them.

Yes, let’s remove NE’s `type` value.

The `level` stuff is more complicated. I think it could potentially be useful for shield generation so let's leave it in there for now. But we probably need to deal with it before the v1.0 release.

**Comment by nvkelso** [comment]
@rmarianski Hmmm, looks like `expressway` from Natural Earth is a better approximation of `motorway`:

**Updated table**, including ferry:

```
"ne:Type","ne:expressway","tilezen:kind","tilezen:kind_detail"
,1,"highway","motorway"
"Major Highway",,"highway","trunk"
"Beltway",,"highway","trunk"
"Bypass",,"highway","trunk"
"Secondary Highway",,"major_road","primary"
"Road",",major_road","secondary"
"Track",,"minor_road","tertiary"
"Unknown",,"minor_road","tertiary"
"Ferry Route",,"ferry",""
"Ferry, seasonal",,"ferry","ferry"
```

**Comment by nvkelso** [comment]
Verified.
