### ISSUE TITLE
Modify High Road logic to pull out airport lines out of minor roads

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#895]
* **What did you see?** Airport runways appear as minor roads.
* **What did you expect to see?** They're import enough of a top level category `runway` and `taxiway` should be pulled out into a new `aeroway` kind, with runway and taxiway preserved as `kind_detail`.
* **What map location are you having problems with?** SFO airport south of San Francisco.

```
      aeroway: runway
      aeroway: taxiway
```

**Comment by nvkelso** [comment]
See: 

- https://github.com/tilezen/vector-datasource/blob/15513013f4fbd5c55c2106773029171b2bc93491/yaml/roads.yaml#L366-L388

**Comment by nvkelso** [comment]
@nvkelso to add sort order recommendation.

**Comment by nvkelso** [comment]
The **landuse** polygons for `runway` and `taxiway ` should sort immediately above the lines in the **roads**  layer (so lowest is line, line, polygon, polygon to topmost). So many sort orders for the other road features will need to bump up.

**Comment by rmarianski** [comment]
Couple of questions:

Not sure I follow exactly what should happen for the sort_order. The landuse values are:

runway => 63
apron => 62
taxiway => 61

And in roads:

z>=15 (not tunnel)
runway => 427
taxiway => 426
z>=15 (tunnel)
runway => 327
taxiway => 326
z<15
runway => 377
taxiway => 376

The rest of the values in both roads and landuse are close in value to those. If we sort the aeroway landuse polygons immediately above, wouldn't we have to bump the other landuse values up as well too (by a few hundred)? And then probably the rest of the roads on top of that?

Additionally, should we continue to include the `aeroway` tag on roads features? Or is that now completely captured by the `kind_detail`? If we want to drop it, we might have similar opportunities for normalizing some of the other roads tags into a `kind_detail`.

**Comment by nvkelso** [comment]
Yes, we need to bump most the other road values up by 2 (zoom <15) and then 4 (zoom >= 15), and probably enable zoom ranges in landuse CSV. 

_Note: I think the above proposal is better than the alternative of putting the runway and taxiway road lines below the landuse in the landuse range. We've talked about dynamically re-sorting the landuse sort values (based on area) as a post-processing step, this probably complicates that._

Road `kind_detail` is covered in https://github.com/tilezen/vector-datasource/issues/719. We could probably remove the `aeroway` tag after that issue is completed (but may be harder for people to transition to Mapzen tiles from another provider).

**Comment by nvkelso** [comment]
We talked more about this in Slack today, with a big comprehensive list of all kinds and their sort order being passed around. With some experimentation we probably need to tuck the default airport lines (runway, taxiway) **under** the existing landuse polygon sort values instead of the above proposal.

**Comment by nvkelso** [comment]
👍
