### ISSUE TITLE
Update street name lookup

### ISSUE THREAD

**Issue by rmarianski** [tilezen/vector-datasource#897]
We use [StreetNames](https://pypi.python.org/pypi/StreetNames) to shorten road names. Pelias has a more comprehensive [list](https://github.com/pelias/schema/blob/master/street_suffix.js) that we might want to start using.

**Comment by nvkelso** [comment]
Good find! Their list is huge, maybe we should cherry pick some of them into `StreetNames`?

**Comment by nvkelso** [comment]
(Looks like pelias prefers lowercase names and we prefer TitleCased so we'd need to adapt their code one way or another.)

**Comment by rmarianski** [comment]
Big thanks to @missinglink for the pointer. :synergy:

**Comment by nvkelso** [comment]
Closing stale issues.
