### ISSUE TITLE
Move to EPSG:3857

### ISSUE THREAD

**Issue by zerebubuth** [tilezen/vector-datasource#908]
At the moment, the database is created with EPSG:900913, as this was the default "mercator" projection in the past. The defaults in `osm2pgsql` have been updated to use EPSG:3857 which is now the standard "Popular Visualisation CRS", and we should move with the times.

Although this can be done with a database migration, because of the external dependency on `osm2pgsql` versions and update scripts, it might be better to do it as part of the database reload which is coming with #876 et al.

**Comment by nvkelso** [comment]
This is working.
