### ISSUE TITLE
Move static assets to S3

### ISSUE THREAD

**Issue by zerebubuth** [tilezen/vector-datasource#909]
We currently bundle some static assets within the repository, for example; transformed Natural Earth data. Some other assets are downloaded at setup time, for example openstreetmapdata land/water shapefiles. This mixture doesn't give us, or anyone using `vector-datasource`, any control over the versions of assets used, and evades the issues around updating to new data releases.

We should move the assets out to an S3 bucket and make sure the names are versioned (e.g: with a timestamp prefix), and include specific versions in `vector-datasource`. As a separate project, we should script the updates so that new versions are uploaded to S3 and the tiles with differences are identified for re-rendering.

**Comment by nvkelso** [comment]
@zerebubuth I think this has been completed, can you verify please?

**Comment by zerebubuth** [comment]
Yes, this was done as part of #943, but we forgot to link it to this issue.
