### ISSUE TITLE
Missing miniature, possibly other railway types

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#955]
In this old issue https://github.com/tilezen/vector-datasource/issues/353 we noted that `railway=miniature` should be included in tiles, but isn't currently. There is a test case in the San Francisco Zoo.

In addition to adding miniature, review the list below to audit if we should add any other types:
- railway=rail
- railway=subway
- railway=preserved
- railway=narrow_gauge
- railway=abandoned
- railway=disused
- railway=funicular
- railway=monorail
- railway=miniature
- railway=light_rail
- railway=tram

**Comment by nvkelso** [comment]
Further customer feedback on this (edited from ticket):

**Problem:**

The map does not show railways marked with `railway=disused`
but shows railways marked with `railway=abandoned`.

**See OSM Wiki docs:** 

- **railway=disused** http://wiki.openstreetmap.org/wiki/Tag:railway=disused
- **railway=razed** https://wiki.openstreetmap.org/wiki/Demolished_Railway ).

User suggests an abandoned or razed railway is less relevant than a disused railway, so it
seems wrong to show them while hiding the disused railways.

**Examples:**

- Razed railway https://www.openstreetmap.org/way/521306179
- Abandoned railway https://www.openstreetmap.org/way/521306174
- Disused railway https://www.openstreetmap.org/way/520731856 (not shown)

**Comment by matkoniecz** [comment]
Just an usecase for railway=disused - I wantef to show it as as an feature useful for an orientation.

**Comment by nvkelso** [comment]
Still a problem.

**Comment by nvkelso** [comment]
Not yet in a dev build.

**Comment by nvkelso** [comment]
SF Zoo train finally on the map! /cc @burritojustice 

![image](https://user-images.githubusercontent.com/853051/57430645-314ba000-71e5-11e9-942d-445aee38bcd6.png)
