### ISSUE TITLE
Installing gives error column "l10n_name" does not exist

### ISSUE THREAD

**Issue by rmglennon** [tilezen/vector-datasource#971]
Following these instructions, https://github.com/tilezen/vector-datasource/wiki/Mapzen-Vector-Tile-Service, a user reported this problem with installing, as we're in this an intermediate stage before 1.0 release. The instructions load up the production schema for WoF data, which is missing that column that was added recently. 

cc @rmarianski

---

wget http://localhost:8080/all/16/19293/24641.json

gives me an error:

* Running on http://localhost:8080/ 
* Restarting with reloader 
127.0.0.1 - - [17/Aug/2016 15:10:24] "GET /all/16/19293/24641.json HTTP/1.1" 500 
- 
Traceback (most recent call last): 
File "/install/tileserver/tileserver/__init__.py", line 195, in __call__ 
response = self.handle_request(request) 
File "/install/tileserver/tileserver/__init__.py", line 290, in handle_request 
coord, self.layer_config.all_layers) 
File "/install/env/lib/python2.7/site-packages/tilequeue/query.py", line 198, 
in __call__ 
raise async_exception 
ProgrammingError: column "l10n_name" does not exist 
LINE 78: %#l10n_name AS tags 
^

**Comment by zerebubuth** [comment]
Does this mean we should explicitly change the instructions so that instead of saying:

> WARNING: If you are standing up your own instance of the Tilezen stack (rather than doing development), it's best practice to checkout the latest tagged release rather than running off master.

We say something more like?

> Check out the latest tagged release. Do not use master.

**Comment by rmarianski** [comment]
Since we have an "assets" location now, which at the moment only holds the shape files, I'm hoping that we can dump both prod and dev versions of wof data there. Then we can have instructions that point to different pgdump links based on the latest tagged release vs master.

But we might want to make a quick change to the instructions now to prevent confusion until we get there.

**Comment by zerebubuth** [comment]
The dev dump is still likely to be behind current master (although perhaps not in ways that matter). Do we plan to handle that by automatically knowing how to migrate the dump to current, or should we just bail and pop up a message which says "this might not work - if you want it to work, use a tagged release"?

**Comment by rmarianski** [comment]
Good point, perhaps both? Maybe as part of the instructions we should have an adjustment migration that gets run that would account for the discrepancy between master and what's deployed on dev, at least schema wise to ensure that the table structure matches.

Oddly enough, it looks like the schema should get created properly as part of the setup, but I assume what happens is that the data import overrides that with the structure that's in the data.

**Comment by zerebubuth** [comment]
Oh, yeah, depends on what flags are on the shapefile import... we should check that.

And we should have tests for the install procedure for master and the latest release. Parts of it are tested with the CI, but we should have a stand-alone shell script for it too. Perhaps only run once a day, though? I'm not sure if that's possible with CircleCI, or we'd have to do some sort of "cloud cron"?

**Comment by rmarianski** [comment]
> Oh, yeah, depends on what flags are on the shapefile import... we should check that.

I mean just the wof part. The rest I think are ok.
Specifically, when we run perform-sql-updates, we first call schema.sql, which sets up the wof tables. These tables are empty (short of the placetype id lookup). Subsequently, we ask the user to pull down the pgdump, and run pg_restore with the --clean option, which is dropping the previously created table with the necessary column.
Tangentially, my version of pg_restore doesn't have an --if-exists option, maybe that was added more recently? I'm running ubuntu 14.04.

> And we should have tests for the install procedure for master and the latest release. Parts of it are tested with the CI, but we should have a stand-alone shell script for it too. Perhaps only run once a day, though? I'm not sure if that's possible with CircleCI, or we'd have to do some sort of "cloud cron"?

:+1: 
One way we might want to do this is to package up the steps in a dockerfile, and then have the test use it directly. That way we can share this with users as a way to get started as well.

**Comment by nvkelso** [comment]
Let’s target the documentation at last released production version, with
NOTES for what do do if someone wants to be on latest master (dev).

On Thu, Aug 18, 2016 at 11:34 AM, Robert Marianski <notifications@github.com

**Comment by iandees** [comment]
I dumped the WOF tables from the dev database this afternoon:

```
pg_dump -t wof_neighbourhood -t wof_neighbourhood_placetype -Fc -f wof_neighborhoods.pgdump -h localhost -U gisuser gis
```

...and posted the dump to S3:
https://s3.amazonaws.com/mapzen-tiles-assets/wof/dev/wof_neighbourhoods.pgdump

I will update the documentation here in a moment.

**Comment by iandees** [comment]
I updated the docs and my local setup is working now! 👍
