### ISSUE TITLE
Use 2 char language codes not 3

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#972]
Following up on https://github.com/tilezen/vector-datasource/pull/816, it looks like iOS, Android, and web all natively prefer 2 char language codes instead of 3 char code. Instead of forcing everyone to shim between, we should just state the 2 char code instead.

/cc @bcamper

**Comment by nvkelso** [comment]
And consider whitelisting country code (e.g. 2nd part of `en-gb`).

**Comment by nvkelso** [comment]
This is working on dev for me. 

But one minor documentation fix required that `ja` for Japanese instead of `jp` (see https://github.com/tilezen/vector-datasource/pull/975#discussion_r76197406).

**Comment by rmarianski** [comment]
@dianashk we had previously talked about using 3 letter codes, but looks like 2 letter codes are the way to go.

**Comment by nvkelso** [comment]
Fixed https://github.com/tilezen/vector-datasource/issues/972#issuecomment-242310941 in 24430af2591163e669d3c3c6c3ffefdbc5ad51dc.
