### ISSUE TITLE
Tiles should include POIs, places that have fractional zoom

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#976]
Olga noticed that some tiles didn't include features with a fractional zoom until the next rounded up full integer zoom. For instance: if the POI is min_zoom 13.2 it would be expected to be in the zoom 13 tile, but it is only appearing in the zoom 14 tile.

**Comment by zerebubuth** [comment]
Yup. There's a lot of places where we check `min_zoom <= zoom`, but if `zoom` only takes integer values, then that's wrong, it should be `min_zoom < zoom + 1`. There are a couple of solutions to this:

1. Fix that code in all the places it exists.
2. Don't support fractional `min_zoom`.

I'm in favour of the latter, as `min_zoom` is really only a hint anyway.

**Comment by nvkelso** [comment]
I'd like to take door 1, fix the code. 

We curate some neighbourhood `min_zoom` values upstream in Who's On First assuming they will show up at the fractional zoom, but since the feature is only available at the next integer zoom it doesn't work. We also spend a effort getting fractional zooms on POIs. When we don't include these earlier it creates sparse looking vector maps as the fraction gets closer to the next integer (e.g. zoom 13.8 looks sparse compared to zoom 13 or zoom 14).

**Comment by rmarianski** [comment]
What does fixing the code mean? Would we make the min zoom values floats throughout? And then have the queries ask for features < zoom + 1?

**Comment by nvkelso** [comment]
Yes, I think so.

The min_zoom values with 13.86747474 are not super useful client side, so
maybe pair this with a final transform that clips them to 13.86 or 13.867
(after tile kind budgets might sort and trim features)? Data curation (e.g.
in Who’s On First) would almost only be to 13.8 tenths, but collision
sorting client side is probably useful to hundredths or thousandths.

**Comment by zerebubuth** [comment]
We currently don't have any way of getting fractional zooms from `places` - all the NE data pulls in `scalerank`, which is an integer, and the values in `places.yaml` are all integers. Do we want to make the change anyway so that we can do it in the future?

**Comment by nvkelso** [comment]
I think the `places` layer could contain fractional zooms when sourced from Who's On First: 

- https://github.com/tilezen/vector-datasource/blob/master/queries/places.jinja2#L77

But because our WOF table schema incorrectly converts Who's On First floats to ints we only get ints out?

- https://github.com/tilezen/vector-datasource/blob/5f5e09598fcc79f8c5a80b961a5090dbad264e14/data/schema.sql#L21-L22

Stephen and I just edited Petworth in DC to have a min_zoom of 14.5 in WOF for a data sample:

- https://whosonfirst.mapzen.com/spelunker/id/85841475/#14/38.9465/-77.0185
- https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data/master/data/858/414/75/85841475.geojson

**Comment by zerebubuth** [comment]
Worse than "incorrectly converts" - it looks like [it will bail with an error](https://github.com/tilezen/tilequeue/blob/961d31c4dbb3ea008317c6760b7c7a2f0289fe7c/tilequeue/wof.py#L293-L308) if `min_zoom` or `max_zoom` are not integers. I've added tilezen/tilequeue#110 to track that, separately from updating the schema in this task.

**Comment by nvkelso** [comment]
@zerebubuth Do we also need this for the landuse layer?

**Comment by zerebubuth** [comment]
@rmarianski already [extended support](https://github.com/tilezen/vector-datasource/pull/989/commits/4ce389c9d89d38b271f8f0130f4608188e3644ba) to the `landuse` layer and other layers.

**Comment by nvkelso** [comment]
For the sample **Petworth** from Who's On First which should have a fractional `min_zoom` it doesn't:

http://tile.dev.mapzen.com/vector/v1/all/15/9373/12529.topojson?api_key=vector-tiles-HqUVidw

Should be 14.5, but is 14.

But looks like that is the fault of Boundary Issues [saving it](https://github.com/whosonfirst-data/whosonfirst-data/commit/07cbb130e1d6c4fec6ae3d61eeb62c72eff07ea2) as an int instead of a float?

Updating the data again, will re-test.

**Comment by nvkelso** [comment]
But while we changed the type of the min_zoom in the database, we still need to export the `min_zoom` value on all features.

The following layers need that added (to the jinja files):

- boundaries
- roads
- transit
- water

But I have verified that `min_zoom` is now only has hundredth precision (x.xx instead of x.xxxxxx like before).

**Comment by nvkelso** [comment]
Verified additions on 4 requested layers. 

I don't see `min_zoom` on **earth** layer features, but that's a minor concern for next release: https://github.com/tilezen/vector-datasource/issues/1073
