### ISSUE TITLE
Update shapefile import process

### ISSUE THREAD

**Issue by rmarianski** [tilezen/vector-datasource#979]
Reprojecting some of the shapefiles to mercator can result in some invalid geometries.

The current process imports the shapefiles via make files using ogr2ogr. Previously, we had resolved this just by calling st_makevalid in the database after import, and then re-exported the fixed data into the shapefiles that were checked into the repo.

What we might want to do instead is move the import process out of make files, and instead have a python script that drives the process. This will allow us to "fix" the geometries directly, and we can probably just go from source shape file to database directly. We've needed to grow a python script to tile one of the ne shapefiles, so we're being guiding down this path anyway.

**Comment by nvkelso** [comment]
+1

**Comment by nvkelso** [comment]
We've made progress on this in the last few releases, closing.
