### ISSUE TITLE
Oh, Switzerland

### ISSUE THREAD

**Issue by meetar** [tilezen/vector-datasource#995]
* **What did you see?**

The "name" field for Switzerland contains a CSV list of all the native names for the country in each of the official languages.

* **What did you expect to see?**

"Confoederatio Helvetica"

… or maybe the most common native name, which would be Die Schweiz, as German-speakers make up about 2/3 of the population. The alternate names are already in their name:lang fields.

I further imagine Switzerland is not the only country in this situation – do we have an entry for "official" names like "Confoederatio Helvetica"? Either way, a CSV list isn't particularly usable, as data fields go…

* **Screenshot?** _Props for animated gifs._

<img width="373" alt="screen shot 2016-08-25 at 11 49 02 am" src="https://cloud.githubusercontent.com/assets/459970/17976222/8af46afe-6aba-11e6-8d67-ca4009fee618.png">

**Comment by rmarianski** [comment]
It's like that in the data itself: http://www.openstreetmap.org/node/1504546320

Not sure what we'd want to do. @iandees, @zerebubuth, @nvkelso ideas?

**Comment by zerebubuth** [comment]
That list of names is coming straight from the `name` tag of the [country node](http://www.openstreetmap.org/node/1504546320).

There is an `official_name:*` set of tags too, and the one you want appears to be called `official_name:la`.

**Comment by nvkelso** [comment]
@meetar Data will be data :\ 

My recommendation is to use a specific `name:*` language code, which is how Bubble Wrap is now configured.

**Comment by iandees** [comment]
This has perplexed me for several months on OSM. I don't think there's much precedent for using comma-separated names in the `name=` tag. I'm surprised it has lasted for so long. Also, it looks silly on osm.org

![image](https://cloud.githubusercontent.com/assets/261584/17977680/ac336ae8-6ac0-11e6-9b93-9c12075c4a9f.png)

**Comment by meetar** [comment]
Fair enough – suggested solution accepted :+1:

And if I can find my hip waders I'll take a look at the situation on osm…

**Comment by ImreSamu** [comment]
> comma-separated names in the name= tag. 

more info  : http://wiki.openstreetmap.org/wiki/Multilingual_names
* my favorite : Belgium -  "first mapper rule".   
* in Sardinia - the separator is '/' : 
 *  "Terranoa/Olbia " http://www.openstreetmap.org/node/2615891332
* in South Tyrol - the separator is '-' :   
 *   "Bolzano - Bozen"  http://www.openstreetmap.org/node/64776486

**Comment by nvkelso** [comment]
@ImreSamu Thanks for the background!

**Comment by meetar** [comment]
Nice, thanks for the links! I knew that would be in there somewhere :)
