### ISSUE TITLE
topojson.merge issues

### ISSUE THREAD

**Issue by veltman** [tilezen/vector-datasource#998]
Hey there,
  I've noticed that when using the TopoJSON tiles, `topojson.merge()` is a pretty iffy operation, because a decent number of tiles in urban areas contain at least one feature with a topological problem that causes the lib to throw an error.  As an example, consider:

https://vector.mapzen.com/osm/landuse/14/8190/5448.topojson

It contains the following feature, that, when expanded to GeoJSON, looks like this:

``` json
{
  "type": "Feature",
  "properties": {
    "kind": "parking",
    "area": 356,
    "sort_key": 104,
    "source": "openstreetmap.org",
    "min_zoom": 13.0178,
    "id": 194387790
  },
  "geometry": {
    "type": "Polygon",
    "coordinates": [
      [
        [
          -0.025212764739602232,
          51.50874245880317
        ],
        [
          -0.025212764739602232,
          51.50874245880317
        ],
        [
          -0.025212764739602232,
          51.50874245880317
        ],
        [
          -0.025212764739602232,
          51.50874245880317
        ]
      ]
    ]
  }
}
```

The coordinates are a little different than in the GeoJSON vector tile, or in OSM itself, probably due in part to quantization/re-expansion:

TopoJSON version - four identical points
GeoJSON version - a line with two extra identical points
OSM version - a normal polygon

In any case, the fact that it's a "polygon" of four identical points is not really a problem when just displaying all the features, but if you try to call `topojson.merge()` on a set of polygons that includes it, the TopoJSON lib will throw an error.  I've gotten the same error in a variety of other tiles.

I'm not sure what's to be done about this, but wanted to note it just in case.  It seems like there are at least three potential parts of the issue:
1. Underlying OSM data weirdness - probably can't be helped?
2. TopoJSON quantization/expansion turning valid geometries into problem ones - e.g. a very, very small polygon that becomes a zero-area polygon. It seems like this case could at least be detected during processing by converting features there and back and confirming they're still valid.
3. TopoJSON `.merge()`/`.mergeArcs()` logic. I'm not sure whether a zero-area polygon being unmergeable is the intended behavior, I'll probably file an issue on the repo for it. This same problem might also come up with `topojson.mesh()`.

**Comment by rmarianski** [comment]
Looks like this slipped through the cracks, sorry about that. We've seen this come up in geojson and mvt formats in the past. I haven't looked through all the details yet, but I think that we'll want to avoid emitting invalid geometries.

**Comment by nvkelso** [comment]
@veltman We spend time making MVT topologically consistent, but do have any plans on doing the same for TopoJSON.
